### ISSUE TITLE
[ISSUE] dbx execute - log print 

### ISSUE THREAD

**Issue by rfcortes** [databrickslabs/dbx#112]
## Expected Behavior
dbx execute: print logs to standard output from Databricks CICD templates job

## Current Behavior
Logs do not print to standard output 

## Steps to Reproduce (for bugs)
define job with log and execute 

```
class SampleJob(Job):
    def launch(self):
        self.logger.warn("print me")
```

## Your Environment

* dbx version used:  version ~> 0.2.2
* Databricks Runtime version: 9.1 LTS

**Comment by renardeinside** [comment]
hi @rfcortes , 
currently exporting logs on the flight via API from the clusters is not supported by the platform itself (it's not the limitation of dbx). You can see your logs in the Cluster logs tab, or by exporting them into your logging analysis solution. I would recommend reaching out to your Solutions Architect for further guidance.
