### ISSUE TITLE
[BUG] Issue with encoding  :sparkles:  character when running dbx deploy command

### ISSUE THREAD

**Issue by adleonar** [databrickslabs/dbx#121]
## Expected Behavior
Deployment finishing successfully 

## Current Behavior
Error
UnicodeEncodeError: 'charmap' codec can't encode character '\u2728' in position 88: character maps to "undefined"

## Steps to Reproduce (for bugs)
Running dbx deploy

## Context
When running "dbx deploy" command there is an error just after 
"Updating job definitions - done"  log
and before
"Deployment for environment {environment} finished successfully" log message.

It is due to problem with encoding the :sparkles: emoji (https://www.fileformat.info/info/unicode/char/2728/index.htm). Change was added in the latest release namely in
https://github.com/databrickslabs/dbx/pull/115/files
in dbx/commands/deploy.py  file.

Using previous 0.2.2 version resolved the issue.

## Your Environment
Azure Devops MSFT hosted agent (vmImage: "windows-latest")
Python 3.8 x64

* dbx version used: 0.3.0
* Databricks Runtime version:

**Comment by renardeinside** [comment]
HI @adleonar , 

thanks for raising the issue! I wasn't expecting that problem with emoji's :) 
I'll take care of this one.

**Comment by renardeinside** [comment]
fixed in the above-mentioned PR, will be released in 0.3.1. Thanks for raising the issue @adleonar !

**Comment by adleonar** [comment]
No problem @renardeinside ! Thank you for fixing it
