### ISSUE TITLE
[FEATURE] Add Support for `Jinja2` Deployment Files

### ISSUE THREAD

**Issue by elenamartina** [databrickslabs/dbx#123]
## Expected Behavior
It would be beneficial to be able to define environment variable specific logic within a deployment file, with if statements, for loops, filters and other functionality that Jinja2 allows. This would enable, for example, the same job deployment configuration file to be reused for different scopes and environments and would improve code reusability.

This functionality would also automatically allow [Passing environment variables to the deployment configuration](https://dbx.readthedocs.io/en/latest/environment_variables.html), which is currently being hardcoded using regex patterns as implemented in [this pr](https://github.com/databrickslabs/dbx/pull/80).

Given a deployment file `deployment.json.j2`:

```jinja2
{
    "default": {
    "jobs": [
        {
        "name": "your-job-name",
        {% if (ENVIRONMENT == "production") %}
        "timeout_seconds": {{ TIMEOUT | default(-1)  }},
        {% else %}
        "timeout_seconds": {{ TIMEOUT | default(2700) }},
        {% else %}
    [ ...]
```

...or a deployment file `deployment.yaml.j2`:

```jinja2
environments:
  default:
    jobs:
      - name: "your-job-name"
        {% if (ENVIRONMENT == "production") %} 
        timeout_seconds: {{ TIMEOUT | default(-1)  }}
        {% else %}
        timeout_seconds: {{ TIMEOUT | default(2700) }}
   [ ... ]
```

there could be a Deployment Config class defined as
```python
class Jinja2DeploymentConfig(AbstractDeploymentConfig):
```
which could render Jinja and then pass the rendered template onto a `json` or `yaml` loader/reader.

## Current Behavior
Currently, only plain `json` and `yaml` deployment files are supported.
No custom support is provided for logic/conditional statements, filters like `| lower` and for loops in deployment files.

## Your Environment

* dbx version used: v0.2.2
* Databricks Runtime version: 9.1LTS

**Comment by renardeinside** [comment]
Closed in #124 , will be released in 0.4.0 
Thank you so much for contributing to the project @elenamartina !
