### ISSUE TITLE
Are there plans to integrate Delta Live tables / pipelines into dbx?

### ISSUE THREAD

**Issue by pgorsira** [databrickslabs/dbx#129]
It would be nice to be able to declaratively describe delta live pipelines with dbx the same way we can do so with jobs. Just wondering if this is on the roadmap.

**Comment by renardeinside** [comment]
Hi @pgorsira, 

currently, DLT doesn't support local-based development (only in the notebooks). 
Therefore dbx doesn't support DLT at the moment. As soon as DLT will be supported in external environments, it will be available in dbx.
