### ISSUE TITLE
[BUG] DBX CLI creating jobs that already exist, causing duplicates

### ISSUE THREAD

**Issue by Teun-Roefs** [databrickslabs/dbx#136]
## Expected Behavior
Executing: `dbx deploy --deployment-file ../xxx/jobs/deployment.yaml --no-rebuild -e MOD`
```
[dbx][2022-01-25 09:31:43.874] Processing deployment for job: xxx
[dbx][2022-01-25 09:31:43.915] Updating existing job with id: 542433 and name: xxx
```

1. DBX deploying the deployment.yaml file and selecting the right environment
2. DBX CLI checking for existing jobs in the workspace
3. DBX only creating jobs if they do not exist yet, else create
4. Rinse and repeat

## Current Behavior
1. DBX deploying the deployment.yaml file and selecting the right environment
2. DBX CLI checking for existing jobs in the workspace
3. DBX creating jobs that already exist even though the name is the same

In the current situation, multiples of the same job are created in the Databricks workspace, even though the job already exists.

Extra information:
* Some of the jobs were created manually prior to using the DBX CLI. After removing these and running the pipeline again, jobs are not re-created
  * This however happened also in other Databricks workspaces that did not have any existing jobs
* Running a `databricks jobs list` using the API version 2.0 gives all jobs including duplicates up to 20 jobs. Using the `limit` option gives a maximum of 25 jobs. Running the `databricks jobs list` using API version 2.1 results in a subset of most recent jobs, no duplicates

Checking the code it seems DBX is using `JobsApi`: https://github.com/databrickslabs/dbx/blob/af3407139a6d03fb897aec58e574218b55be7d5d/dbx/commands/deploy.py#L453

There is no call made using a limit or subset, which leaves me wondering if DBX is having an issue where it only retrieves the default of 20 jobs rather than using the same approach as the Databricks `--all` option and retrieving all jobs or that the issue is in the JobsAPI itself.

See: https://github.com/databricks/databricks-cli/blob/8e2849a91b594cadba702e13aebcc391afa6c54e/databricks_cli/jobs/api.py#L34 for the actual code in the Databricks CLI.

Does DBX take into account the `has_more` feature in the 2.1 Jobs API?  https://docs.databricks.com/dev-tools/api/latest/jobs.html#operation/JobsList

## Context
DBX is used to manage jobs through a `deployment.yaml` file. Every time our Azure DevOps repository is updated, the pipeline will trigger the update/creation of these jobs based on the `deployment.yaml` file in the repository and the environment that is used in the command.

The pipeline is triggered and installs `dbx`, sets up a `.databrickscfg` file to use for the environments and deploys the jobs that are in the `deployment.yaml` file. 

## Your Environment

* dbx version used: 0.3.0
* Databricks Runtime version: 9.1-LTS

**Comment by renardeinside** [comment]
hi @Teun-Roefs , 
thanks a lot for raising this issue! 
I've provided a fix and this will be covered in 0.3.1
