### ISSUE TITLE
Unneeded argument "--deployment-file" on "dbx launch" command at integration tests

### ISSUE THREAD

**Issue by 7ose** [databrickslabs/dbx#141]
## Expected Behavior
python_basic template uses dbx launch for running integration tests without error.

## Current Behavior
When trying to do integration tests, I get the following error

```
Run dbx launch --deployment-file conf/deployment.yml --job=mlops-project-dbx-sample-integration-test --as-run-submit --trace
Usage: dbx launch [OPTIONS]
Try 'dbx launch -h' for help.

Error: No such option: --deployment-file
Error: Process completed with exit code 2.
```

dbx launch doesn't have or need the --deployment-file option

## Steps to Reproduce (for bugs)
* Use dbx to create a new proyect based on python_basic template
* Set your DATABRICKS_HOST and DATABRICKS_TOKEN on GitHub Actions
* Commit and push
* Check the pipeline for the error in the integration tests step

## Context
I'm trying to do a deployment of a raw project based on the template using GitHub Actions

## Your Environment

* dbx version used: 0.3.0
* Databricks Runtime version: 10.2

**Comment by renardeinside** [comment]
resolved in the referenced PR, will be released in 0.3.1, thanks for raising this one @7ose!
