### ISSUE TITLE
Dbx does not uninstall old versions of the same deployed packages

### ISSUE THREAD

**Issue by giovannipapini** [databrickslabs/dbx#148]
## Expected Behavior

For new deploys I would expect that dbx uninstalled older versions of the same jars if present in the specified cluster

## Current Behavior

The packages are not only left in dbfs (which I would expect in order to recover them if needed) but also left in the list of installed libraries, creating possible conflicts

## Your Environment

* dbx version used: 0.3.0
* Databricks Runtime version: 9.1 LTS

**Comment by renardeinside** [comment]
hi @giovannipapini , 
could you please clarify a bit - this uninstallation doesn't happen on interactive clusters?

**Comment by giovannipapini** [comment]
Yes: when I deploy a new version of the same jar library I can still see the older version installed on the cluster "Libraries" page, with of course a different source. This thing is repeated each time I perform a new deploy from Azure pipelines, generating a long list of same-name installed libraries. I have to manually uninstall all of them each time, it would be much easier to simply have something like a `--disinstall-previous-version-if-any` option in the deploy phase.

Thank you for the quick reply!

**Comment by renardeinside** [comment]
> Yes: when I deploy a new version of the same jar library I can still see the older version installed on the cluster "Libraries" page, with of course a different source.

Unfortunately, this is not supported by the interactive clusters logic - jar-library de-installation requires interactive cluster restart. We can implement a logic that adds a re-start step, but in my experience people would prefer using job clusters for such runs. 
For example you use local unit-testing setup for quicker development loop, and then launch the code on a job cluster with attached instances pool for integration tests.
