### ISSUE TITLE
Non posix path used during deployment of job on Windows

### ISSUE THREAD

**Issue by SSM-david-lynn** [databrickslabs/dbx#154]
## Expected Behavior
Posix paths should be used in the json to create a job when running dbx deploy on Windows

## Current Behavior
Remote paths are being escaped causing the jobs create api to fail with a 400 and error code INVALID_PARAMETER_VALUE

## Steps to Reproduce (for bugs)
test_deploy_path_adjustment_json and test_deploy_path_adjustment_yaml in test_deploy.py fail on windows

## Context
Running with remote python files and tasks will cause dbx to escape the \ in the path instead of converting the path to posix
` dbx deploy --deployment-file=./conf/deployment.json`

Example output:
` "python_file": "dbfs:\\Shared\\dbx\\projects\\sample_project\\1c585cf2ff01418bb8de42a5a6a7dbf6\\artifacts\\run_job.py"`

Expected output:
` "python_file": "dbfs:/Shared/dbx/projects/sample_project/1c585cf2ff01418bb8de42a5a6a7dbf6/artifacts/run_job.py`

## Your Environment
python 3.8.10
* dbx version used: 0.3.2
* Databricks Runtime version:

**Comment by renardeinside** [comment]
hi @SSM-david-lynn , 
thanks a lot for opening the issue and providing the bug fix.

**Comment by renardeinside** [comment]
Closed in #157, will be released in 0.3.3.
