### ISSUE TITLE
Incorrect S3 URI used for remote path during deployment of multitask job

### ISSUE THREAD

**Issue by castillo-luis** [databrickslabs/dbx#156]
## Expected Behavior
Correct s3 URI used for uploaded artifacts in job json when running dbx deploy.

## Current Behavior
Artifact path is being added as s3:/bucket/prefix which results in error due to invalid URI. Should be s3://bucket/prefix

Seems to be caused by the use of Pathlib here, which collapses double slashes to single slashes.
https://github.com/databrickslabs/dbx/blob/83a91107ac3676cb047d6ec2470dbca79496f5d6/dbx/utils/common.py#L421

## Steps to Reproduce (for bugs)
Run dbx deploy with remote python files and tasks, creates incorrect s3 artifact paths

## Your Environment
ubuntu 20.4
python 3.8.10

* dbx version used: 0.3.2
* Databricks Runtime version:

**Comment by renardeinside** [comment]
Hi @castillo-luis , 
could you please mention - do you use the [strict path adjustment policy](https://dbx.readthedocs.io/en/latest/path_adjustment.html)?

**Comment by castillo-luis** [comment]
You should get the same result, an invalid S3 URI with strict_path_adjustment_policy set to true or false....

**Comment by renardeinside** [comment]
@castillo-luis , 
Just for my understanding - you have an experiment that's artifact path is registered in s3://some/prefix (not in dbfs://), and when you're working with dbx > 0.3.2 you're getting this issue, right?

**Comment by castillo-luis** [comment]
right so I have a task like this in my deployment.json

            "spark_python_task": {
              "python_file": "tasks/acquire_data.py",
              "parameters": [

and something like this for the artifact location in project.json
"artifact_location": "s3://bucket/prefix"

with dbx 0.3.0 artifacts get uploaded correctly and local paths are correctly switch out in the job json like this...
            "spark_python_task": {
              "python_file": "s3://bucket/prefix/GUID/tasks/acquire_data.py",
              "parameters": [

with >= dbx 0.3.1 due to the uploader was refactoring paths are not converted to...note the missing slash in the s3 path.
            "spark_python_task": {
              "python_file": "s3:/bucket/prefix/GUID/tasks/acquire_data.py",
              "parameters": [

which causes an INVALID URI error

**Comment by renardeinside** [comment]
@castillo-luis , 
I see - thanks a lot for raising this one and explaining the issue. I'll take care of this one.

**Comment by renardeinside** [comment]
hi @castillo-luis , 
I've fixed this issue and added a test for it. Bugfix will be released in version 0.3.3. Thank you so much for raising the issue!
