### ISSUE TITLE
[BUG] Non-strict path adjustment fails if there are empty strings

### ISSUE THREAD

**Issue by gmuciaccia-camlin** [databrickslabs/dbx#167]
## Expected Behavior

When running `dbx deploy` with non-strict path adjustment policy and with a JSON that contains an empty string (see below for an example), the job should be created without error.

## Current Behavior

The command fails with (actual paths have been omitted)

```
mlflow.exceptions.MlflowException: API request to endpoint [...] failed with error code 409 != 200. Response body: '<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=ISO-8859-1"/>
<title>Error 409 </title>
</head>
<body>
<h2>HTTP ERROR: 409</h2>
<p>Problem accessing [...]. Reason:
<pre>    File already exists, cannot overwrite: &apos;[...]</pre></p>
<hr />
</body>
</html>
'
```

## Steps to Reproduce (for bugs)

Run `dbx deploy --environment=prod --deployment-file=conf.json --no-rebuild --no-package` with the following configuration

```json
{
  "prod": {
    "jobs": [
      {
        "format": "MULTI_TASK",
        "name": "my_job",
        "tasks": [
          {
            "existing_cluster_name": "MyCluster",
            "libraries": [
              {
                "whl": "path/to/file.whl"
              }
            ],
            "max_retries": 0,
            "python_wheel_task": {
              "entry_point": "entrypoint",
              "package_name": "package_name",
              "namedParameters": {
                "param": ""
              }
            },
            "task_key": "task_one"
          }
        ]
      }
    ]
  }
}
```

Note that `"param"` has an empty string as value.

## Context

As far as I understand, the non-strict path adjustment tries to transform every string into a path. An empty string is resolved to the path of the repo, so the whole repo is uploaded (it appears in the experiment's artifacts).

### Suggested solution

Please add

```python
if candidate == '':
    return candidate
```

to the beginning of `_non_strict_path_adjustment` in `dbx/commands/deploy.py`.

## Your Environment

* dbx version used: 0.3.3
* Databricks Runtime version: 10.3

**Comment by renardeinside** [comment]
Hi @gmuciaccia-camlin , 
Thanks a lot for raising this issue, I'll take care of the fix. 
The recommended way is to use strict adjustment. The plan is to deprecate and eventually disable non-strict adjustment. Could you please mention - what could be a blocker in your use-case to prevent from using strict adjustment?

**Comment by gmuciaccia-camlin** [comment]
Hi @renardeinside , I've just become aware of the strict adjustment mode while reading the code, and I'm going to suggest to use it everywhere in our code base.

I only submitted this issue cause I thought it may be useful for people not using it, I did not know there are plans to deprecated it. I agree, strict mode is better.

Thanks for the quick answer.

**Comment by renardeinside** [comment]
Closed in the referenced PR. thank you so much @gmuciaccia-camlin for reporting this one!
