### ISSUE TITLE
[Question] Release 0.4.0 timeline

### ISSUE THREAD

**Issue by allebacco** [databrickslabs/dbx#171]
Is there any timeline for the 0.4.0 release with full support for APIs 2.1?

Could you consider an intermediate 0.3.4 release in these days with the current features? I think it will very useful with Jinja and improved named properties propagation.

**Comment by renardeinside** [comment]
Hi @allebacco , 
this sounds like a good idea to me. I'll prepare a 0.3.4 version with current features and release it this weekend.

**Comment by allebacco** [comment]
Thanks, it will be very useful for my work. I will use it on Monday!

**Comment by allebacco** [comment]
0.4.0 released, thanks.
