### ISSUE TITLE
Fix finalize_deployment_file_path method to support .j2 files

### ISSUE THREAD

**Issue by castillo-luis** [databrickslabs/dbx#174]
## Expected Behavior
.j2 files are accepted as deployment file and processed as jinja template files

The finalize_deployment_file_path method needs to be fixed like this...to accept the .j2 file extension
https://github.com/castillo-luis/dbx/blob/18612d5e058c32744d7daaac8cbaaaddeac4caab/dbx/commands/deploy.py#L234

## Current Behavior
.j2 files are not recognized as being valid

## Steps to Reproduce (for bugs)
create a .j2 deployment file and try to use

## Your Environment
Ubuntu 20.4

* dbx version used: 0.4.0

**Comment by renardeinside** [comment]
hi @castillo-luis , 
sorry for this one - I'll cover it today and make a bugfix release. For some reason tests didn't catch it.

**Comment by elenamartina** [comment]
Hi @renardeinside, @castillo-luis, I've just opened a pr to fix this: #175
