### ISSUE TITLE
Would this Job service API change be an issue? Deadline: [March 15, 2022]

### ISSUE THREAD

**Issue by jspreddy** [databrickslabs/dbx#176]
Received this email from Databricks. Is this change going to be a problem for dbx?
--------------------

Hi there,

Databricks implemented the following changes to increase the stability and scalability of the Jobs service. All workspaces will receive these changes by March 15, 2022:

- Each new job and run is assigned a longer, unique, numeric, non-sequential identifier.
- The value of the `number_in_job` field, included in the response to some Jobs API requests, is now set to the same value as `run_id` which is also a longer, unique, numeric, non-sequential identifier.

**This is a breaking change and action is required for clients that use the Jobs API** and depend on a fixed length, sequential, or monotonically increasing identifier. You must modify your logic to accept longer, non-sequential, and unordered identifiers. The identifier type of `int64` remains unchanged, and compatibility is preserved for clients that use IEEE 754 64-bit floating-point numbers (ex: JavaScript clients).

### Action Required:
By **March 12, 2022**, you must change your logic to process the job id/run id as int64/long and expect a random number. In most cases, you will only need to change the declared type in your source code to long and will not need to count on ids being sequential or sorted. This `run_id` is also `int64` and non-sequential.

In addition, users of Terraform need to upgrade to the latest plugin version as specified here.

Please see the [complete release note](https://docs.databricks.com/release-notes/product/2022/february.html#jobs-service-stability-and-scalability-improvements) for more information.

If you have any questions, please contact [help@databricks.com](mailto:help@databricks.com).

Thank you,
Databricks

**Comment by renardeinside** [comment]
Hi @jspreddy , 
Thanks a lot for reaching out. 

dbx doesn't enforce the type of the job/run id and it's not based on the previous sequential behavior. 
We're using the job_name for unique identification. I've also tested dbx in new environments, and it is working as expected.
