### ISSUE TITLE
Multiple policies

### ISSUE THREAD

**Issue by giovannipapini-agilelab** [databrickslabs/dbx#177]
## Expected Behavior

At the moment, at least from what I understand in the documentation and the code, there is no way to add multiple `policy_name` to a `new_cluster`. Did I understand correctly? Would it be possible to add such feature?

## Your Environment

* dbx version used: 0.4.1
* Databricks Runtime version: 9.1

**Comment by renardeinside** [comment]
Hi @giovannipapini-agilelab , 
Thanks a lot for reaching out. 

Databricks doesn't support applying multiple policies to clusters, therefore dbx doesn't support it as well. You'll need to reach out to your Solutions Architect requesting this feature first.
