### ISSUE TITLE
[BUG] dbx execute fails for a job with multiple tasks

### ISSUE THREAD

**Issue by iammukeshsinghqb** [databrickslabs/dbx#180]
Sample YAML File (Cookie-Cutter):

custom:
  basic-cluster-props: &basic-cluster-props
    spark_version: "9.1.x-cpu-ml-scala2.12"

  basic-static-cluster: &basic-static-cluster
    new_cluster:
      <<: *basic-cluster-props
      num_workers: 1
      node_type_id: "Standard_E8_v3"

#please note that we're using FUSE reference for config file, hence we're going to load this file using its local FS path
environments:
  default:
    strict_path_adjustment_policy: true
    jobs:
      - name: "single-task-job"
        <<:
          - *basic-static-cluster
        spark_python_task:
          python_file: "file://pipeline_run.py"
          parameters: ["--conf-file", "file:fuse://conf/test/sample.yml", "--task-name", "node1" ]
      - name: "single-task-job-2"
        <<:
          - *basic-static-cluster
        spark_python_task:
          python_file: "file://pipeline_run.py"
          parameters: ["--conf-file", "file:fuse://conf/test/sample.yml", "--task-name", "node2" ]
      - name: "multi-task-job"
        job_clusters:
          - job_cluster_key: "basic-cluster"
            <<: *basic-static-cluster
        tasks:
          - task_key: "first-task"
            job_cluster_key: "basic-cluster"
            spark_python_task:
              python_file: "file://pipeline_run.py"
              parameters: [ "--conf-file", "file:fuse://conf/test/sample.yml", "--task-name", "node1"]
          - task_key: "second-task"
            job_cluster_key: "basic-cluster"
            spark_python_task:
              python_file: "file://pipeline_run.py"
              parameters: [ "--conf-file", "file:fuse://conf/test/sample.yml", "--task-name", "node2"]
          - task_key: "third-task"
            job_cluster_key: "basic-cluster"
            depends_on:
              - task_key: "first-task"
              - task_key: "second-task"
            spark_python_task:
              python_file: "file://pipeline_run.py"
              parameters: [ "--conf-file", "file:fuse://conf/test/sample.yml", "--task-name", "node3"]

## Expected Behavior
DBX execute for a single task job runs successfully
dbx execute --cluster-id=0223-xxxxxx-qlb6md98 --job=single-task-job

[dbx][2022-03-02 21:50:38.663] No environment variables provided, using the ~/.databrickscfg
[dbx][2022-03-02 21:50:39.584] Executing job: single-task-job in environment default on cluster None (id: 0223-172952-qlb6md98)
[dbx][2022-03-02 21:50:39.584] Re-building package
[dbx][2022-03-02 21:50:40.950] Package re-build finished
[dbx][2022-03-02 21:50:40.951] Auto-discovery found deployment file conf/deployment.yml
[dbx][2022-03-02 21:50:41.055] Preparing interactive cluster to accept jobs
[dbx][2022-03-02 21:50:41.124] Cluster is ready
[dbx][2022-03-02 21:50:41.124] Preparing execution context
[dbx][2022-03-02 21:50:41.289] Existing context is active, using it
[dbx][2022-03-02 21:50:41.795] Requirements file requirements.txt is not provided, following the execution without any additional packages
[dbx][2022-03-02 21:50:41.795] Locating package file
[dbx][2022-03-02 21:50:41.799] Package file located in: dist/databricks_dbx_test-0.0.1-py3-none-any.whl
[dbx][2022-03-02 21:50:41.799] Uploading file: dist/databricks_dbx_test-0.0.1-py3-none-any.whl
[dbx][2022-03-02 21:50:42.507] Installing package
[dbx][2022-03-02 21:50:48.285] Package installation finished
[dbx][2022-03-02 21:50:48.527] Processing parameters
[dbx][2022-03-02 21:50:48.527] Uploading file: conf/test/sample.yml
[dbx][2022-03-02 21:50:49.066] Processing parameters - done
[dbx][2022-03-02 21:50:49.066] Starting entrypoint file execution
[dbx][2022-03-02 21:50:49.290] Command successfully executed

[dbx][2022-03-02 21:50:49.290] Command execution finished

## Current Behavior
Now when I try to run the multi task job,
dbx execute --cluster-id=0223-xxxxxx-qlb6md98 --job=multi-task-job. The job fails,

[dbx][2022-03-02 21:54:02.417] No environment variables provided, using the ~/.databrickscfg
[dbx][2022-03-02 21:54:03.561] Executing job: multi-task-job in environment default on cluster None (id: 0223-172952-qlb6md98)
[dbx][2022-03-02 21:54:03.561] Re-building package
[dbx][2022-03-02 21:54:05.058] Package re-build finished
[dbx][2022-03-02 21:54:05.059] Auto-discovery found deployment file conf/deployment.yml
Traceback (most recent call last):
  File "/Users/username/opt/anaconda3/envs/testdbx/bin/dbx", line 8, in <module>
    sys.exit(cli())
  File "/Users/username/opt/anaconda3/envs/testdbx/lib/python3.7/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/Users/username/opt/anaconda3/envs/testdbx/lib/python3.7/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/Users/username/opt/anaconda3/envs/testdbx/lib/python3.7/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/username/opt/anaconda3/envs/testdbx/lib/python3.7/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/username/opt/anaconda3/envs/testdbx/lib/python3.7/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/Users/username/opt/anaconda3/envs/testdbx/lib/python3.7/site-packages/dbx/commands/execute.py", line 107, in execute
    entrypoint_file = job_payload.get("spark_python_task").get("python_file")
AttributeError: 'NoneType' object has no attribute 'get' 

## Steps to Reproduce (for bugs)

Use dbx execute on any multi task job.
dbx execute --cluster-id=0223-xxxxxx-qlb6md98 --job=multi-task-job

Error,
[dbx][2022-03-02 21:54:02.417] No environment variables provided, using the ~/.databrickscfg
[dbx][2022-03-02 21:54:03.561] Executing job: multi-task-job in environment default on cluster None (id: 0223-172952-qlb6md98)
[dbx][2022-03-02 21:54:03.561] Re-building package
[dbx][2022-03-02 21:54:05.058] Package re-build finished
[dbx][2022-03-02 21:54:05.059] Auto-discovery found deployment file conf/deployment.yml
Traceback (most recent call last):
  File "/Users/username/opt/anaconda3/envs/testdbx/bin/dbx", line 8, in <module>
    sys.exit(cli())
  File "/Users/username/opt/anaconda3/envs/testdbx/lib/python3.7/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/Users/username/opt/anaconda3/envs/testdbx/lib/python3.7/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/Users/username/opt/anaconda3/envs/testdbx/lib/python3.7/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/username/opt/anaconda3/envs/testdbx/lib/python3.7/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/username/opt/anaconda3/envs/testdbx/lib/python3.7/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/Users/username/opt/anaconda3/envs/testdbx/lib/python3.7/site-packages/dbx/commands/execute.py", line 107, in execute
    entrypoint_file = job_payload.get("spark_python_task").get("python_file")
AttributeError: 'NoneType' object has no attribute 'get'
 

## Context
I was trying to execute a job with multiple tasks using dbx execute and I started seeing the above error. However, the job with single task was run successfully .

## Your Environment

* dbx version used: 0.4.1
* Databricks Runtime version: 10.1 (includes Apache Spark 3.2.0, Scala 2.12)

**Comment by aavang1** [comment]
@iammukeshsinghqb, it seems like `dbx execute` does not support Jobs API 2.1, yet. The stack trace you posted shows a failure in the code `entrypoint_file = job_payload.get("spark_python_task").get("python_file")`. That code assumes the job it is evaluating has a `spark_python_task` key, which multi-task jobs do not.

I think this is the correct version of `execute.py`, used by `dbx==0.4.1`, but the line number doesn't match:
https://github.com/databrickslabs/dbx/blob/743b579a4ac44531f764c6e522dbe5a81a7dc0e4/dbx/commands/execute.py#L104

The `dbx deploy` command calls an `adjust_job_definitions` method ([click](https://github.com/databrickslabs/dbx/blob/743b579a4ac44531f764c6e522dbe5a81a7dc0e4/dbx/commands/deploy.py#L162)), which handles single-task and multi-task jobs ([click](https://github.com/databrickslabs/dbx/blob/743b579a4ac44531f764c6e522dbe5a81a7dc0e4/dbx/utils/adjuster.py#L30-L40)).

**Comment by tonkolviktor** [comment]
This also happens if the job has only one task, but that task is not `spark_python_task`, but `python_wheel_task`.

**Comment by renardeinside** [comment]
Addressed in the linked PR, will be released as a part of 0.6.6
