### ISSUE TITLE
[BUG] dbx launch job fails with notebook parameters

### ISSUE THREAD

**Issue by hendrikfrentrup** [databrickslabs/dbx#182]
## Expected Behavior

Launching a deployed job and passing parameters via CLI (either via `--parameters` or `--parameters-raw`:
```
dbx launch --job Drop-Table --trace --parameters='table=default.temp'
```
or
```
dbx launch --job Drop-Table --trace --parameters-raw='{"table=default.temp"}'
```
or perhaps (though I would say "notebook_params" is redundant in this case
```
dbx launch --job Drop-Table --trace --parameters-raw='{"notebook_params":{"table=default.temp"}}'
```
will trigger a run of the job with the given parameters

## Current Behavior

The command above throw the following error:
```
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://<ws>.cloud.databricks.com/api/2.0/jobs/run-now
 Response from server: 
 { 'error_code': 'MALFORMED_REQUEST',
  'message': 'Could not parse request object: Expected object for field '
             'notebook_params, found STRING'}
```

## Steps to Reproduce (for bugs)
* create or deploy job (without default parameters)
* execute commands above

## Context
* I'd like to be able to launch a job via CI/CD pipeline and pass in parameters

## Your Environment
* dbx version used: 0.4.1 (Python 3.8.10) also tried dbx version 0.3.0 same issue
* Databricks Runtime version: 9.1 LTS

**Comment by renardeinside** [comment]
fixed in the referenced PR, will be released in 0.7.0 
thanks a lot for raising the issue @hendrikfrentrup !
