### ISSUE TITLE
[FEATURE] Support auto-discovery of jinja templates

### ISSUE THREAD

**Issue by mitchstockdale** [databrickslabs/dbx#183]
## Expected Behavior
Auto-discovery should occur for deployment files ending in `.j2` and matching auto-discovery path prefix: `conf/deployment.(json.j2|yaml.j2|yml.j2)`
## Current Behavior
Auto-discovery only occurs for deployment files matching: `conf/deployment.(json|yaml|yml)`
## Steps to Reproduce (for bugs)
N/A
## Context
Running `--deployment-file` for every `dbx deploy` and `dbx execute` command is tedious. SInce jinja templates are supported, why not support their auto-discovery? `dbx` is proving to be excellent software for quickly and easily managing job deployments to Databricks (well done, team 👏), so using configurable deployment files via jinja would not be uncommon.
## Your Environment
N/A
* dbx version used: 0.4.1
* Databricks Runtime version: N/A

**Comment by mitchstockdale** [comment]
This would also be a good opportunity to update parts of the [quickstart documentation](https://dbx.readthedocs.io/en/latest/quickstart.html?highlight=conf%2Fdeployment#quickstart) relating to auto-discovery of JSON files only (not true since YAML is supported).

**Comment by renardeinside** [comment]
thank you for your contribution @mitchstockdale , PR merged, will be released in 0.4.1
