### ISSUE TITLE
[Feature] `dbx destroy` command for cleaning up jobs

### ISSUE THREAD

**Issue by ilyasotkov** [databrickslabs/dbx#188]
`dbx deploy` will create/update jobs in Databricks, but I haven't found a straightforward way to clean up these jobs. Would be useful to be able to run `dbx destroy` so that all jobs defined in the YAML config file are deleted from Databricks.

**Comment by scheleaap** [comment]
I agree. `dbx` uploads artifacts and deploys jobs. It would be helpful if dbx could delete everything related to a job (the job itself, artifacts and experiments).

**Comment by kennes913** [comment]
It would be also great if this command was also run to keep the API job resources aligned with the jobs defined in the deployment.yml. For example, say I remove a job with the intention of no longer running that job in a given databricks workspace.
