### ISSUE TITLE
`dbx execute` expects file `requirements.txt` but `dbx init` template provides file `unit-requirements.txt`

### ISSUE THREAD

**Issue by justinTM** [databrickslabs/dbx#190]
## Expected Behavior
Running the `dbx execute` command from within a `dbx init`-generated python project will succeed on a shared Databricks cluster

## Current Behavior

```console
dbx init --template=python_basic
```

you will now have the following directory structure (notice file `unit-requirements.txt`):
<img width="425" alt="image" src="https://user-images.githubusercontent.com/9123665/160485561-5e89b53b-fbef-42c2-a7fd-38a8ad8e7604.png">

```console
root@a4b43a6d4a6b:/workspaces/my-databricks-project# dbx execute --cluster-name=shared-cluster --job=my-databricks-job-sample-integration-test
[dbx][2022-03-28 20:39:47.879] Cluster is ready
[dbx][2022-03-28 20:39:47.880] Preparing execution context
[dbx][2022-03-28 20:39:47.882] Existing context is not active, creating a new one
[dbx][2022-03-28 20:39:49.580] New context prepared, ready to use it
[dbx][2022-03-28 20:39:52.721] Requirements file requirements.txt is not provided, following the execution without any additional packages
```

and then you will receive python import errors due to the missing requirements file.

## Your Environment

macOS 10.15
Databricks CLI Version 0.16.4
DataBricks eXtensions aka dbx, version ~> 0.4.1
python version 3.10

**Comment by renardeinside** [comment]
Hi @justinTM , 
this is done intentionally - unit-requirements represent packages you need for local development - there is no need to install them on Databricks.  requirements.txt shall contain libraries that are not represented in the Databricks environment.

**Comment by justinTM** [comment]
@renardeinside well first of all I don't think it's fair for you to close it prematurely; if you do not specify a requirements file via a `dbx` flag, the command will error. So, either the repo here needs to rename to requirements.txt, or README needs to be updated. but as-written, the documentations fails when followed word-for-word.

**Comment by renardeinside** [comment]
Hi @justinTM , 
yes, sorry for that - I assume it was a bit of a hasty decision to close the issue without proper alignment. 

> So, either the repo here needs to rename to requirements.txt, or README needs to be updated. but as-written, the documentation fails when followed word-for-word.

I assume this phrasing is a bit misleading "[Installing project requirements](https://github.com/databrickslabs/dbx/blob/ffed70f154cb344f71b372153936ad3a78ac6a83/dbx/templates/projects/python_basic/render/%7B%7Bcookiecutter.project_name%7D%7D/README.md?plain=1#L7)", since it means "installing project requirements for local development". Would that be a good idea to rephrase the `README.md` to avoid confusion?

**Comment by justinTM** [comment]
No worries! Let me give it a test run again when i get back to machine in hour (it's been a week since I did this)

Thank you!

**Comment by renardeinside** [comment]
hi @justinTM , 
this behaviour has been changed in the recent release 0.6.5 - we're getting rid of a separate unit-requirements.txt file.
