### ISSUE TITLE
[Question] project.json

### ISSUE THREAD

**Issue by justinTM** [databrickslabs/dbx#195]
for the file `project.json`, is there design documentation to understand the thought process on this file? right now we have abstracted away the generation of this file to simply use the deployment.yml file and generate project.json automatically as part of job deployment.

but i'm wondering if there are plans to do more with project.json? will there be more keys than just environment workspace_dir and artifact_location?

**Comment by renardeinside** [comment]
Hi @justinTM , 

thanks for raising the issue. 

The `project.json` file is an auxiliary file that is designed for two specific tasks:
1. Providing mapping between environment name and profile name during **local** development. In your CI pipeline, you'll override the local profile setting by using `DATABRICKS_HOST` and `DATABRICKS_TOKEN` env variables, so this functionality is only used for the local part of the development workflow.
2. Providing the deployment coordinates, specifically `workspace_dir` and `artifact_location` - these are locations wherein the Databricks workspace an underlying mlflow experiment is defined, and where the artifacts of this experiment are physically saved. 

> but i'm wondering if there are plans to do more with project.json? will there be more keys than just environment workspace_dir and artifact_location?

At the moment there are no additional plans to store any additional information in this file. However, I don't get your point about "generating the project.json" on the fly. As per the design, it's a configuration file that is designed to be stored in the git repository to provide mappings between env names and the physical location of the artifacts. 

Let me know if you'll have any other questions.

**Comment by copdips** [comment]
@justinTM 
If I understand well your needs, I also generate `project.json` dynamically during the CICD time, you need to write a script to generate it, I cannot past you the real code, but the idea is like as below, each parameter of `dbx configure` could be calculated dynamically, you can also run the command in a loop, then you will have a big single `project.json` file containing many profiles inside:

```bash
        dbx configure \
            --environment "$dbx_profile" \
            --profile "$dbx_profile" \
            --workspace-dir "$workding_dir" \
            --artifact-location "$artifact_location"
```

**Comment by renardeinside** [comment]
as discussed above, there is an option to use `dbx configure` on the fly in your CI/CD setup. 
We currently don't plan making `project.json` dynamic as no real need for this proposal is visible at the moment. 
Please re-open the issue if there is still a need in it.
