### ISSUE TITLE
[FEATURE] Provide parameter overriding options for 'execute' command, similar to 'launch'

### ISSUE THREAD

**Issue by matthiaspfenninger** [databrickslabs/dbx#196]
## Expected Behavior
It would be nice if the `execute` command is acting equivalently to `launch` in terms of dynamic parameter overriding: there should be options to set parameters via `--parameters` and `--parameters-raw` for the `execute` command.

## Current Behavior
The `launch` command supports overriding of job parameters via  `--parameters` and `--parameters-raw`. The `execute` command does not provide a similar functionality, parameters have to be added to the static file that is provided under `--deployment-file` instead.

## Context
In some scenarios the preferred dbx workflow might be to directly use `execute` over separately using `deploy` and `launch`. It would be nice if both of these workflows give users the same options to control job parameters.

## Environment
* dbx version used: 0.4.1
* Databricks Runtime version: 10.4 LTS

**Comment by matthiaspfenninger** [comment]
Looks like this didn't make it into version 0.5.0 as planned via milestone – any idea if it makes it into a patch version soon @renardeinside? 

Thanks :)

**Comment by renardeinside** [comment]
hi @matthiaspfenninger , 
we're planning to switch the release policy a little bit, do a bigger refactoring and make this change part of 1.0.0 
Please stay tuned, you'll soon see some big updates in dbx.

**Comment by renardeinside** [comment]
closed in the referenced PR, thanks a lot for opening the issue @matthiaspfenninger !
