### ISSUE TITLE
[Feature] Allow jinja templating also for project config (similar to deployment config)

### ISSUE THREAD

**Issue by matthiaspfenninger** [databrickslabs/dbx#198]
## Expected Behavior
As of per version 0.4.1, dbx supports Jinja templating for deployment configs (see ["Jinja2 Support" in docs](https://dbx.readthedocs.io/en/latest/jinja2_support.html)). It would be nice if this was also supported for the global project config file.

## Proposed Change
The `InfoFile` class in [common.py](https://github.com/databrickslabs/dbx/blob/main/dbx/utils/common.py) could be extended to be able to render Jinja templates if a file with `j2` extension is detected.

## Current Behavior
Jinja templating is only supported in the deployment config, implemented in the `Jinja2DeploymentConfig` class in [common.py](https://github.com/databrickslabs/dbx/blob/main/dbx/utils/common.py).

## Context
There can be cases where environment names are not known upfront and can therefore not be hardcoded into the project config file – examples:
- automatically creating environments with system generated names for testing purposes
- environment name is provided as user input on a higher level than dbx

In these cases it would be nice to parametrize the project config, which could be easily achieved by expanding the Jinja templating to that file.

## Your Environment
* dbx version used: 0.4.1
* Databricks Runtime version: 10.4 LTS

**Comment by renardeinside** [comment]
hi @matthiaspfenninger , 
thanks a lot for raising the issue. 
I'm struggling to understand the value and the use-case for this. You can generate as many environments as you want with:

```
dbx configure
```
Does it cover your use-case? I'm asking because I was expecting project.json file to be pretty static, like `package.json` in `npm` modules.

**Comment by matthiaspfenninger** [comment]
Hi @renardeinside 

Thanks a lot for the response!  

Our use case is that we use dbx as part of testing pipelines, where each test run receives an automatically generated identifier. This identifier should also be used for the dbx configuration, to make sure to isolate dbx artifacts between different runs.

I agree that we can achieve this by running the _configure_ command as part of our pipelines, i.e. something like:
```bash
dbx configure --workspace-dir /Shared/dbx/testruns/<test-id> --artifact-location dbfs:/dbx/testruns/<test-id>
```

My idea was that it would be cleaner from IaC perspective to not have to hide this config inside a bash command of a pipeline. But to have it clearly visible as a project template file that lives in the repository.

Let me know what you think!

**Comment by renardeinside** [comment]
I think there is a misconception on how dbx works. 

dbx will keep the artifacts separate between pipelines by default - it's achiveable via `--branch-name` + `--tags` functionality. 

To sum up - you don't need to create environments in `.dbx/project.json` dynamically - it's an anti pattern. This file is not intended to change often (as you probably don't create a new Databricks workspace for each CI pipeline).
