### ISSUE TITLE
[Feature] Pipfile support

### ISSUE THREAD

**Issue by jmatias** [databrickslabs/dbx#200]
## Expected Behavior

Similar behavior to what `dbx` supports today for `requirements.txt`:

Given that a `Pipfile` exists in the repository,
when we execute `dbx execute  --job ... --cluster ...`
then `dbx` will install the packages found in the `[packages]` section of the Pipfile before running the job
but will **NOT** install the packages  found in the `[dev-packages]` section.

Given that a `Pipfile` exists in the repository,
when we execute `dbx deploy ...`
then `dbx` will add the packages found in the `[packages]` section of the Pipfile to the deployment config
but will **NOT** add the packages  found in the `[dev-packages]` section.

## Current Behavior

Today, we can pass requirements files to dbx, but not Pipfiles. 
[example: dbx execute](https://dbx.readthedocs.io/en/latest/cli.html#cmdoption-dbx-execute-requirements-file)
[example: dbx deploy](https://dbx.readthedocs.io/en/latest/cli.html#cmdoption-dbx-deploy-requirements-file)

#### Quick and dirty solution using the https://github.com/pypa/pipfile package:
```python
from pipfile import Pipfile
parsed = Pipfile.load(filename="./Pipfile")

def _generate_pkg_str(k, v):
    # k contains pkg (e.g. jsonpath-ng)
    # v contains semver string (e.g. ==1.5.*)
    if v == "*":
        return k  # just add the package name
    return f"{k}{v}"  # add the qualified package (e.g. jsonpath-ng==1.5.*)
requirements_content = [_generate_pkg_str(k, v) for (k, v) in parsed.data['default'].items()]
```

- It seems like I can implement the change here:

https://github.com/databrickslabs/dbx/blob/ffed70f154cb344f71b372153936ad3a78ac6a83/dbx/utils/dependency_manager.py#L14

- For the `execute` command, we'll have to add it here:

https://github.com/databrickslabs/dbx/blob/ffed70f154cb344f71b372153936ad3a78ac6a83/dbx/commands/execute.py#L126-L134

**Comment by matthiaspfenninger** [comment]
Great idea, missing the exact same feature!

**Comment by renardeinside** [comment]
hi @jmatias , 
there is no need in using requirements.txt for this purpose. you can use standard Python packaging (add your dependencies to the package wheel directly, without using a separate file).
