### ISSUE TITLE
bdbx init. Error : no such command “init”.

### ISSUE THREAD

**Issue by aj1052737** [databrickslabs/dbx#211]
## Expected Behavior
Creates a dbx templated project with CI/CD support as explained [here](https://docs.databricks.com/dev-tools/dbx.html#create-a-dbx-templated-project-with-cicd-support)

## Current Behavior
Error : no such command "init"

full error : 
```
FutureWarning: MLflow support for Python 3.6 is deprecated and will be dropped in a
n upcoming release. At that point, existing Python 3.6 workflows that use MLflow will continue to work without modification, but Python 3.6 users will no l
onger get access to the latest MLflow features and bugfixes. We recommend that you upgrade to Python 3.7 or newer.
  import mlflow
Usage: dbx [OPTIONS] COMMAND [ARGS]...
Try 'dbx -h' for help.

Error: No such command 'init'.
```

## Steps to Reproduce (for bugs)
[pip install dbx
dbx init](url)

## Context
starting an MVP that'll run on databricks and scheduled through bdx

## Your Environment
python 3.6

* dbx version used: 0.1.2

* Databricks Runtime version: no databricks for now, i'm running dbx init locally

**Comment by renardeinside** [comment]
hi @aj1052737 , 
it seems like you're using a very old version of dbx - please upgrade it via:
```
pip install -U dbx
```
