### ISSUE TITLE
%run not working as intended, using IPython line magic instead of databricks

### ISSUE THREAD

**Issue by samcomber-mns** [databrickslabs/dbx#215]
## Expected Behavior
I'm trying to run `dbx execute --cluster-id=123--job=job_test --no-rebuild --no-package` but am encountering this error within a notebook for job `job_test`

I'm expecting `%run /path/to/notebook` command to work from within notebook 

![image](https://user-images.githubusercontent.com/102611296/165696098-b7e61b4f-8a34-4d75-b8de-78b9153380b9.png)

## Current Behavior
I believe IPython run_line_magic (`get_ipython().run_line_magic('run', '/path/to/notebook')`) is being ran instead of databricks `%run`  (see this post as to why this doesn't work: https://stackoverflow.com/questions/66878378/run-magic-using-get-ipython-run-line-magic-in-databricks).. which is raising the below exception

`Exception: File /path/to/notebook not found.`

* dbx version used: 0.4.1
* Databricks Runtime version: 10.4

**Comment by renardeinside** [comment]
hi @samcomber-mns , 

dbx execute is currently not oriented to use with notebooks - if you want to run a notebook you simply run it from the UI, you don't run it as a dbx execute command. Could you please explain to me the use-case of running dbx execute with a notebook?

**Comment by samcomber-mns** [comment]
Hi @renardeinside, thanks for the response.

I was looking for a way to completely localise my development process. Right now we have CI/CD set up where I push code and deploy notebooks (that execute e2e ML pipelines) to test, this deployment process takes around ~2 minutes each time, meaning I hop over to the UI, wait for the deployment and trigger to test applied changes.

I was curious to see whether dbx could be used to trigger these notebooks from terminal as opposed to having to rely on our CI/CD deployment for more incremental committed changes (i.e. silly bugs etc). The use case would be purely for when project is in development stage, where I'm rapidly prototyping with new features and can quickly call dbx execute to test developed change.

**Comment by renardeinside** [comment]
Hi @samcomber-mns , 
this functionality is going to be implemented but in a slightly different way.  I'll keep this issue open and match it to the correct PR as soon as I'll open it

**Comment by renardeinside** [comment]
hi @samcomber-mns , 

please take a look at the functionality called `dbx sync` - it should cover your use-case (local development, direct sync to the Databricks Repo and then use it directly from a notebook). 
Would that cover your use-case?

**Comment by renardeinside** [comment]
`dbx sync` cover cases for jointed development in Notebooks and IDE.

**Comment by samcomber-mns** [comment]
Yes, we're using this currently, works great! Thanks

dbx sync repo -d <repo name> &
