### ISSUE TITLE
[Docs] How to add Spark configs to a deployment config

### ISSUE THREAD

**Issue by PaulCornellDB** [databrickslabs/dbx#220]
If you dig around the Jobs API reference docs a bit, you can eventually find out what to specify in the deployment YAML to set Spark configs. It seems though that you can only do this for new jobs clusters, not for existing all-purpose clusters. In any event, it might be good to explicitly state this in the dbx docs, along with an example, to make it easier for users.

**Comment by renardeinside** [comment]
Described in [this](https://dbx.readthedocs.io/en/latest/examples/python_multitask_deployment_example.html) section
