### ISSUE TITLE
[Feature] How to handle setup.py/extras_require

### ISSUE THREAD

**Issue by tonkolviktor** [databrickslabs/dbx#222]
## Expected Behavior

I'd like to be able to specify optional dependency during deployment:
https://setuptools.pypa.io/en/latest/userguide/dependency_management.html#optional-dependencies

## Current Behavior

Under libraries the current project's wheel is added, but no option to specify the optional dependencies.
If I specify manually it is not replaced:
```
    "libraries": [
        {
            "whl": "dist/my-package-py3-none-any.whl[my-optional-deps]"
        },
        {
            "whl": "dbfs:/dbx/my-package/0ebc/artifacts/dist/my-package-py3-none-any.whl"
        }
    ],
```
It would be nice if one could keep the build and specify the optional dependency.

* dbx version used: latest
* Databricks Runtime version: latest as of 2022.05.04

**Comment by renardeinside** [comment]
hi @tonkolviktor , 
you can use standard Python packaging approach and avoid using `requirements.txt` (this functionality is deprecated). 
Please take a look at the latest template for examples.
