### ISSUE TITLE
running pytest with cloudFiles format

### ISSUE THREAD

**Issue by jasonvondie** [databrickslabs/dbx#228]
## Expected Behavior
I expect that when I run `pytest`, it will read in my data using `cloudFiles.format`
## Current Behavior
I receive the following error
`: java.lang.ClassNotFoundException: Failed to find data source: cloudFiles.`
## Context
This seems to be related to jar files that may be missing. I currently have spark-xml from com.databricks and spark-csv JAR's in my folder. 
## Your Environment
mac
* dbx version used: 0.4.1
* Databricks Runtime version: 9.1.0

**Comment by renardeinside** [comment]
Hi @jasonvondie , 

Unfortunately, it's impossible to use cloudFiles outside of the Databricks Runtime (e.g. in local unit tests). 
I would recommend mocking out this section with simple Apache Spark file streaming for unit testing.

**Comment by jasonvondie** [comment]
> Hi @jasonvondie ,
> 
> Unfortunately, it's impossible to use cloudFiles outside of the Databricks Runtime (e.g. in local unit tests). I would recommend mocking out this section with simple Apache Spark file streaming for unit testing.

Awesome - Thank you for the reply!
