### ISSUE TITLE
[Feature] Add sync command

### ISSUE THREAD

**Issue by matthayes** [databrickslabs/dbx#232]
It would be useful if dbx has commands for syncing local file changes to Databricks repos or DBFS in order to enable local development in IDEs.

**Comment by renardeinside** [comment]
hi @matthayes , 
do I expect correctly that you're going to add a new PR with docs?

**Comment by matthayes** [comment]
yes I'll do that

**Comment by matthayes** [comment]
PR for docs here: https://github.com/databrickslabs/dbx/pull/256
