### ISSUE TITLE
pep8 and black disagree on whitespace before ':'

### ISSUE THREAD

**Issue by matthayes** [databrickslabs/dbx#234]
## Expected Behavior

prospector and black should apply the same rules for whitespace before ':'

## Current Behavior

prospector and black disagree on which is correct

## Steps to Reproduce (for bugs)

With the following code, running prospector yields `pep8: E203 / whitespace before ':'` but black has no problem with it.

```
path[len(ancestor) + 1 :]
```

With the following code, black check produces an error, but prospector does not.

```
path[len(ancestor) + 1:]
```

## Context

N/A

## Your Environment

* dbx version used: `main` branch
* Databricks Runtime version: N/A

**Comment by renardeinside** [comment]
fixed in #237
