### ISSUE TITLE
`make lint` fails with "No module named rstcheck.__main__"

### ISSUE THREAD

**Issue by matthayes** [databrickslabs/dbx#235]
## Expected Behavior

Running `make lint` should pass on recent commit from `main` branch.

## Current Behavior

Running `make lint` fails with:

```
No module named rstcheck.__main__
```

## Steps to Reproduce (for bugs)

`make lint`

## Your Environment

* dbx version used: `main` branch
* Databricks Runtime version: N/A

**Comment by renardeinside** [comment]
closed in #237
