### ISSUE TITLE
Dependencies conflict after updating dbx cli

### ISSUE THREAD

**Issue by Stefanos-Arampatzis** [databrickslabs/dbx#246]
## Expected Behavior
run successfully `dbx execute` after updating to the latest version`0.4.1`
## Current Behavior
Raises an error `ModuleNotFoundError: No module named 'azure.core.rest'` immediately.
## Steps to Reproduce (for bugs)
Update dbx from `0.3.0`  to `0.4.1` and run `dbx execute [OPTIONS]`
## Context
Looks like the error is raised due to some dependencies conflict. Seems that `azure-core` is not updated to the latest version `1.24.0` and I can see in my console that 1.15.0 is installed instead.
Uninstall and re-install `azure-core`
## Your Environment

* dbx version used: 0.4.1
* Databricks Runtime version: 10.4 LTS

**Comment by renardeinside** [comment]
hi @Stefanos-Arampatzis ,

I cannot reproduce this issue in 0.5.0 - please re-open the ticket if needed.
