### ISSUE TITLE
[Feature] Add job run log to dbx launch output

### ISSUE THREAD

**Issue by nididpi** [databrickslabs/dbx#253]
## Expected Behavior
By adding the new option `--job-run-log-level`, `dbx launch` will output the job run log instead of have to go to databrick UI for logs.
## Current Behavior
Currently, when job completes, it will only ask to go to databrick UI to check logs
## Your Environment

* dbx version used: 0.4.1

**Comment by nididpi** [comment]
#254

**Comment by renardeinside** [comment]
linked PR is merged, will be delivered as a part of 0.6.6 
Thanks a lot for opening and contributing to the PR @nididpi !

**Comment by RaccoonForever** [comment]
Thanks a lot both (or more) of you!
