### ISSUE TITLE
Question: Is it possible to include an additional python wheel from the DBFS when running dbx execute?

### ISSUE THREAD

**Issue by richard-vanderveen** [databrickslabs/dbx#260]
This will be more of a question than an issue, but it is something our team has been struggling to figure out.
We are in the process of replacing DatabricksConnect with `dbx`, however we run into some issues with our solutions.

For the most part, `dbx` works perfectly for us. We can use it to connect to a remote cluster, push a wheel (build using Poetry) and execute a piece of code. 

Where we run into trouble is when we want to use a private python solution stored on Github, I will refer to this solution as package X. We tried several approaches:
1. Including package X in the Poetry pyproject.toml results into authorization issues when installing the wheel on the remote cluster through `dbx`, as package X is inside a Github organization
2. We have pipelines in place to automatically write new wheel versions of package X to the DBFS of the target cluster, however we cannot seem to find a way to instruct the `dbx execute` command to also install package X prior to installing the job's current wheel.
3. We tried finding a way to authorize the cluster (or poetry for that matter) to be able to fetch and install package X as a regular python library, but without luck.

Is there a way to include a python wheel file that is already present on the DBFS of the target remote cluster in the job definition for `dbx` and install it to make it available? To be clear, this is another wheel than the one a developer would be working on locally, but the local code depends on X.

* dbx version used: 0.4.1
* Databricks Runtime version: 9.1

**Comment by renardeinside** [comment]
Great you've found it @richard-vanderveen . You have a good point that we need to work better in terms of dependency management, but it will take some time to implement.

**Comment by richard-vanderveen** [comment]
@yewsiang Apologies, I was on holiday. For what is it still worth:

Because I use a requirements.txt file (which is the default dbx looks for) it works out of the box. Probably there is something off with how you provide the name of the alternative file (or this is something off in dbx itself).

**Comment by renardeinside** [comment]
hi @yewsiang , 
dbx automatically adds the core package to your library dependencies list, there is no need to manually add it in the requirements file. 

Also note that usage of `requirements.txt` is deprecated, please take a look at the newest version of template for guidance on how to work with dependencies.
