### ISSUE TITLE
dbx execute streaming query on interactive cluster returns 500

### ISSUE THREAD

**Issue by harry19023** [databrickslabs/dbx#261]
## Expected Behavior
Running a streaming query with `dbx execute` will give feedback on the status of the job

## Current Behavior
Query starts and then return a 500 error

{ 'error': 'RuntimeException: Unknown ExecutionStatus '
           'RunningInBackground(ExecutionId(fa230ea8-7880-4b17-ba35-ae2b32889a11),Map(8724530366035194313-a31bd105-b339-4ccc-ae10-fd66fdeb09b4 '
           '-> '
           'List(StreamProgress(ExecutionContextId(3882082318993597891),RunnableCommandId(8724530366035194313),ExecutionId(fa230ea8-7880-4b17-ba35-ae2b32889a11),null,null,Map(a31bd105-b339-4ccc-ae10-fd66fdeb09b4 '
           '-> {"message":"Processing new '
           'data","isDataAvailable":true,"isTriggerActive":true}),List())), '
           'RESULTS -> '
           'List(Progress(ExecutionContextId(3882082318993597891),RunnableCommandId(8724530366035194313),ExecutionId(fa230ea8-7880-4b17-ba35-ae2b32889a11),List(StageProgress(5,13,start '
           'at NativeMethodAccessorImpl.java:0,0,0,0,3), '
           'StageProgress(5,14,start at '
           'NativeMethodAccessorImpl.java:0,0,0,0,1), StageProgress(5,15,start '
           'at '
           'NativeMethodAccessorImpl.java:0,0,3,0,3)),List(),None,List(),List()))),false)'}

## Steps to Reproduce (for bugs)
run a streaming job using `dbx execute`

```
class StreamingJob(Job):

    def launch(self):
        self.logger.info("Launching streaming job")

        self.spark.readStream \
            .format("delta") \
            .option("ignoreChanges", "true") \
            .table('test_db.source') \
            .writeStream \
            .format('delta') \
            .trigger(once=True) \
            .option("checkpointLocation", "/tmp/delta/events/_checkpoints/") \
            .toTable('test_db.target')

if __name__ == "__main__":
    job = StreamingJob()
    job.launch()
```

## Your Environment

* dbx version used: 0.4.1
* Databricks Runtime version:  10.5

**Comment by teaVeloper** [comment]
Hi, I also encountered this behaviour. I figured, that everything was done properly on the cluster and it is just an issue with the hook of dbx showing the results, but the `StreamingQuery` runs asynchronously.

Try:
```python
class StreamingJob(Job):

    def launch(self):
        self.logger.info("Launching streaming job")

        streaming_query = self.spark.readStream \ # assign the StreamingQuery to an variable
            .format("delta") \
            .option("ignoreChanges", "true") \
            .table('test_db.source') \
            .writeStream \
            .format('delta') \
            .trigger(once=True) \
            .option("checkpointLocation", "/tmp/delta/events/_checkpoints/") \
            .toTable('test_db.target')
        streaming_query.awaitTermination() # await Termination of StreamingQuery

if __name__ == "__main__":
    job = StreamingJob()
    job.launch()
```
My approach is usually to not await Termination, but `return` the streamingQuery, so I can awaitTermination wherever I run `launch` and could possibly run multiple 'streams' asynchronously. But this approach worked for me at least.

**Comment by renardeinside** [comment]
hi @teaVeloper , 
yes, I approve - your approach is absolutely correct. Unfortunately running unawaited streaming queries is not supported in the ExecutionContext API, therefore it's not supported in dbx

**Comment by harry19023** [comment]
Amazing, thanks you @teaVeloper. This works great.
