### ISSUE TITLE
Loosen mlflow and protobuf requirements

### ISSUE THREAD

**Issue by matthayes** [databrickslabs/dbx#275]
## Expected Behavior

`pip install dbx` should ideally not conflict with other dependencies listed in a requirements file.

## Current Behavior

Due to these requirements below in the `setup.py`, it can be challenging to pip install dbx because other requirements may depend on a different version of `protobuf`.

```
    "mlflow==1.26.1",
    "protobuf==4.21.1",
```

## Steps to Reproduce (for bugs)

Add `dbx==0.5.0` to a requirements file that also has another dependency such as `google-api-python-client` that depends on an earlier `3.x` version of `protobuf`.

## Context

I originally made the following change in e6361bf922813b94ae47bc6aee308a05c80d6da4 to address the incompatibility of protobuf `4.21.0rc2` with mlflow.  Fixing the version prevented it from picking up the newer RC that didn't work.

```
-    "mlflow>=1.23.0",
+    "mlflow==1.26.0",
+    "protobuf==3.20.1",
```

Later `dependabot` bumped the `mlflow` and `protobuf` versions further.

Since then, `4.21.0` was yanked (maybe due to the issues observed), and a new `4.21.1` was released.  When I remove the `protobuf` dependency and change the mlflow dependency to `"mlflow>=1.26.1` the tests all pass.  This is basically how `setup.py` used to be before.

## Your Environment

* dbx version used:
* Databricks Runtime version:

**Comment by renardeinside** [comment]
fixed in relevant commit
