### ISSUE TITLE
Jinja2 template not found (without absolute path) since 0.5.0

### ISSUE THREAD

**Issue by Teun-Roefs** [databrickslabs/dbx#278]
## Expected Behavior
I would expect `dbx deploy --deployment-file ../path/to/deployment/file.yml.j2` to successfully deploy the jobs inside the config file.

## Current Behavior

I would expect `dbx deploy --deployment-file ../path/to/deployment/file.yml.j2` to successfully deploy the jobs inside the config file, however, I get an error stating the file cannot be found. See screenshot below.

![Screenshot 2022-06-07 at 11 58 37](https://user-images.githubusercontent.com/98397489/172352961-49b9a992-ee37-4c3e-918a-37a29392a8e6.png)

## Steps to Reproduce (for bugs)

1. Install DBX version 0.5.0
2. Navigate to a sub-folder to ensure you can use `../` inside your `--deployment-file` path.
3. Execute `dbx deploy --deployment-file path/to/deployment/file.yml.j2`
4. Get error message that file cannot be found

1. Install DBX version 0.4.1
2. Navigate to a sub-folder to ensure you can use `../` inside your `--deployment-file` path.
3. Execute `dbx deploy --deployment-file path/to/deployment/file.yml.j2`
4. Jobs deployed successfully

![Screenshot 2022-06-07 at 12 02 16](https://user-images.githubusercontent.com/98397489/172353677-5dba12a9-7ba5-457c-acb5-9e1fd1356045.png)

## Context
We currently do not have `dbx` pinned to a specific version, hence our pipelines started failing when the upgrade was done through our Azure DevOps agents. We reverted `dbx` back to `0.4.1` and everything is working fine again.

## Your Environment

* dbx version used: 0.5.0
* Databricks Runtime version: n/a

**Comment by renardeinside** [comment]
hi @Teun-Roefs , 
I'm on this issue, run into it while fixing the tests. I'll analyse it and provide resolution.

**Comment by renardeinside** [comment]
covered in #295 , will be released in 0.6.0
Thank you @Teun-Roefs for raising the issue!
