### ISSUE TITLE
Breaking change with GitHub Actions workflow moving from 0.5.0 to 0.6.0

### ISSUE THREAD

**Issue by niall-turbitt** [databrickslabs/dbx#300]
I’ve noticed some breaking changes in my github actions workflows going from dbx==0.5.0 to 0.6.0. In my unit-requirements.txt file I previously had dbx without specifying the version, and so was downloading the most recent dbx version when running my github actions workflow. After the update from 0.5.0 to 0.6.0 it seems that my pipeline is not picking up the host and token from github actions secrets (screenshot 1)
![Screenshot 2022-06-23 at 10 33 04](https://user-images.githubusercontent.com/52167569/175276983-a141ca9b-c6df-4b02-8684-7e536ad623fb.png)

Whenever I revert to dbx==0.5.0 in unit-requirments.txt the actions workflow runs as expected (screenshot 2). 
![Screenshot 2022-06-23 at 10 35 50](https://user-images.githubusercontent.com/52167569/175277068-818ea248-774b-4bab-abe8-80a6e755914f.png)

Note that using dbx==0.6.0 and deploying/launching the same job from local machine works as expected.

## Steps to Reproduce (for bugs)
- Set GitHub actions secrets for Databricks Host and Databricks token
- Run Github actions workflow which uses this host and token

## Your Environment
* dbx version used: 0.5.0 / 0.6.1
* Databricks Runtime version: DBR 11.0 ML

**Comment by renardeinside** [comment]
hi @copdips , 
unfortunately databrickslabs projects are not allowed to be 1.X since it means official support (and we don't provide official support for dbx at the moment). Therefore we recommend binding the version to the subversion for stability, e.g.:
```
dbx>=0.5,<0.6
```

**Comment by Stefanos-Arampatzis** [comment]
@niall-turbitt  Downgrading to `0.5` worked for me

**Comment by renardeinside** [comment]
hi @Stefanos-Arampatzis ,

yes, it's already in testing, shall be out today in 2 hours

**Comment by renardeinside** [comment]
fixed and released, thanks a lot for quick detection!
