### ISSUE TITLE
Error 400 when updating job definitions with dbx 0.6.2

### ISSUE THREAD

**Issue by Stefanos-Arampatzis** [databrickslabs/dbx#305]
## Expected Behavior
Deploy jobs in any env
## Current Behavior
Raises a bad request 400 error
## Steps to Reproduce (for bugs)
Deploy a job `dbx deploy -e dev --jobs=<JOB_NAME>`
## Context
![image](https://user-images.githubusercontent.com/83594163/175917659-4c20dd48-d2a8-49bb-8061-d3d7ec341dda.png)

This error is not raised when deploying with `--files-only` option.
**TEMP Solution**: Downgrading `dbx` to `0.5` resolved the deployment issue

## Your Environment
OS:Mac
python 3.8.x
* dbx version used: 0.6.2
* Databricks Runtime version: 10.4 LTS

**Comment by renardeinside** [comment]
hi @Stefanos-Arampatzis , 
it means you need to use the proper path in your configurations (file://some/file/name). Please follow [this](https://dbx.readthedocs.io/en/latest/path_adjustment.html) documentation for details.
