### ISSUE TITLE
cannot run `python -m dbx configure`:  No module named dbx.__main__

### ISSUE THREAD

**Issue by copdips** [databrickslabs/dbx#306]
## Expected Behavior
no error when running `python -m dbx configure`

## Current Behavior

(venv)> python -m dbx launch
/{myRepoPath}/venv/bin/python: No module named dbx.__main__; 'dbx' is a package and cannot be directly executed

## Steps to Reproduce (for bugs)
run `python -m dbx launch` or `python -m dbx configure`

**Comment by copdips** [comment]
I'm using dbx in azure pipelines, and actually azure have a python module bug since yesterday that we must add `python -m` to run any commands

**Comment by renardeinside** [comment]
hi @copdips , 
do I understand correctly that it was working previously, now it has a bug and no dbx commands can be executed at all without `python -m` in all Azure Pipelines?

**Comment by renardeinside** [comment]
fixed and released in 0.6.3, please install the latest version.
Thanks for reporting this @copdips !

**Comment by copdips** [comment]
@renardeinside

thank you so much for this rapid fix, could you please also add a patch version for dbx v0.5 ?
we've currently some issue with dbx v0.6.

**Comment by renardeinside** [comment]
hi @copdips , 
unfortunately our release process doesn't support changing already released version. 
If there is an issue with v0.5 > v0.6 which is not reflected in the CHANGELOG as a feature, please feel free to create another ticket specifically for that issue.
