### ISSUE TITLE
what is `.dbx/lock.json`

### ISSUE THREAD

**Issue by copdips** [databrickslabs/dbx#317]
Hello,

Multiple docs say that do not commit file `.dbx/lock.json`:
https://dbx.readthedocs.io/en/latest/templates/python_basic.html?highlight=lock.json#project-file-structure

```bash.
├── .dbx
│   ├── lock.json  # please note that this file shall be ignored and not added to your git repository.
│   └── project.json
├── .gitignore
```

Its content is similar to : 

```json
{
    "context_id": "123456789"
}
```

Could you please explain what does it work for, if we commit it, what will be the consequence ?

**Comment by renardeinside** [comment]
hi @copdips , 
this file used as a local state to store information about the execution context id. 
it's only used when `dbx execute` is used.

there is nothing critical in storing this information in your git repository, it's just a bad practice in common to store temporary files in git repository, therefore this recommendation is there.
