### ISSUE TITLE
How `.syncinclude` and `.gitignore` work together?

### ISSUE THREAD

**Issue by avaneeshqb** [databrickslabs/dbx#323]
## Context
Current Sync repo behaviour automatically ignores all files listed under `.gitignore`. Even adding folders to `.syncinclude` doesn't add them. This doesn't help any developer who wants to add a few files(eg: local/user-specific  conf) for convenience and doesn't want them tracked in git.  
Would it makes sense to include folders listed under `.syncinclude` but also under `.gitignore`? 

For additional context, we're planning on using `dbx sync` to interact with datasets/code in databricks notebooks while being able to use IDE to edit code using IDE. We're using kedro projects which includes a `conf/local` folder for developement-specific configuration. 

## Expected Behavior
Include folders added under `.syncinclude` even when excluded by `.gitignore`

## Current Behavior
Excludes folders added under `.syncinclude` when excluded by `.gitignore`

## Steps to Reproduce (for bugs)
1. Sync a repo using `dbx sync repo -d <dest_repo>` which has a folder listed under .gitignore [eg: `conf/local/*.yml`]
2. Add the folder to `.syncinclude` as well.
3. Add a file to the folder mentioned in both.

## Your Environment

* dbx version used: 6.4
* Databricks Runtime version: NA

**Comment by renardeinside** [comment]
@matthayes could you please take a look into it?

**Comment by matthayes** [comment]
> Current Sync repo behaviour automatically ignores all files listed under .gitignore. Even adding folders to .syncinclude doesn't add them. 

Right, that is the current behavior.  I intended `.syncinclude` to be a convenient way to check in set of patterns/directories to automatically sync that are standard for users of the repo, so you don't have to type a list of `-i` options each time.  It seemed that probably most of the time people don't want to sync files/directories matched by `.gitignore`, so I chose to not sync those by default.  Ignore rules currently take precedence over include rules:

https://github.com/databrickslabs/dbx/blob/main/dbx/sync/path_matcher.py#L118

> Would it makes sense to include folders listed under .syncinclude but also under .gitignore?

As a default behavior, I'm not sure.  I think there are situations where having ignore rules take precedence makes sense.  For example, suppose you are syncing a folder `/foo`, which has within it a `build` directory that is produced via building.  You probably don't want `build` synced, and `build` is typically included in `.gitignore`.  So the current behavior helps here.  

But there are situations, as you highlight, where you do want go sync something covered by the `.gitignore`.  There isn't a way to override this behavior at the moment.  I'll have to think more about the best way to handle this.  The simplest workaround may be to add an option to not use `.gitignore` rules, so you can be very explicit in `.syncinclude` about what to sync.

**Comment by renardeinside** [comment]
hi @avaneeshqb , 
was the question resolved with the answer above?

**Comment by avaneeshqb** [comment]
@renardeinside. While it's a valid workaround, removing .gitignore wasn't an option for us. We're going with editing files in databricks environment. 
@matthayes On possible design changes, maybe a new arg `--always-sync` might work. This will not also cause any issues with backward compatibility too. I could try to make this change if it makes sense.

**Comment by matthayes** [comment]
How about these options below?  I can work on a PR.

* `--use-gitignore` / `--no-use-gitignore` controls whether the `.gitignore` is used for syncing purposes
* `-fi` ( `--force-include` ) forces a directory to be included, regardless of `.gitignore`

**Comment by avaneeshqb** [comment]
Those would be great, just `--force-include` would be immediately beneficial for us. 

Happy to work on it over the weekend too if it's ok. Looking at the code later, already had an idea what might need modification.

**Comment by matthayes** [comment]
Okay great.  I should have a PR ready today.

**Comment by matthayes** [comment]
Hi @avaneeshqb I have prepared a PR in #351 that implements what I proposed above.

@renardeinside or @fjakobs, can one of you review?

**Comment by matthayes** [comment]
Hi @avaneeshqb , this has been merged.  If you're up for it please try it and let me know if you experience any issues.

**Comment by renardeinside** [comment]
closed, will be released as a part of 0.6.9
thanks a lot to @avaneeshqb for reporting this one and to @matthayes for implementation!
