### ISSUE TITLE
folder name `jobs` or `tasks`

### ISSUE THREAD

**Issue by copdips** [databrickslabs/dbx#327]
## Expected Behavior

The folder name generated by `dbx --init` should be `tasks` instead of `jobs` to repect  to the same naming convention when using jobs API or the Web UI.

## Current Behavior

the folder name is `jobs`:
https://dbx.readthedocs.io/en/latest/templates/python_basic.html

![image](https://user-images.githubusercontent.com/13083856/178492389-2881e87d-b2ac-48cd-9169-b86429601d55.png)

**Comment by renardeinside** [comment]
hi @copdips , 
recent naming convention is actually **workflows**:
<img width="320" alt="Screenshot 2022-07-12 at 15 18 51" src="https://user-images.githubusercontent.com/4979594/178499278-f879259b-173c-4b17-b23e-335d1926cbee.png">
We'll address these issues during the upcoming release, thanks a lot for raising this one. 
Btw it's just a package name in Python, you can simply rename it at your convenience.

**Comment by copdips** [comment]
Yes, indeed I'm currently using `tasks` in my code, I created this issue just would like to have a improvement at dbx side.

**Comment by renardeinside** [comment]
hi @copdips , 
I've refactored the folder, now unit elements are called `tasks`. Changes will take place in 0.6.6.

Thanks a lot for your proposal!
