### ISSUE TITLE
Config file not found

### ISSUE THREAD

**Issue by rafaelvp-db** [databrickslabs/dbx#329]
## Expected Behavior

Config files are loaded correctly by workflow tasks

## Current Behavior

Config file is not found, e.g.:

`FileNotFoundError: [Errno 2] No such file or directory: 'dbfs:/dbx/telco_churn_mlops/fdb43500f86d46ed81f4690db141f7a6/artifacts/conf/data_prep_config.json'`

## Steps to Reproduce (for bugs)

Start a new project with `dbx init`, reference a config file inside a `deployment.json` file, deploy the DBX project and launch it

## Your Environment

* dbx version used: 0.4.1
* Databricks Runtime version: 11.0

**Comment by renardeinside** [comment]
hi @rafaelvp-db , 
shall this be closed since resolution was found?

**Comment by rafaelvp-db** [comment]
sorry @renardeinside, I thought I had been able to fix it with the PR I sent. but I tested it further and the fix caused the MLflow part to stop working. so the issue stands

**Comment by rafaelvp-db** [comment]
as per @mshtelma 's guidance, I've added a bit to _read_config_file function in common.py to fix the config path. so now it looks like this:

```@staticmethod
    def _read_config(conf_file) -> Dict[str, Any]: 
        filename = conf_file.replace("dbfs:/", "/dbfs/")
        config = yaml.safe_load(pathlib.Path(filename).read_text())
        return config```

with this change I was able to fix the issue. thanks @mshtelma and @renardeinside for the input!
