### ISSUE TITLE
Plans for cluster deployments

### ISSUE THREAD

**Issue by guiferviz** [databrickslabs/dbx#33]
Hi! Do you have any plans to include cluster deployment as well or is `dbx` only intended for jobs?

I think it would be nice to have a list of clusters at the same level as the list of jobs. Something like:
```json
{
    "default": {
        "jobs": [...],
        "clusters": [...],
    }
}
```

I would be very happy to work on it if we agree on a definition. Something worth discussing would be whether jobs should reference clusters with the id (like the API requires) or with the name (it would require a lookup prior to job creation to substitute the name for the id).

**Comment by renardeinside** [comment]
Hi @guiferviz , 

Thanks a lot for opening this issue. 

In general, I would say that this feature can be achieved or implemented **not** in dbx. 
As per the definition - dbx is a _job management tool_, while clusters management is more a part of _infrastructure_ settings. 
For interactive cluster management, it's much better to use the Databricks CLI directly, or Terraform provider. 

For automated cluster management (cluster definition for a job), this might be achieved via generating the deployment.json file with Python script, or via using Jsonnet.

Here is a quick example with Jsonnet:
```json
local baseConfig = {
    "spark_version": "7.3.x-cpu-ml-scala2.12",
    "node_type_id": "some_node_type",
    "num_workers": 1,
    "max_retries": 3,
};

local clusterConfigs = {
    "silver": baseConfig + {"num_workers": 2}, // override parameters
    "gold": baseConfig + {"node_type_id": "some_other_node_type", "num_workers": 10},
};

// group big chunks to avoid config duplication
local notifications = {
        "email_notifications": {
        "on_start": ["some-email@example.com"],
        "on_success": ["some-other-email@example.com"],
        "on_failure": ["one-more-email@example.com"]
    }
}; 

local basicJob = {
    "libraries": [],
} + notifications;

// finalized deployment definition
local deploymentDefinition = {
    "default": {
        "jobs": [
            basicJob + {"name": jobName, "new_cluster": clusterConfigs[jobName]}
            for jobName in ["silver", "gold"]
        ],
    },
};

deploymentDefinition
```

With Jsonnet, we can dump this definition into a file:
```bash
jsonnet conf/deployment.jsonnet > conf/generated_deployment.json
```

Output will look like:
```json
{
   "default": {
      "jobs": [
         {
            "email_notifications": {
               "on_failure": [
                  "one-more-email@example.com"
               ],
               "on_start": [
                  "some-email@example.com"
               ],
               "on_success": [
                  "some-other-email@example.com"
               ]
            },
            "libraries": [],
            "name": "silver",
            "new_cluster": {
               "max_retries": 3,
               "node_type_id": "some_node_type",
               "num_workers": 2,
               "spark_version": "7.3.x-cpu-ml-scala2.12"
            }
         },
         {
            "email_notifications": {
               "on_failure": [
                  "one-more-email@example.com"
               ],
               "on_start": [
                  "some-email@example.com"
               ],
               "on_success": [
                  "some-other-email@example.com"
               ]
            },
            "libraries": [],
            "name": "gold",
            "new_cluster": {
               "max_retries": 3,
               "node_type_id": "some_other_node_type",
               "num_workers": 10,
               "spark_version": "7.3.x-cpu-ml-scala2.12"
            }
         }
      ]
   }
}
```
And can be directly used in dbx:
```
dbx deploy
```

Will that solve your problem?

**Comment by guiferviz** [comment]
Thanks for your quick response @renardeinside!
jsonnet is a really good tool for working with these configuration files, thanks for pointing it out.

My proposal was motivated from clients that prefer to have a single cluster on which to run several or all of their jobs in order to save costs. I understand that cluster deployment is more infrastructure-related, but in my view also ephemeral clusters are kind of related to infrastructure; at the end we are creating computing resources.
Also, create or update a cluster with libraries and pre-deployment scripts needs more than one simple API call using Databricks CLI, hence my desire to have a package that deals with such things.

The good thing is that I can always use `"existing_cluster_id"` in my job definition and continue to use `dbx` for job deployment and execution :)

**Comment by renardeinside** [comment]
@guiferviz , 
so would it be okay for you to use the `existing_cluster_id` or Jsonnet option?

**Comment by guiferviz** [comment]
Hi @renardeinside , yes thanks, I'll close the issue.
