### ISSUE TITLE
Is there a documentation for "dbx" library in Python? 

### ISSUE THREAD

**Issue by OmkarMehta** [databrickslabs/dbx#331]
## Expected Behavior
dbx.configure()
## Current Behavior
![image](https://user-images.githubusercontent.com/18292840/178616143-2a0b69d6-2c77-428b-a5e6-633531958f9a.png)

## Your Environment

* dbx version used:>0.5
* Databricks Runtime version: 9.1

**Comment by renardeinside** [comment]
hi @OmkarMehta , 
it's not expected that users will use dbx as a library at the moment, since interfaces are unstable and are a subject to change. dbx is designed as a CLI tool in the first place. 
Could you please explain the use-case for dbx running as a library on the cluster?

**Comment by OmkarMehta** [comment]
hi @renardeinside,
Got it. I want to create a Kubeflow workflow for spark apps jobs. So, I started with `dbx`. While I can use `dbx` cli to create a new job and cluster using `deployment.json` file, and Databricks notebook. I wish to automate `dbx` commands. 
For that, `dbx` library would be easier to use for making the deployment. Correct me, if I am wrong.

**Comment by renardeinside** [comment]
hi @OmkarMehta , 

I'm not sure if Kubeflow pipelines are somehow relevant to:
- using dbx in the notebook (as per your initial screenshot)
- both batch or streaming jobs on Databricks, as well as to Databricks CLI. 

Maybe I miss some critical knowledge of Kubeflow. 

Here is what I see from quick check of its [documentation](https://www.kubeflow.org/docs/components/pipelines/introduction/):

> The Kubeflow Pipelines platform consists of:
> - A user interface (UI) for managing and tracking experiments, jobs, and runs.
> - An engine for scheduling multi-step ML workflows.
> - An SDK for defining and manipulating pipelines and components.
> - Notebooks for interacting with the system using the SDK.

As for tracking experiments/jobs/runs, you can do this with managed mlflow which is already included into Databricks platform. 
Scheduling multi-step ML workflows could be easily done with Databricks multistep jobs.
I don't think it makes sense to mention the Notebooks part when there are Databricks notebooks.

I can imagine that you are looking to use kubeflow to _orchestrate_ jobs on Databricks. In this case you have two separate layers:
- job definition and deployment
- job orchestration and launch

For job definition and deployment you simply use dbx CLI interface as described in the docs (`dbx deploy` command). 
For job orchestration you might use Kubeflow Pipelines (and this is one place where I see it in this architecture). In this case you can simply call `dbx launch` command from your pipeline to trigger and trace job execution. You can also trigger this command programmatically by using `dbx.commands.launch` command. 

Hope this helps.
