### ISSUE TITLE
dbx Deploy on Windows error: File In Use By Another Process

### ISSUE THREAD

**Issue by billkellett** [databrickslabs/dbx#334]
## Expected Behavior: 
I am running the ide-best-practices reference application on VSCode, following instructions at https://docs.microsoft.com/en-us/azure/databricks/dev-tools/ide-how-to.  When I run `dbx deploy --environment=default` I expect the command to run successfully. 

## Current Behavior: 
I am able to Deploy successfully with VSCode on Mac.  However, the Deploy step fails on Windows.  The relevant error from console output is:

 `error: [WinError 32] The process cannot access the file because it is being used by another process: 'build\\bdist.win-amd64\\wheel\\.\\covid_analysis-0.0.1-py3.9.egg-info\\dependency_links.txt'`

Complete console output from the Deploy step is: 

`(ide-demo3) PS C:\Users\Bill\Dropbox\python\databricks-via-ide\ide-demo3\ide-best-practices> dbx deploy --environment=default
[dbx][2022-07-14 13:40:29.096] Starting new deployment for environment default
[dbx][2022-07-14 13:40:29.109] Using profile provided from the project file
[dbx][2022-07-14 13:40:29.110] Found auth config from provider ProfileEnvConfigProvider, verifying it
[dbx][2022-07-14 13:40:29.111] Found auth config from provider ProfileEnvConfigProvider, verification successful
[dbx][2022-07-14 13:40:29.111] Profile DEFAULT will be used for deployment
[dbx][2022-07-14 13:40:30.357] Auto-discovery found deployment file conf\deployment.yml
[dbx][2022-07-14 13:40:30.369] Re-building package
Obtaining file:///C:/Users/Bill/Dropbox/python/databricks-via-ide/ide-demo3/ide-best-practices
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: covid-analysis
  Building wheel for covid-analysis (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [32 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib
      creating build\lib\covid_analysis
      copying covid_analysis\transforms.py -> build\lib\covid_analysis
      copying covid_analysis\__init__.py -> build\lib\covid_analysis
      C:\Users\Bill\.virtualenvs\ide-demo3-yKT8r90k\lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      installing to build\bdist.win-amd64\wheel
      running install
      running install_lib
      creating build\bdist.win-amd64
      creating build\bdist.win-amd64\wheel
      creating build\bdist.win-amd64\wheel\covid_analysis
      copying build\lib\covid_analysis\transforms.py -> build\bdist.win-amd64\wheel\.\covid_analysis
      copying build\lib\covid_analysis\__init__.py -> build\bdist.win-amd64\wheel\.\covid_analysis
      running install_egg_info
      running egg_info
      writing covid_analysis.egg-info\PKG-INFO
      writing dependency_links to covid_analysis.egg-info\dependency_links.txt
      writing top-level names to covid_analysis.egg-info\top_level.txt
      reading manifest file 'covid_analysis.egg-info\SOURCES.txt'
      adding license file 'LICENSE'
      adding license file 'NOTICE.txt'
      writing manifest file 'covid_analysis.egg-info\SOURCES.txt'
      Copying covid_analysis.egg-info to build\bdist.win-amd64\wheel\.\covid_analysis-0.0.1-py3.9.egg-info
      running install_scripts
      adding license file "LICENSE" (matched pattern "LICEN[CS]E*")
      adding license file "NOTICE.txt" (matched pattern "NOTICE*")
      error: [WinError 32] The process cannot access the file because it is being used by another process: 'build\\bdist.win-amd64\\wheel\\.\\covid_analysis-0.0.1-py3.9.egg-info\\dependency_links.txt'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for covid-analysis
  Running setup.py clean for covid-analysis
Failed to build covid-analysis
ERROR: Failed to build one or more wheels
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Bill\.virtualenvs\ide-demo3-yKT8r90k\Scripts\dbx.exe\__main__.py", line 7, in <module>
  File "C:\Users\Bill\.virtualenvs\ide-demo3-yKT8r90k\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\Bill\.virtualenvs\ide-demo3-yKT8r90k\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\Bill\.virtualenvs\ide-demo3-yKT8r90k\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\Bill\.virtualenvs\ide-demo3-yKT8r90k\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\Bill\.virtualenvs\ide-demo3-yKT8r90k\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\Bill\.virtualenvs\ide-demo3-yKT8r90k\lib\site-packages\dbx\commands\deploy.py", line 151, in deploy
    dependency_manager = DependencyManager(no_package, no_rebuild, requirements_file)
  File "C:\Users\Bill\.virtualenvs\ide-demo3-yKT8r90k\lib\site-packages\dbx\utils\dependency_manager.py", line 25, in __init__
    self._core_package_reference: Optional[LibraryReference] = self._get_package_requirement()
  File "C:\Users\Bill\.virtualenvs\ide-demo3-yKT8r90k\lib\site-packages\dbx\utils\dependency_manager.py", line 61, in _get_package_requirement
    handle_package(self._no_rebuild)
  File "C:\Users\Bill\.virtualenvs\ide-demo3-yKT8r90k\lib\site-packages\dbx\utils\common.py", line 85, in handle_package
    subprocess.check_call([sys.executable] + shlex.split("-m pip wheel -w dist -e . --prefer-binary"))
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['C:\\Users\\Bill\\.virtualenvs\\ide-demo3-yKT8r90k\\Scripts\\python.exe', '-m', 'pip', 'wheel', '-w', 'dist', '-e', '.', '--prefer-binary']' returned non-zero exit status 1.
(ide-demo3) PS C:\Users\Bill\Dropbox\python\databricks-via-ide\ide-demo3\ide-best-practices> `

## Steps to Reproduce (for bugs): 
I am simply following the instructions for the reference application at https://docs.microsoft.com/en-us/azure/databricks/dev-tools/ide-how-to 

## Context
It all works fine for me on Mac, and I believe I'm doing the exact same steps on Windows.

## Your Environment
I am running Windows 10 Pro Version 21H1 OS Build 19043.1826 with Windows Feature Experience Pack 120.2212.4180.0

VSCode info:
Version: 1.63.2 (system setup)
Commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3
Date: 2021-12-15T09:40:02.816Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19043

* dbx version used: 0.6.4
* Databricks Runtime version: 10.4.x-scala2.12

**Comment by renardeinside** [comment]
hi @billkellett , 
have you tried upgrading pip on your machine as per this issue https://github.com/pypa/pip/issues/7865

**Comment by billkellett** [comment]
Hi Ivan,

When I try to upgrade pip using the syntax described in pypa/pip#7865<https://github.com/pypa/pip/issues/7865> ( python -m pip install --upgrade pip ) I get the following response:

Requirement already satisfied: pip in c:\python310\lib\site-packages (22.1.2)

So it appears that I have the latest version.  I do see this version when I do pip --version in my Virtual Environment as well.


________________________________

**Comment by renardeinside** [comment]
hi @billkellett , 
I've recently changed the way how dbx makes it's build - could you please try again with dbx 0.6.5 ?

**Comment by billkellett** [comment]
Hi Ivan,

I built a new project using reference app with dbx 0.6.5, but I'm still getting the same error message:

error: [WinError 32] The process cannot access the file because it is being used by another process: 'build\\bdist.win-amd64\\wheel\\covid_analysis-0.0.1.dist-info'


________________________________

**Comment by renardeinside** [comment]
hi @billkellett , 

I've just tried it in a new project on Win10 and it was working as expected. Could you please try the following:

```
pip uninstall <project-name>
```
Then:
```
pip install -e .
```
And then launch the deploy command?

**Comment by billkellett** [comment]
Ivan, no change in behavior.  Since you got it working on Win10, it must be something odd or corrupt on my machine.  No need trying other tests unless it's something specifically related to the error message I see.

Thanks,

Bill.

________________________________

**Comment by renardeinside** [comment]
sure @billkellett , 
I'm closing this one as non-reproducible. If you'll be able to repro this issue on another machine, please re-open this one.
