### ISSUE TITLE
Task paramter variable

### ISSUE THREAD

**Issue by ptabandzelic** [databrickslabs/dbx#352]
Hey, is this has to do with dbx?When i put some of the task paramter variables inside  "-name" for example:
- name: databricks-job-{{start_id}} in yaml configuration file, it does not parse that variable in databricks jobs ui.

**Comment by renardeinside** [comment]
hi @ptabandzelic , 

could you please re-open the request as per GitHub Issue template - mentioning the version, current behaviour, expected behaviour etc. These fields are there not because we like bureaucracy, these fields are there to ease the triaging process.
