### ISSUE TITLE
Why by dbx init we generate tasks/ for databricks jobs

### ISSUE THREAD

**Issue by ptabandzelic** [databrickslabs/dbx#358]
So under the tasks/ we have databricks jobs which consists of tasks. Why on the top level we have tasks/ and not jobs/

**Comment by renardeinside** [comment]
hi @ptabandzelic , 
this discussion already took place [here](https://github.com/databrickslabs/dbx/issues/327) 

Logic is the following - `task` represents a unit element of computation, and tasks can be arranged into jobs. There could be one or multiple tasks inside a job. 

You're free to rename this package to the convenient name of your choice - it's just naming convention in the end.
