### ISSUE TITLE
[FEATURE] Fetch and use cluster policy definitions when policy_id is defined in deployment config

### ISSUE THREAD

**Issue by dimi-kr** [databrickslabs/dbx#36]
## Expected Behavior
When `policy_id` is being used in deployment configuration of a job all mandatory fields are set in cluster policy automatically merged into api request for job creation/modification.
## Current Behavior
dbx doesn't include mandatory configuration fields from cluster policy.
## Steps to Reproduce (for bugs)
1. Create a policy for cluster with random mandatory fields. 
2. bootstrap a project (https://dbx.readthedocs.io/en/latest/quickstart.html)
3. Include `policy_id` field in deployment.json. Value must be the same as if of a policy created in step 1.
4. `dbx deploy` will fail because a new job is expected to have the field from step 1.
## Your Environment

* dbx version used: 0.1.2
* Databricks Runtime version: doesn't matter

**Comment by renardeinside** [comment]
hi @dimi-kr ,

Thanks a lot for providing the feature request. I'll take a look into it.

**Comment by renardeinside** [comment]
hi @dimi-kr , 
please find policy propagation implementation in version 0.1.3 [here](https://dbx.readthedocs.io/en/latest/properties_propagation.html).
