### ISSUE TITLE
[BUG] Unable to change the artifact location from default

### ISSUE THREAD

**Issue by jessiebwatson** [databrickslabs/dbx#37]
## Expected Behavior
When running `dbx deploy` files should be pushed to chosen artifact location e.g. dbfs:/dbx/{addition_to_path}/{current_folder_name}
## Current Behavior
Always pushes the files to the default file path, even if the project.json artifact location has been changed
e.g. dbfs:/dbx/{current_folder_name}
## Steps to Reproduce (for bugs)
1. Change the project.json artifact location
2. Run `dbx deploy`
3. See where the files have been pushed to (for me this is always the default)
## Context
Want to be able to include initials in the path to push to different places in the dbfs
## Your Environment

* dbx version used: 0.1.2
* Databricks Runtime version: N/A

**Comment by renardeinside** [comment]
Hi @jessiebwatson ,
thanks for opening this issue. I'll take care of it.

**Comment by renardeinside** [comment]
hi @jessiebwatson , 
unfortunately, this issue cannot be directly fixed since MLflow has no direct method for changing the artifact location after experiment creation. Therefore, dbx will raise exception when artifact_location is not matching between project.json and experiment.

**Comment by renardeinside** [comment]
Blocked by [this](https://github.com/mlflow/mlflow/issues/3719) issue on mlflow.
