### ISSUE TITLE
Jobs 2.1 API setting ignored by DatabricksClientProvider

### ISSUE THREAD

**Issue by aholten** [databrickslabs/dbx#378]
## Expected Behavior

[Despite this closed issue stating the contrary](https://github.com/databrickslabs/dbx/issues/162), dbx does not support the Databricks Jobs 2.1 API. 

## Current Behavior

The config/environment variable jobs-api-version value is not passed the `ApiClient` constructor in ` DatabricksClientProvider`'s [_get_v2_client class method](https://github.com/databrickslabs/dbx/blob/f3fc016f944a2a23f2f6bc960c6147ecd60ec12b/dbx/api/client_provider.py#L48) even when available as `config.jobs_api_version` as provided by `config = AuthConfigProvider.get_config()`. 

## Steps to Reproduce (for bugs)

- Configure a profile in `.databrickscfg` to include `jobs-api-version = 2.1`
- Attempt any dbx command that uses a jobs API endpoint using that profile (eg. `dbx deploy`)
- More specifically, the incorrect API urls can be revealed with breakpoints or by attempting to deploy an incorrectly specified deployment yaml/json

## Context
I would like to use the Jobs 2.1 API for [multitask job job cluster sharing](https://docs.databricks.com/data-engineering/jobs/jobs-api-updates.html#api-changes).

## Your Environment

* dbx version used: 0.6.10
* Databricks Runtime version: N/A

**Comment by renardeinside** [comment]
closed in linked PR, will be out in the next release
