### ISSUE TITLE
dbx execute support jinja-variables-file

### ISSUE THREAD

**Issue by ptabandzelic** [databrickslabs/dbx#380]
Hey, right now jinja-variables-file is argument of a dbx deploy.When i use dbx launch with jinja variables inside configuration, its working.But for dbx execute its not reading jinja variables.

so dbx execute --job=job --task=task will throw error if i have jinja vars inside conf file.
dbx launch --job=job will work even if i have jinja vars inside conf file.
dbx deploy --job=job --jinja-variables-files.Works as usual

**Comment by renardeinside** [comment]
closed in the linked PR, will be released in next version
