### ISSUE TITLE
`dbx deploy` returns invalid python file reference in latest versions

### ISSUE THREAD

**Issue by RamonRay** [databrickslabs/dbx#389]
## Expected Behavior
`dbx deploy` succeeds using the deployment config json file and code that works in previous versions (were using 0.1.6, but 0.1.6 returns endpoint not found error when running `dbx execute`)
## Current Behavior
When running dbx deploy, 400 Client Error was thrown
```
 { 'error_code': 'INVALID_PARAMETER_VALUE',
  'message': 'Invalid python file reference: '
             '<package_name>/<python_file_path>. '
             'Please visit the Databricks user guide for supported python '
             'references'}
```
I saw it in 0.6.6 and then upgraded to 0.6.12 and the issue still exists

## Steps to Reproduce (for bugs)
In the deployment config json file, add the task with the following fields
        "spark_python_task": {
          "python_file": "<package_name>/<python_file_path>",
          "parameters": [
               <self_defined_params>
          ]
        }
Then run `dbx deploy --jobs=<job_name> --environment=<environment_name>`

After that, 400 Client Error, Bad Request for url, is thrown.

## Your Environment

* dbx version used:0.6.6 and 0.6.12
* Databricks Runtime version: 9.1.x-scala2.12

**Comment by renardeinside** [comment]
hi @RamonRay , 
this is expected behaviour since 0.6.6. Please reference the file in the following format:
```
"spark_python_task": {
    "python_file": "file://<package_name>/<python_file_path>",
    "parameters": [
        <self_defined_params>
    ]
}
```
