### ISSUE TITLE
[FEATURE] Please support defining the deployment in yaml instead of json.

### ISSUE THREAD

**Issue by jspreddy** [databrickslabs/dbx#39]
## Current Behavior
The deployment is defined in `conf/deployment.json`. 

JSON is cumbersome to read and write. Not to mention it causes duplication of config.

## Context
1. I want to be able to not duplicate config.
2. I want to extract common config and include it in the job definitions.
3. I want to reduce human error when configuring the jobs.
4. I want to be able to extend/add functionality to the deployment config file in the future.

## Proposal
1. Allow `--deployment-file` to take a `deployment(.json | .yaml | .yml)` file. 
2. By default check for `deployment(.json | .yaml | .yml)` file in the conf folder.
3. Parse the file appropriately.

## Your Environment

* dbx version used: DataBricks eXtensions aka dbx, version ~> 0.1.2
* Databricks Runtime version: 8.1, 8.2

**Comment by renardeinside** [comment]
hi @jspreddy , 

would you like to volunteer and provide a PR with implementation?

**Comment by renardeinside** [comment]
Just released in 0.1.5. Thank you @jspreddy for investing your time into this and making the whole implementation! 🔥

**Comment by jspreddy** [comment]
The changelog is not properly updated for the release.
