### ISSUE TITLE
Getting TypeError: 'NoneType' object does not support item assignment if I run dbx execute

### ISSUE THREAD

**Issue by atursunov** [databrickslabs/dbx#391]
## Expected Behavior
run successfully following command:
dbx execute --cluster-name=<name of interactive cluster> --job=cicd-demo-sample-integration-test

## Current Behavior
![image](https://user-images.githubusercontent.com/7220691/184920736-77fe561e-5edf-400f-abe3-78b821cd518e.png)

## Steps to Reproduce (for bugs)
1. pip install cookiecutter path
2. cookiecutter https://github.com/databrickslabs/cicd-templates
3. follow instructions in README.md and/or https://www.youtube.com/watch?v=rs4hz9HX0WM&t=1s

## Context
Trying to run unit and integration tests both locally (in PyCharm) and remotely (in Azure Databricks).

## Your Environment
OS: Windows 10
Python: 3.8.10
Cloud: Azure
CICD tool: Azure DevOps

* dbx version used: 0.6.12
* Databricks Runtime version: 9.1.x-cpu-ml-scala2.12

**Comment by renardeinside** [comment]
Hi @atursunov , 
cicd-templates is deprecated. Please use `dbx init` instead, and follow the guidelines [here](https://docs.microsoft.com/en-us/azure/databricks/dev-tools/dbx).
