### ISSUE TITLE
[FEATURE] Handling concurrent CI jobs

### ISSUE THREAD

**Issue by mickvanhulst-TomTom** [databrickslabs/dbx#393]
Within our team, we have various members who may or may not be making changes to a job and want to test that job with different parameters. This, for example, occurs when we trigger our CI where we want to make sure that we are not overwriting one another's files/data.

As we are considering migrating to dbx fully, I am wondering whether there is a suggested workflow on how to handle concurrent requests to jobs with possibly different parameters etc.?

I have seen the jobless deployments, but I am getting the error `'Shared job cluster feature is not supported in runs/submit API.'`, which makes me assume that it is not yet supported. The functionality also seems rather ambiguous to me. Is it the case that I would essentially call an existing job with potentially different parameters? What "files" are deployed and which are not?

https://dbx.readthedocs.io/en/latest/guidance/run_submit.html

**Comment by renardeinside** [comment]
hi @mickvanhulst-TomTom , 

if you're planning to migrate towards `dbx` fully I would recommend doing it with the 0.7.X update which brings more flexibility, documentation and features. We're planning to finish the 0.7.0 release until the end of August. 

Although the changes we're planning to introduce are more on the documentation and interface side, we're not planning to introduce breaking changes except some minor behaviours in `dbx sync`. 

On the topic of files-only and jobless deployment and runs, please take a look at [this](https://dbx.readthedocs.io/en/v0.6.12/guidance/run_submit.html) documentation.

Short answer is that if you're using ```dbx deploy --files-only```, it will only upload the files and save job definition as an asset in the artifact storage, but it won't create or update any of the existing jobs. 

At the same time when you're using:
`dbx launch --as-run-submit` it will pick up the latest asset from the artifact storage (deployed with command above) and create an ephemeral run (run which is not registered or created as a job). 
RunSubmit which performs this launch doesn't support shared clusters (as described in 'Shared job cluster feature is not supported in runs/submit API.' error message). It's a limitation of Databricks Jobs, not a limitation of dbx. 

> As we are considering migrating to dbx fully, I am wondering whether there is a suggested workflow on how to handle concurrent requests to jobs with possibly different parameters etc.?

Simply use dbx deploy (without --files-only option) and then use dbx launch with various parameters provided in the `parameters` section. 
Existing runs behaviour can be defined with --existing-runs option (you can wait for them to finish, simply create a concurrent run with different set of parameters, or cancel the existing runs).

**Comment by renardeinside** [comment]
hi @mickvanhulst-TomTom , 
is the reply above something that covers the concurrent CI case? Also take a look at this [documentation](https://dbx.readthedocs.io/en/latest/features/assets/) piece - is it something that covers the topic nicely?

**Comment by mickvanhulst-TomTom** [comment]
Hi @renardeinside , thanks for the update, the updated documentation looks a lot better, great job! 

My understanding is that we would be able to completely isolate our runs by using tags (i.e., `dbx deploy <workflow-name> --assets-only --tags "cake=cheesecake"`); although the tags flag is only needed when there are multiple people working on the same branch. When deploying in an assets-only fashion, can we still use environment variables like branch name (e.g., [0]) in our configurations?

To further isolate any of the artifacts that are created during these runs, can we use `parameters` to overwrite our task (notebook or Python wheel) parameters? 

[0] https://dbx.readthedocs.io/en/latest/guides/python/devops/python_notebook_devops/?h=git#using-jinja-to-pass-tags-and-branches-from-environment-variables

**Comment by renardeinside** [comment]
> When deploying in an assets-only fashion, can we still use environment variables like branch name (e.g., [0]) in our configurations?

yes, definitely - the Jinja functionality works independently of the `--assets-only` behaviour. It's described [here](https://dbx.readthedocs.io/en/latest/features/jinja_support/).

> To further isolate any of the artifacts that are created during these runs, can we use parameters to overwrite our task (notebook or Python wheel) parameters?

the `--parameters` option is absolutely irrelevant to the deployment isolation. 

deployment isolation happens during `dbx deploy --assets-only`, `--parameters` simply gives you an interface to override default parameters when launching the workflow. 

If it's intended in your CI pipelines to launch the workflow with different set of parameters to avoid overriding each others data, you can use it straight away.

**Comment by renardeinside** [comment]
Closing this one since this behaviour is documented and provided in the docs. 
In case of any follow up questions please feel free to create a new ticket or kickoff a discussion.
