### ISSUE TITLE
dbx launch: Run url wrapped to 2+1 lines

### ISSUE THREAD

**Issue by tonkolviktor** [databrickslabs/dbx#452]
## Expected Behavior
I expect the Run url in one line.

## Current Behavior
I have 2 lines (+1 for the timestamp):
![image](https://user-images.githubusercontent.com/4534324/188427863-91b8586d-e2ff-48b9-a831-c8115d6b8a17.png)

```
[dbx][2022-09-05 09:55:40.440] Run URL: 
https://adb-XXXXXXXX.2.azuredatabricks.net/?o=YYYYYY#job/8ZZZ6
9ZZZZZZ3/run/963171
```

## Steps to Reproduce (for bugs)
I'm a bit unsure if this happens everyone or only in Azure DevOps when there is an traceback

## Context
I'm running a CI and I have an error. I would like to click on the url, but that does not work.

I'm not 100% sure if this is a dbx problem, but in <0.7.* this worked, so I'll try here first.

## Your Environment
dbx 0.7.4
Azure DevOps

* dbx version used: dbx 0.7.4
* Databricks Runtime version:  10.4 LTS[](url)

**Comment by renardeinside** [comment]
I cannot reproduce this behaviour locally, seems like something specific to how Azure DevOps formats the output.

**Comment by renardeinside** [comment]
I assume it's due to how[ rich strings](https://rich.readthedocs.io/en/stable/introduction.html) are formatted, let me check what the options are. 
Thanks a lot for reporting this one @tonkolviktor !

**Comment by badjouras** [comment]
I'm also facing this issue. Locally it's fine, on ADO I get the split lines.
