### ISSUE TITLE
[FEATURE] Add support for getting the current branch name within GitLab CI

### ISSUE THREAD

**Issue by allebacco** [databrickslabs/dbx#46]
## Expected Behavior

When calling the `get_current_branch_name()` function during a deploy executed within a GitLab-CI job, the function returns the current branch name.

## Current Behavior

When calling the `get_current_branch_name()` function during a deploy executed within a GitLab-CI job, the function returns `None`.

## Context

I am calling `dbx deploy` within a GitLab-CI job. The name of the current branch can be retrieved with the `CI_COMMIT_REF_NAME` environment variable.

For more details about GitLab-CI variables, see [Predefined variables reference](https://docs.gitlab.com/ee/ci/variables/predefined_variables.html).

## Possible implementations

1. in `get_current_branch_name()`, add an `if "CI_COMMIT_REF_NAME" in os.environ:` section for reading the branch name, like for the GitHub one
2. (more generic) in the `deploy` command add a `--branch-name` argument for passing the name of the branch

## Your Environment

* dbx version used: 0.1.3
* Databricks Runtime version: 8.1 (includes Apache Spark 3.1.1, Scala 2.12)

**Comment by renardeinside** [comment]
hi @allebacco , 

thanks a lot for raising this issue. 
Would you like to volunteer and propose a PR?

**Comment by allebacco** [comment]
hi @renardeinside ,

I will try to propose a PR in the next days.

My idea is to add a `--branch-name` argument to the `deploy` command. In this way I am not targeting only the GitLab CI use case but all the use cases in which the branch name should be provided.

**Comment by renardeinside** [comment]
thanks a lot @allebacco , 
The only thing I possible would like to mention - `--branch-name` parameter shall be optional, and it shall be defined both for deploy and launch commands. If the parameter is not provided, we pick branch name using logic in `get_current_branch_name()` function. Does that make sense from your perspective?

**Comment by allebacco** [comment]
Yes, It make sense. 

So just to recap the requirements:
* the name of the parameter should be `--branch-name`
* the parameter should be added to `deploy` and `launch` commands
* the parameter should be optional
* if not provided (or empty string), fallback is to call the `get_current_branch_name()` function for getting a branch name, like in current implementation
