### ISSUE TITLE
No such option: --workflow   

### ISSUE THREAD

**Issue by AnastasiaProkaieva** [databrickslabs/dbx#461]
## Expected Behavior
dbx launch --workflow
## Current Behavior
`dbx launch` is expecting a flag `--job` even the docstring mentioning that. 
> This option is deprecated, please use workflow name as argument instead.
`dbx deploy --workflows `on the other hand works. 

## Steps to Reproduce (for bugs)
dbx launch --workflow
## Your Environment
Python 3.9.12
* dbx version used: 0.7.4

**Comment by renardeinside** [comment]
> This option is deprecated, please use workflow name as argument instead.

Not sure if this doc is unclear, but it explicitly says:

<img width="715" alt="Screenshot 2022-09-11 at 20 11 52" src="https://user-images.githubusercontent.com/4979594/189542678-03399ac0-dae3-458d-bd60-ca72e72fa35e.png">

Workflow name is an **argument**, not an option.
