### ISSUE TITLE
dbx deploy fails when no workflows are defined

### ISSUE THREAD

**Issue by crash-g** [databrickslabs/dbx#484]
## Expected Behavior

Calling `dbx` without defining any workflow should not raise an exception (it should be a no-op).

## Current Behavior

When executing

```
dbx deploy --deployment-file=config.json --no-package
```

with the following `config.json`

```json
{
  "build": {
    "no_build": true
  },
  "environments": {
    "staging": {
      "workflows": []
    }
  }
}
```

`dbx` fails with `Exception: No jobs provided for deployment`

## Context

We generate our `config.json` file automatically and depending on the environment it may be empty. This was never a problem in past versions of `dbx`, but with commit ca25fc96 an unconditional check has been introduced which makes our pipelines fail as described above.

Would it be possible to revert to the previous behavior, or at least give the possibility to turn the check off?

## Your Environment

* dbx version used: `0.7.5`
* Databricks Runtime version: 10.4

**Comment by renardeinside** [comment]
hi @crash-g , 
thanks a lot for opening the issue. agree with you that this should remain a noop. Fix is merged, will be released as a part of 0.7.6
