### ISSUE TITLE
dbx sync token 

### ISSUE THREAD

**Issue by ptabandzelic** [databrickslabs/dbx#493]
Hey, so i have cloned repo on Databricks REPO.
Next thing locally(IDE) when want to sync to Databricks REPO following happens:
``
dbx sync repo --dest-repo name_repo_on_databricks --environment=production
``

````
│   215 │   │   if not repo_name:                                                                 
│   216 │   │   │   raise ValueError("repo_name is required")                                     
│   217 │   │   self.base_path = f"/Repos/{user}/{repo_name}"                                     
│ ❱ 218 │   │   self.api_token = config.token                                                     
│   219 │   │   self.host = config.host.rstrip("/")                                               
│   220 │   │   self.workspace_api_base_path = f"{self.host}/api/2.0/workspace"               
│   221 │   │   self.workspace_files_api_base_path = f"{self.host}/api/2.0/workspace-files/impo 
AttributeError: 'NoneType' object has no attribute 'token'
````

Every other dbx commands work, deploy, execute, launch, destroy etc..

**Comment by copdips** [comment]
Have you configured the Databricks auth in advance ?
If not, this [link](https://dbx.readthedocs.io/en/latest/guides/python/python_quickstart/?h=token#preparing-the-local-environment) might help.

**Comment by renardeinside** [comment]
hi @ptabandzelic , 
could you please share the content of `.dbx/project.json` file?

**Comment by renardeinside** [comment]
closed as no reply provided. if error occures again please feel free to re-open.
