### ISSUE TITLE
[dbx launch] TypeError: submit_run() got an unexpected keyword argument 'max_retries'

### ISSUE THREAD

**Issue by TamGB** [databrickslabs/dbx#500]
## Expected Behavior
Job should be deployed normally via the Jobs API.

## Current Behavior
Deploying a job like we normally did - typically performed via CI/CD in Gitlab - suddenly started returning an error given by:
`TypeError: submit_run() got an unexpected keyword argument 'max_retries'`

## Steps to Reproduce (for bugs)
Run the launch command: `dbx launch --environment=tests_environment --job=integration_tests --as-run-submit`

Considering the job file, `deployment.json`:
```
{
  "integration_tests": {
      "workflows": [
          {
              "name": "integration_tests",
              "new_cluster": {
                  "spark_version": "11.2.x-scala2.12",
                  "node_type_id": "Standard_F4s",
                  "spark_env_vars": {
                      "PYSPARK_PYTHON": "/databricks/python3/bin/python3",
                  },
                  "enable_elastic_disk": true,
                  "azure_attributes": {
                      "availability": "ON_DEMAND_AZURE"
                  },
                  "num_workers": 2
              },
              "libraries": [],
              "max_retries": 0,
              "spark_python_task": {
                  "python_file": "file://tests/integration/integration_tests_runner.py"
              },
              "timeout_seconds": 3600
          }
      ]
  }, 
}
```

While it does contain a `max_retries` parameter, even removing it yields the same result. It seems the dbx library is injecting that parameter by default regardless of its presence.

Oddly enough, even in the official Jobs 2.1 documentation the `max_retries` parameter is mentioned in the examples, see [documentation](https://docs.databricks.com/dev-tools/api/latest/jobs.html).

## Your Environment

* dbx version used: 0.7.5
* Databricks Runtime version: 11.2.x-scala2.12

**Comment by Stefanos-Arampatzis** [comment]
@renardeinside 
 I have experienced the same issues today. Looks like when using dbx launch (--from-assets), Service.run_submit , final_spec has all the arguments from  Service.create_job (--assets-only)
e.g. max_retries, email_notifications

**Comment by TamGB** [comment]
Have you managed to bypass it somehow @Stefanos-Arampatzis ?

**Comment by renardeinside** [comment]
hi @Stefanos-Arampatzis , 
the bug is spotted, thanks a lot. Most probably I'll will release the remedy release in 2-3 hours.
