### ISSUE TITLE
Typo in dbx sync docs 

### ISSUE THREAD

**Issue by NodeJSmith** [databrickslabs/dbx#504]
The dbx sync command has a typo in the docstring. This is feeding into the documentation.

https://github.com/databrickslabs/dbx/blob/50e4e696397327e9a0ce368ae55c6ee7fd83a8a3/dbx/commands/sync/options.py#L142

**Comment by renardeinside** [comment]
thanks for raising this one @NodeJSmith, i've addressed it in #511
