### ISSUE TITLE
jinja variables file

### ISSUE THREAD

**Issue by ptabandzelic** [databrickslabs/dbx#510]
Can we have support for multiple variable files for deployment configuration?

**Comment by renardeinside** [comment]
I don't think this is a good design to be honest. Could you please describe the use-case and the way you see you use it?

**Comment by ptabandzelic** [comment]
For example, in one configuration file i would like to have everything related to building workflows, cluster.
In other configuration file i would like to have parameters that are related to the each task of workflow.
For example a lot of parameters sensitive to task are passed as CLI arguments and those parameters are dependent on usecase, so maybe i want to change these task params in automated way, with same workflow configuration.

**Comment by renardeinside** [comment]
> For example, in one configuration file i would like to have everything related to building workflows, cluster.
In other configuration file i would like to have parameters that are related to the each task of workflow.
For example a lot of parameters sensitive to task are passed as CLI arguments and those parameters are dependent on usecase, so maybe i want to change these task params in automated way, with same workflow configuration.

I think what you're describing is a dynamic configuration pattern. My take on this would be the [JSONNet](https://jsonnet.org/), not the functionality of `dbx`. It allows you to generate multiple definition files, dynamically and with conditioning and cross-referencing between the files - and then these files could be feeded to `dbx` interfaces. Would that be something sufficient?

**Comment by ptabandzelic** [comment]
Will check it out, thank u!
