### ISSUE TITLE
Update instead of reset job/workflow for dbx deploy

### ISSUE THREAD

**Issue by ddxgz** [databrickslabs/dbx#512]
## Expected Behavior
The redeployed existing jobs/workflows will keep the historical completed runs.

## Current Behavior
~~The existing jobs/workflows lost all the historical completed runs after re-deployment with `dbx deploy`~~
**Correction**: Not every job, but some of the existing jobs/workflows lost all the historical completed runs after re-deployment with `dbx deploy`. 

Haven't found the cause yet, will update later.

## Steps to Reproduce (for bugs)
1. Deploy a workflow
2. Run the workflow
3. Redeploy the workflow
4. You will find the completed runs are empty

## Context
It's crucial to keep historical runs for jobs. For existing jobs/workflows, the re-deployment should keep the historical runs, or provide an option in cli to choose whether to reset or update the jobs/workflow. 

In the code line below, dbx uses `jobs_service.reset_job(job_id, job)` instead of `jobs_service.update_job(job_id, job)`. 
https://github.com/databrickslabs/dbx/blob/d9c28ee4dc2f5d5a45e67d69d713e04f06db620e/dbx/commands/deploy.py#L275

## Your Environment

* dbx version used: 0.7.6
* Databricks Runtime version:

**Comment by renardeinside** [comment]
hi @ddxgz , 
thanks a lot for reporting this one, we're currently looking for RCA. Stay tuned for updates

**Comment by renardeinside** [comment]
hi @ddxgz , 
I've tried multiple times in multiple environments, but cannot reproduce this issue. Is it still reproducible on your side?

**Comment by ddxgz** [comment]
Hi @renardeinside , I'll try to reproduce, or try to see if it's caused by something else this week. I'll close the issue if I cannot reproduce it.

**Comment by ddxgz** [comment]
Sorry that I didn't have time to try again. I will close this issue. Will come back if I managed to find something. Thanks!
