### ISSUE TITLE
Jinja `get_last_modified_file()` looks for target file of _previous_ build, not current

### ISSUE THREAD

**Issue by rwoodard-prog** [databrickslabs/dbx#523]
(An easy, non-dbx workaround exists for this issue, documented below.  Still wanted to point this out.)

## Expected Behavior

Jinja should populate `dbx.get_last_modified_file()` after the build step.

## Current Behavior

Jinja tries to populate `dbx.get_last_modified_file()` before the build step.

## Steps to Reproduce (for bugs)

Using this config:

```yaml
build:
  commands:
    - sbt clean compile package

...

            libraries:
              - jar: "{{ 'file://' + dbx.get_last_modified_file('target/scala-2.12', 'jar') }}"
...
```

Simple way to reproduce is to delete target dir:

```shell
rm -fr target/
dbx deploy MyJob --assets-only
```

This results in an error:

```
...
[dbx][2022-10-15 11:01:04.443] No file was found in path target/scala-2.12
...
TypeError: can only concatenate str (not "NoneType") to str
```

This is because Jinja tries to populate `dbx.get_last_modified_file()` before the `build` block.

The way I actually found the error:

In a workflow, which consists of editing, building, deploying, launching, an intermediate error can cause this error.

When I call

`dbx deploy MyJob --assets-only`

the build step `sbt clean` will delete the existing target (from a previous build), `target/scala-2.12/myjob_2.12.14-3.2.1_0.1.1.jar`.  

If I have a bug in my code so that `sbt compile` fails, then `dbx` exits (as it should). Note that the target jar will not be built.

I fix my code and rerun `dbx deploy`.  Since the target jar was deleted in previous `dbx` call _and_ since Jinja substitution happens before the `build` block is executed, Jinja fails to populate `dbx.get_last_modified_file()` because it does not exist.  This causes `dbx` to fail before it can execute the `sbt` commands specified in the `build` block.

If the `build` block ran first, then the target jar would be built and Jinja would find it correctly.

I can easily work around this by always building outside of `dbx`:

```yaml
...
build:
  no_build: true
...
```

and calling:

```shell
sbt clean compile package && \
  dbx deploy MyJob --assets-only && \
  dbx launch McJob --from-assets
```

The more difficult workaround would be to never write bugs.  I will probably stick with the first solution...

## Your Environment

* dbx version used:

```
dbx --version
[dbx][2022-10-15 11:11:01.407] 🧱Databricks eXtensions aka dbx, version ~> 0.7.6
```

* Databricks Runtime version: 

n/a

**Comment by renardeinside** [comment]
hi @rwoodard-prog , 
thanks a lot for opening the issue. I'll see what I can do about it, there are various workarounds that I've in mind.

**Comment by renardeinside** [comment]
hi @rwoodard-prog , 
I've fixed this behaviour in the linked issue, will release it as a part of 0.8.8

**Comment by rwoodard-prog** [comment]
Thanks, @renardeinside!  Fantastic work!
