### ISSUE TITLE
submit_run() got an unexpected keyword argument 'email_notifications'

### ISSUE THREAD

**Issue by Microsheep** [databrickslabs/dbx#525]
## Expected Behavior

Job could be launched successfully.

## Current Behavior

When calling `dbx launch test-job --from-assets --trace` with a job deployment definition containing `email_notifications` field, the job fails to launch with the following error: `TypeError: submit_run() got an unexpected keyword argument 'email_notifications'`.

When trying the same job with `dbx deploy test-job` then `dbx launch test-job`, the same definition works fine. 

## Steps to Reproduce (for bugs)

1. Add a job definition with the `email_notifications` field.
2. Deploy the job using `dbx deploy test-job --assets-only`
3. Try to launch the job using `dbx launch test-job --from-assets --trace` 

## Context

Possibly due to the difference in `RunNowLauncher` and `RunSubmitLauncher` ?
https://github.com/databrickslabs/dbx/blob/main/dbx/commands/launch.py#L125-L136

## Your Environment

* dbx version used: 0.7.4
* Databricks Runtime version: 11.1.x-scala2.12

**Comment by renardeinside** [comment]
hi @Microsheep , 
this has been fixed in 0.7.6, could you please upgrade and try out with the new version?

**Comment by Microsheep** [comment]
Hi @renardeinside,

Updating to 0.7.6 did resolve the issue.
Thank you.

Closing this issue.
