### ISSUE TITLE
DBX Debug Option (Local IDE)

### ISSUE THREAD

**Issue by DJeyCodeX** [databrickslabs/dbx#529]
# Local Development
PySpark Code Development in PyCharm IDE.

#DBX Command 
**dbx execute** command is used to run the code from PyCharm over the databricks cluster

Currently, there is no option like **dbx debug** or anything that can be used to debug code (breakpoints) step by step onto PyCharm IDE.

**Comment by renardeinside** [comment]
hi @DJeyCodeX , 
unfortunately interactive remote debugging is not something `dbx` can or will provide. 
The [Spark Connect](https://www.databricks.com/blog/2022/07/07/introducing-spark-connect-the-power-of-apache-spark-everywhere.html) project will deliver this functionality. Please reach out to your account SA for details on preview.
