### ISSUE TITLE
Error thrown when running `dbx deploy ...` cannot find `pydantic` library

### ISSUE THREAD

**Issue by chrimaho** [databrickslabs/dbx#537]
## Current Behavior

Here's what I've done:
1. I have followed the instructions given [here][dbx-python-quickstart-local-environment].
2. I've run the below command, and can successfully query my Databricks environment.
    ```sh
    databricks --profile prd workspace ls /
    ```
4. I've followed the instructions given [here][dbx-yml-reference-deployment] and have successfully constructed my `.yml` file for deploying my workflow. It seems to be correct from my observation.
5. I've executed the below command, and get an error. See below screen shots.
    ```sh
    dbx deploy --deployment-file <path-to-yml-file> --workflows <my-workflow-name> --environment <my-environment> --debug true
    ```

First screen shot. This proves that it can connect successfully. Some parts redacted for privacy.

![image](https://user-images.githubusercontent.com/44449504/199136846-e93aa8e6-fc46-4346-ba6e-cf71ad32a18f.png)

Second screen shot. This shows that there is an issue with `dbx` trying to access the `pydantic` library from my repo root directory?? But `pydantic` is not installed there, it's in my `pipenv` directory: `./venv/Lib/site-packages/pydantic/main.py`

![image](https://user-images.githubusercontent.com/44449504/199137231-5ba6cd9c-b220-43de-a444-0b9828c149d1.png)

## Expected Behavior

When I run the command:

```sh
dbx deploy ...
```

I want it to just run. I don't want to throw an error about the location for where `pydantic` is installed.

## Steps to Reproduce (for bugs)

Due to some privacy around the `.yml` set up, and the Databricks instance that I'm using, I can't provide the exact same files to reproduce the issue.

## Context

* `dbx` version used: **0.7.6**
* `databricks` cli version used: **0.17.3**
* Databricks Runtime version: (not necessary when deploying workflow config files)

[dbx-python-quickstart-local-environment]: https://dbx.readthedocs.io/en/latest/guides/python/python_quickstart/#preparing-the-local-environment
[dbx-yml-reference-deployment]: https://dbx.readthedocs.io/en/latest/reference/deployment/

**Comment by renardeinside** [comment]
hi @chrimaho , 
the validation error usually points to the fact that something isn't correct in the deployment file. 
Could you please share the `deployment.yml` contents? You can delete/mask some specific things.

**Comment by renardeinside** [comment]
The real error is the validation error you see below, it's not relevant to the "file not found" one.

**Comment by chrimaho** [comment]
Hi @renardeinside,

Thank you for your advice.

I have done some troubleshooting, and found that it was because of the `format: MULTI_TASK` key was in the wrong position. Previously it was under the `environments` key, but it should have been under the elements in the `workflows` key.

Thank you for supporting. This issue can now be closed.
