### ISSUE TITLE
`cluster-policy://` is not adjusted with dbx v0.8 and jobs api v2.1

### ISSUE THREAD

**Issue by copdips** [databrickslabs/dbx#538]
## Expected Behavior

`"policy_id": "cluster-policy://xxx"` should be adjusted to `"policy_id": "{the_policy_id}",`

## Current Behavior

Nothing adjusted for policy_id

## Steps to Reproduce (for bugs)

dbx v0.8
jobs api v2.1
with `workflows.job_clusters.new_cluster.policy_id` declareed in deployement file

## Context

it seems that we also need to add the type `JobCluster` during the instance check on:
https://github.com/databrickslabs/dbx/blob/af7fb3f1fca440844f2b77ce6752040ba4d7053a/dbx/api/adjuster/adjuster.py#L154

**Comment by renardeinside** [comment]
good catch, thanks @copdips !
I've fixed this one in the #531 as a part of the tests
