### ISSUE TITLE
dbx sync does not strip the path from the config host

### ISSUE THREAD

**Issue by matthayes** [databrickslabs/dbx#551]
## Expected Behavior

If the `host` in `~/.databrickscfg` has a path, `dbx sync` should still be able to make requests successfully using the correct API URL.

## Current Behavior

The path is not stripped by the `dbx sync` client code, which results in the API path being appended to the already existing path, resulting in an invalid URL and 404 errors.

## Steps to Reproduce (for bugs)

Login to Databricks in the browser and copy the full URL as the `host` in the config.

## Your Environment

* dbx version used:
* Databricks Runtime version:

**Comment by renardeinside** [comment]
Fixed in #552 will be released as part of 0.8.3
