### ISSUE TITLE
The `init_scripts` property cannot be applied for DLT pipelines.

### ISSUE THREAD

**Issue by ericfeunekes** [databrickslabs/dbx#568]
## Expected Behavior

Deploying delta pipeline defined in deployment.conf that includes an init script, init script is property is added to the deployed pipeline.

## Current Behavior

The `init_scripts` property cannot be applied for DLT pipelines. Provided value will be omitted

## Context

Trying to deploy delta pipelines that use clusters having init scripts located in DBFS. Just need the property to be set.

## Your Environment

* dbx version used: 0.8.4
* Databricks Runtime version:

**Comment by renardeinside** [comment]
hi @ericfeunekes , 
this is the limitation of DLT pipelines, not the limitation of `dbx` - please follow [this](https://docs.databricks.com/workflows/delta-live-tables/delta-live-tables-api-guide.html#pipelinesnewcluster) documentation for details.

**Comment by ericfeunekes** [comment]
Thanks for looking into it!
