### ISSUE TITLE
Unable to find a way to connect to Databricks cluster and execute dynamic jobs

### ISSUE THREAD

**Issue by tadas-subonis** [databrickslabs/dbx#579]
Hello,

previously with databricks-connect I was able to do

```
spark = SparkSession.builder.getOrCreate()

```

and run any Spark Job I need to.

At the moment, I cannot see anywhere in the docs how can I do that? I need this feature to be able to launch jobs from my web-server:
 - Obtain reference to sparkContext
 - Build a job flow with custom parameters based on the request
 - Wait until it completes
 - Return the result

**Comment by renardeinside** [comment]
hi @tadas-subonis , 

this is not the way dbx works, unfortunately. You can continue using Databricks Connect, and I would also recommend reaching out to your account Solutions Architect to setup a preview of [Spark Connect](https://www.databricks.com/blog/2022/07/07/introducing-spark-connect-the-power-of-apache-spark-everywhere.html) (which works in the way you've described).

**Comment by tadas-subonis** [comment]
@renardeinside It says that right here that I use dbx...
![image](https://user-images.githubusercontent.com/247218/201704778-acf1bc81-e180-4d6a-a999-b82568b97b13.png)

https://docs.databricks.com/dev-tools/databricks-connect.html

**Comment by renardeinside** [comment]
I don't see a contradiction here to be honest. 

> dbx by Databricks Labs for _local development_ instead of Databricks Connect. 

But your use-case is irrelevant to _local development_, you're looking for a webserver application that can submit code parts to a Spark Session running on Databricks , in your own words:

> I need this feature to be able to launch jobs from my web-server:
Obtain reference to sparkContext
Build a job flow with custom parameters based on the request
Wait until it completes
Return the result

Such pattern is still covered by Databricks Connect. You can achieve close results by using dbx but it will be like using a fork to open a door - possible, but not convenient :) 

Does the explanation above makes sense?

**Comment by tadas-subonis** [comment]
OK. I'll try downgrading first and then check in with SA
