### ISSUE TITLE
Missing console output for Matplotlib plots

### ISSUE THREAD

**Issue by t-schamberger-reply** [databrickslabs/dbx#580]
## Expected Behavior

When executed on a Databricks cluster using `dbx`, the code sample should print the following output:

```
Done
```

## Current Behavior

The code does not print anything, if and only if something is plotted using Matplotlib. Even though no output is shown, the CLI prints ("Command successfully executed").

## Steps to Reproduce (for bugs)

A python script sample containing a plot using Matplotlib is executed using dbx (`dbx execute --cluster-id=xxx-xxx-xxx sample`).

```python
from pyspark.sql import SparkSession
import pandas as pd
import matplotlib.pyplot as plt

spark = SparkSession.builder.appName("dbx-demo").getOrCreate()

df = pd.DataFrame({'lab':['A', 'B', 'C'], 'val':[10, 30, 20]})
plot = df.plot.bar(x='lab', y='val')

print("Done")
```

## Context

On Databricks, I want to execute a PySpark job using dbx, which plots using Matplotlib and saves the figure to dbfs. The simple code sample above reproduces the error. In the cluster stderr logs, I discovered the following error message (not sure if related):

```
ERROR:root:KeyboardInterrupt while sending command.
Traceback (most recent call last):
  File "/databricks/spark/python/lib/py4j-0.10.9.5-src.zip/py4j/java_gateway.py", line 1038, in send_command
    response = connection.send_command(command)
  File "/databricks/spark/python/lib/py4j-0.10.9.5-src.zip/py4j/clientserver.py", line 511, in send_command
    answer = smart_decode(self.stream.readline()[:-1])
  File "/usr/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
KeyboardInterrupt
```

## Your Environment

* dbx version used: 0.8.6
* Databricks Runtime version:  11.3 LTS ML

**Comment by renardeinside** [comment]
hi @t-schamberger-reply , 
i cannot repro this issue with exact same versions. Could you please provide the dbx stacktrace?

Also, if you want to save something to DBFS, it probably should be something like:
```python
from pyspark.sql import SparkSession
import pandas as pd
import matplotlib.pyplot as plt

spark = SparkSession.builder.appName("dbx-demo").getOrCreate()

df = pd.DataFrame({"lab": ["A", "B", "C"], "val": [10, 30, 20]})

plot = df.plot.bar(x="lab", y="val", figsize=(15, 5))
# important - saving step!
fig = plt.gcf()
fig.savefig("/dbfs/books.png")

print("Done")
```

**Comment by renardeinside** [comment]
A way to wrap up the figure content is to use the clear method on `gcf`:

```
plot = df.plot.bar(x="lab", y="val", figsize=(15, 5))
fig = plt.gcf()
fig.savefig("/dbfs/books.png")
fig.clear()
```

**Comment by renardeinside** [comment]
Unrelated to dbx, this is just the way notebook-like interfaces work.
