### ISSUE TITLE
dbx sync repo should check if repo exists first

### ISSUE THREAD

**Issue by matthayes** [databrickslabs/dbx#582]
## Expected Behavior

`dbx sync repo` should produce an easily understandable error message when the target repo does not exist.

## Current Behavior

If the repo doesn't exist, it produces a cryptic error:

```
HTTP 400: {"error_code":"DIRECTORY_PROTECTED","message":"Top-level folder can only contain repos"}
```

## Steps to Reproduce (for bugs)

Run `dbx sync repo -d foo`, where `foo` is a repo that doesn't exist.

## Context

We should be able to use this API below to check if the repo exists:

https://docs.databricks.com/dev-tools/api/latest/repos.html#operation/get-repos

## Your Environment

* dbx version used: 0.8.7
* Databricks Runtime version: N/A

**Comment by renardeinside** [comment]
closed in linked PR, will be delivered in next release.
