### ISSUE TITLE
Cannot run example Java code on Eclipse

### ISSUE THREAD

**Issue by t0mm3h15** [databrickslabs/dbx#583]
## Expected Behavior
    Have below output on Eclipse Console
    // +-----------+----------+---------+--------+
    // |AirportCode|      Date|TempHighF|TempLowF|
    // +-----------+----------+---------+--------+
    // |        PDX|2021-04-03|       64|      45|
    // |        PDX|2021-04-02|       61|      41|
    // |        SEA|2021-04-03|       57|      43|
    // |        SEA|2021-04-02|       54|      39|
    // +-----------+----------+---------+--------+

## Current Behavior
Gets below error
Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
22/11/15 09:36:50 INFO SparkContext: Running Spark version 3.2.1
22/11/15 09:36:50 INFO ResourceUtils: ==============================================================
22/11/15 09:36:50 INFO ResourceUtils: No custom resources configured for spark.driver.
22/11/15 09:36:50 INFO ResourceUtils: ==============================================================
22/11/15 09:36:50 INFO SparkContext: Submitted application: Temps Demo
22/11/15 09:36:50 INFO ResourceProfile: Default ResourceProfile created, executor resources: Map(cores -> name: cores, amount: 1, script: , vendor: , memory -> name: memory, amount: 1024, script: , vendor: , offHeap -> name: offHeap, amount: 0, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
22/11/15 09:36:50 INFO ResourceProfile: Limiting resource is cpu
22/11/15 09:36:50 INFO ResourceProfileManager: Added ResourceProfile id: 0
22/11/15 09:36:50 INFO SecurityManager: Changing view acls to: tshirakawa
22/11/15 09:36:50 INFO SecurityManager: Changing modify acls to: tshirakawa
22/11/15 09:36:50 INFO SecurityManager: Changing view acls groups to: 
22/11/15 09:36:50 INFO SecurityManager: Changing modify acls groups to: 
22/11/15 09:36:50 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users  with view permissions: Set(tshirakawa); groups with view permissions: Set(); users  with modify permissions: Set(tshirakawa); groups with modify permissions: Set()
22/11/15 09:36:51 INFO Utils: Successfully started service 'sparkDriver' on port 63422.
22/11/15 09:36:51 INFO SparkEnv: Registering MapOutputTracker
22/11/15 09:36:51 INFO SparkEnv: Registering BlockManagerMaster
22/11/15 09:36:51 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
22/11/15 09:36:51 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
Exception in thread "main" java.lang.IllegalAccessError: class org.apache.spark.storage.StorageUtils$ (in unnamed module @0x60099951) cannot access class sun.nio.ch.DirectBuffer (in module java.base) because module java.base does not export sun.nio.ch to unnamed module @0x60099951
	at org.apache.spark.storage.StorageUtils$.<init>(StorageUtils.scala:213)
	at org.apache.spark.storage.StorageUtils$.<clinit>(StorageUtils.scala)
	at org.apache.spark.storage.BlockManagerMasterEndpoint.<init>(BlockManagerMasterEndpoint.scala:110)
	at org.apache.spark.SparkEnv$.$anonfun$create$9(SparkEnv.scala:348)
	at org.apache.spark.SparkEnv$.registerOrLookupEndpoint$1(SparkEnv.scala:287)
	at org.apache.spark.SparkEnv$.create(SparkEnv.scala:336)
	at org.apache.spark.SparkEnv$.createDriverEnv(SparkEnv.scala:191)
	at org.apache.spark.SparkContext.createSparkEnv(SparkContext.scala:277)
	at org.apache.spark.SparkContext.<init>(SparkContext.scala:460)
	at org.apache.spark.SparkContext$.getOrCreate(SparkContext.scala:2690)
	at org.apache.spark.sql.SparkSession$Builder.$anonfun$getOrCreate$2(SparkSession.scala:949)
	at scala.Option.getOrElse(Option.scala:189)
	at org.apache.spark.sql.SparkSession$Builder.getOrCreate(SparkSession.scala:943)
	at com.example.demo.SampleApp.main(SampleApp.java:18)

## Your Environment
I have been following below document and on "Step 6: Run the project" I get above error.
https://learn.microsoft.com/en-us/azure/databricks/dev-tools/dbx#eclipse
Im using the "code example" within the document.

Im not quite sure about 2 in "Step 6: Run the project"  
- "In the Run Configurations dialog, expand Java Application, and then click App."
I couldnt fine App in Java Application. So I chose "com.example.demo.SampleApp" instead.
![Screenshot 2022-11-15 094648](https://user-images.githubusercontent.com/117880431/201798822-7d108c01-3b42-406e-b8ad-4a2282e070b0.png)

Thank you!!

* dbx version used: 0.8.6
* Databricks Runtime version: 10.4

**Comment by PaulCornellDB** [comment]
This seems to be an authentication issue. Can you successfully run this code outside of `dbx` otherwise?

**Comment by t0mm3h15** [comment]
Thank you for your reply!
Yes, I was able to run the exact same code successfully with these steps on command prompt. https://learn.microsoft.com/en-us/azure/databricks/dev-tools/dbx#--create-a-dbx-project

**Comment by t0mm3h15** [comment]
Sorry I dont know why this case got closed.... code works successfully in command prompt but it still gets the initial error when trying to run in Eclipse.... could anyone advice please?

**Comment by renardeinside** [comment]
Oops, I was under impression everything worked as per your answer.

**Comment by renardeinside** [comment]
As per traceback above, specifically:
```
Exception in thread "main" java.lang.IllegalAccessError: class org.apache.spark.storage.StorageUtils$ (in unnamed module @0x60099951) cannot access class sun.nio.ch.DirectBuffer (in module java.base) because module java.base does not export sun.nio.ch to unnamed module @0x60099951
```
It seems like you're using JDK 17 instead of JDK 11. Could you please check if you're using the right JDK version?

**Comment by t0mm3h15** [comment]
Sorry for the confusion.
It works when executed via command prompt
It gets the error when executed via Eclipse
I wish to mitigate the error. Thanks!

**Comment by t0mm3h15** [comment]
> As per traceback above, specifically:
> 
> ```
> Exception in thread "main" java.lang.IllegalAccessError: class org.apache.spark.storage.StorageUtils$ (in unnamed module @0x60099951) cannot access class sun.nio.ch.DirectBuffer (in module java.base) because module java.base does not export sun.nio.ch to unnamed module @0x60099951
> ```
> 
> It seems like you're using JDK 17 instead of JDK 11. Could you please check if you're using the right JDK version?

![image](https://user-images.githubusercontent.com/117880431/202098485-17504d88-4c1e-409a-9176-25448fe63fd9.png)
Should be fine

**Comment by renardeinside** [comment]
Make sure you're using the same JDK in the Eclipse and in the shell. Unfortunately this is something unrelated to `dbx`, rather then to the local JDK/Apache Spark setup.

**Comment by t0mm3h15** [comment]
> Make sure you're using the same JDK in the Eclipse and in the shell. Unfortunately this is something unrelated to `dbx`, rather then to the local JDK/Apache Spark setup, therefore I cannot provide much help here.

Just checked JDK in the Eclipse and it was set to 17!
changed it to 11 and rerun the program and it worked! thank you so much!!
