### ISSUE TITLE
named_parameters in python_wheel_task not working

### ISSUE THREAD

**Issue by mullerpeter** [databrickslabs/dbx#589]
## Expected Behavior
Allow `named_parameters` to be passed as an `object` in the deployment configuration file for `python_wheel_task`
## Current Behavior
`named_parameters` parameters have to be passed as an `Array of strings` in the deployment config file, which is not what the databricks create job API endpoint is expecting resulting in an exception when dbx calls the `/2.1/jobs/create` endpoint.
## Steps to Reproduce (for bugs)
Set `named_parameters: ["--name=task", "--data=dbfs:/path/to/data.json"]` in python wheel task and deploy using dbx deploy
## Context
The [databricks REST API reference](https://docs.databricks.com/dev-tools/api/latest/jobs.html#operation/JobsCreate) states the type for `named_parameters` in the `python_wheel_task` as `object`, but dbx enforces `Array of strings`.
## Your Environment
* dbx version used: v0.8.7
* Databricks Runtime version: 11.2

**Comment by renardeinside** [comment]
hi @mullerpeter , 
thanks a lot for opening the issue. I'm in contact with Jobs team to figure out what's the root cause.

**Comment by renardeinside** [comment]
yep, you're right - it should be an object. I'll fix accordingly.

**Comment by jinlow** [comment]
Hi, 
I'm still experiencing this issue in 0.8.7, is there any timeline on a new release for this issue to be resolved?
Thanks!

**Comment by renardeinside** [comment]
hi @jinlow , 
yep, a fix will be released next week as a part of the next version
