### ISSUE TITLE
pipeline_task requires pipeline_id instead of name

### ISSUE THREAD

**Issue by ericfeunekes** [databrickslabs/dbx#591]
## Expected Behavior
When I create a deployment.yml for a job that includes delta pipeline tasks, the delta pipeline tasks should be specified by name

## Current Behavior
the pipeline_task requires a pipline_id. 
## Context
The pipeline_id is impossible to know ahead of time if you're deploying a new delta pipeline. To do this using the current approach, I need to deploy only the delta pipelines, get their pipeline ids, then inject that into the deployment.yml in the correct spot.

dbx gets the pipline_id when it creates or updates the delta pipelines, when compiling from yml, it should inject the pipeline_id to replace the pipeline name that I should be able to specify in the yaml.

## Your Environment

* dbx version used: 0.8.6
* Databricks Runtime version: 11.3

**Comment by renardeinside** [comment]
hi @ericfeunekes , 

Please take a look at [this docs page](https://dbx.readthedocs.io/en/latest/guides/general/delta_live_tables/#referencing-dlt-pipelines-inside-multitask-workflows), specifically at the resolution order.

Isn't it something that covers your request?

**Comment by ericfeunekes** [comment]
Yup. Looks like that covers it!
