### ISSUE TITLE
Allow Service Principals to be owners of workflows

### ISSUE THREAD

**Issue by benedikt-mayer** [databrickslabs/dbx#592]
## Expected Behavior
We use the `permissions` - `access_control_list` to set permissions on workflows.
Since we want to use a service principal to run jobs in production, we also want it to be the owner.
## Current Behavior
Currently, it's not possible to set a service principal as job owner in dbx, even though it's possible in the UI and with the API.
## Steps to Reproduce (for bugs)
Define a service principal as workflow owner.
If you need a more exact error message, I can try to provide it.
## Context
AFAIK it's also not possible to do this via the databricks CLI either, only the API and the UI.
## Your Environment
Azure Databricks, with:
* dbx version used: 0.7.6
* Databricks Runtime version: 10.4 ML LTS

**Comment by renardeinside** [comment]
hi @benedikt-mayer , 

this capability is already supported in dbx.

Please take a look at dbx 0.8+ and [this specific recipe](https://dbx.readthedocs.io/en/latest/reference/deployment/?h=service+principal#managing-the-workflow-as-a-service-principal).

**Comment by benedikt-mayer** [comment]
Oh that's fantastic, thank you!
