### ISSUE TITLE
CalledProcessError when executing "dbx delopy --no-package"

### ISSUE THREAD

**Issue by t0mm3h15** [databrickslabs/dbx#594]
## Expected Behavior
To run with no Error
## Current Behavior
![image](https://user-images.githubusercontent.com/117880431/202644376-055fa6f6-a48f-4a31-b728-fc84d4aad0dc.png)
![image](https://user-images.githubusercontent.com/117880431/202644398-e7cbf244-6ed0-48e9-9c0a-086d4db6abea.png)
## Your Environment
![image](https://user-images.githubusercontent.com/117880431/202644749-24c62b73-90dc-49ed-9512-7b5c2d7ddd84.png)

I've been following below document and encountered this error when excuting "dbx deploy --no-package" as directed in step 4.
https://learn.microsoft.com/en-us/azure/databricks/dev-tools/dbx#--create-a-minimal-dbx-project-for-scala-or-java
Thank you.

* dbx version used: 0.8.4 & (Ive also tried with 0.8.6 but same error)
* Databricks Runtime version: 10.4

**Comment by renardeinside** [comment]
hi @t0mm3h15 , 
most probably issue it's an issue with the packaging/setup. 

Could you please try the following command in the CLI:
```
pip wheel -w dist -e . --prefer-binary --no-deps
```
Would that one work?

**Comment by t0mm3h15** [comment]
Hello @renardeinside, Thank you for your message.

got below error
![image](https://user-images.githubusercontent.com/117880431/202666156-ef35a999-dea0-4cd8-abf6-b83228009737.png)

**Comment by renardeinside** [comment]
The error above means that you don't have `pip` on your PATH. Please check your local environment for details, this error is unrelated to `dbx`.

**Comment by t0mm3h15** [comment]
@renardeinside 
I have added pip to my path on my local environment then encountered this error.... i dont think there was any instructions to have "setup.py" nor "pyproject.toml" in the project folder....
Could you please take a look?
![image](https://user-images.githubusercontent.com/117880431/202698015-6c0c697b-0f66-425f-8a0a-067b1b20ae8f.png)

**Comment by renardeinside** [comment]
@t0mm3h15 , 
as per your project layout I understand that the project is actually a JVM-based one (e.g. Scala/Java)?

**Comment by renardeinside** [comment]
If yes then you'll need to change the build setup since you don't need the python build at all. 
Check this doc for guidance - https://dbx.readthedocs.io/en/latest/guides/jvm/jvm_devloop/

**Comment by t0mm3h15** [comment]
@renardeinside Thank you very much for your reply!

I have being following the document you shared and encountered below problems.

**MVN build errors**
on the azure document it had following command on "deployment,yaml"
![image](https://user-images.githubusercontent.com/117880431/203718178-6c18a311-acf0-4316-b161-89a251d02463.png)
But on the document you shared, it had below command on "deployment.yaml"
![image](https://user-images.githubusercontent.com/117880431/203718351-7477a219-0966-4ba0-9308-ea8c54c829c1.png)
and when i changed it and run deploy command, it gives me "file not found" error.... and Ive echoed python code and it was being error on "mvn clean package". do you know the reason behind this? and when i run "mvn clean package" on its own, it succeeds.

**deployment of JAR file on Azure Databricks**
Ive been rereading the azure document and found following.
![image](https://user-images.githubusercontent.com/117880431/203718783-ab5c2e42-d34d-4fd3-a076-443602f874d3.png)
where should i be deploying the JAR file??
Thank you!

**Comment by renardeinside** [comment]
hi @t0mm3h15 , 
unfortunately we found a bug and this approach is not working yet. Bug resolution is provided but not yet released.
Take a look at this issue for temporary resolution - https://github.com/databrickslabs/dbx/issues/523

**Comment by renardeinside** [comment]
in short - use it like this:

- Specify no build:
```
build:
  no_build: True
``` 
- Provide jar path statically (as `file://...`)
- build and deploy in a chain of steps, e.g.:
```
mvn clean package && dbx deploy
```



[Optional]
Create a `Makefile` and specify the flow like:
```
build-and-deploy:
  mvn clean package
  dbx deploy
```
Then use it:
```
make build-and-deploy
```

**Comment by t0mm3h15** [comment]
@renardeinside Thank you for your reply.

I tried your suggestions but they didnt work and gave me same error as before...
![image](https://user-images.githubusercontent.com/117880431/203925959-37cc83a9-ead1-4b47-85e2-e185c9181c64.png)

this is my deployment.yaml
![image](https://user-images.githubusercontent.com/117880431/203926101-bca50b89-c359-4a4b-ae81-dbc6555a49e2.png)

and this is my project.json
![image](https://user-images.githubusercontent.com/117880431/203926298-0288ecd0-5f44-4c0d-9c25-7da8f21ddf53.png)

do you know what im doing wrong here...?

**Comment by t0mm3h15** [comment]
@renardeinside in addition to above, do you have any clue is to why the error message is showing that "its supposed to be a python project" even though jar file is targeted??
