### ISSUE TITLE
Can't change artifact location

### ISSUE THREAD

**Issue by danricbede** [databrickslabs/dbx#600]
## Expected Behavior
In `project.json`, change `artifact_location` from dbfs to wasbs as per docs: https://dbx.readthedocs.io/en/latest/concepts/artifact_storage/?h=artifact_location

## Current Behavior
Error message on `deploy dbx --no-assets`:
```
Exception: Required location of experiment /Shared/dbx/projects/MyProject doesn't match the project defined one:
         experiment artifact location: dbfs:/dbx/MyProject 
         project artifact location   : wasbs://mycontainer@mystorage.blob.core.windows.net/dbx/MyProject 
```

This happened on the first deploy - this should have been a fresh run.

## Steps to Reproduce (for bugs)
Change `artifact_location` to anything on wasbs

## Your Environment

* dbx version used: 0.8.7
* Databricks Runtime version: 11.3 LTS

**Comment by renardeinside** [comment]
this error means that there is already experiment in /Shared/dbx/projects/MyProject that was at least one deployed. 
As of now, MLflow doesn't support changing experiment artifact locations.
Therefore the simplest solution is to change the working_directory property, e.g. from `/Shared/dbx/projects/MyProject` to `/Shared/dbx/projects/MyProjectInNewLocation`.
