### ISSUE TITLE
Task-level dynamic parameters on dbx launch

### ISSUE THREAD

**Issue by goldstein0101** [databrickslabs/dbx#605]
Hey, why is there not option to pass parameters dynamically for dbx launch.
There is option only for dbx launch --from-assets.

**Comment by renardeinside** [comment]
Hey @goldstein0101 , 

I assume you mean passing **task-level** parameters (since parameters passing in general is supported). 
Unfortunately this is a limitation of Databricks Jobs RunNow API, not of dbx. I'd recommend reaching out to your account SA with this as a feature request.
