### ISSUE TITLE
[FEATURE] Add support for multi-task jobs

### ISSUE THREAD

**Issue by jiri-vinarek** [databrickslabs/dbx#61]
## Expected Behavior

When deployment configuration contains a [job with multiple tasks](https://docs.databricks.com/data-engineering/jobs/index.html?_ga=2.135171313.1582492801.1626868583-172358963.1612518345) a valid configuration is generated and deployed to the cluster.

## Current Behavior

The deployed configuration is invalid for a multi-task job. Libraries (`libraries` JSON object) specified in `job` JSON object have to be moved to each `task` JSON object.

## Your Environment

* dbx version used: 3.1.4
* Databricks Runtime version: 8.4

**Comment by renardeinside** [comment]
Implemented in #78 (thanks a lot @jiri-vinarek ). 

P.S. I've squashed all commits since your initial commit was unsigned (and I don't know how to sign a single existing commit - I've tried to do that and accidentally deleted your PR).
