### ISSUE TITLE
Override parameters in assets launch

### ISSUE THREAD

**Issue by goldstein0101** [databrickslabs/dbx#615]
Hey, so for example in assets based launch where i want to override some parameter which is a file path, where i previously stored it inside deployment.yaml as file:fuse://, but now it overrides it as literal, so i have to pass proper file path, can i achieve that somehow, since path changes based on deployment.

**Comment by JensvandeZande** [comment]
I believe we have related issues. I asked a question in this [discussion.](https://github.com/databrickslabs/dbx/discussions/614)

**Comment by goldstein0101** [comment]
Yeah, when we do dbx deploy, it creates always new directory on dbfs, which means artifacts location changes, so its hard to update it, when passing dynamically with launch, and inside overidding of parameters we have to specify /dbfs/path/to/deployments/hash_of_deployment/config/config.yaml.
Where file:fuse// would to that automatically under the hood.
