### ISSUE TITLE
Compatibility with Databricks features

### ISSUE THREAD

**Issue by yannickRadji** [databrickslabs/dbx#618]
Hi,

Today Databricks push to use clusters with [shared access mode](https://docs.databricks.com/clusters/create-cluster.html#access-mode) to use Unity catalog or table access control.
Nevertheless, DBX requires ML runtimes that aren't compatible with this kind of cluster, concretely if you try to set a cluster with ML runtime and shared access mode you get "_Selected runtime version does not support Legacy Table Acl security mode_". Do you see way to be compatible with shared access mode?

* dbx version used: 0.7
* Databricks Runtime version: 10.4 LTS ML

**Comment by renardeinside** [comment]
hi @yannickRadji , 
please reach out to your account SA and ask for "Improved Shared Clusters", they support dbx.
Another option is to use Single User clusters.
