### ISSUE TITLE
dbx execute failing installing package with private repo

### ISSUE THREAD

**Issue by jfecunha** [databrickslabs/dbx#619]
## Context

We have a poetry environment that is built using private GitHub repositories.
When we run the `dbx execute` it triggers:

```
CalledProcessError: Command 'pip --disable-pip-version-check install --force-reinstall
/.../artifacts/dist/package.whl'
returned non-zero exit status 1.
```
This is generated because it is necessary to do a git clone for the private repo to be installed. Locally we can install this wheel without problems. However, when the package is deployed at the target databricks cluster it shows the previous error.
I suspect that this is because the cluster doesn't have access to git. How can we use the `dbx` execute
 with a git token?

Hope you can help with this. 

Thanks

## Your Environment

* dbx version used: 0.8.7
* Databricks Runtime version: 10.4

**Comment by renardeinside** [comment]
hi @jfecunha , 
you'll need to store your package in a selfhosted pypi repo (e.g. Nexus, Azure DevOps Feed, etc.)
and then configure your cluster init script as follows - https://dbx.readthedocs.io/en/latest/guides/general/dependency_management/#installing-python-packages-from-custom-pypi-repos

**Comment by jfecunha** [comment]
Hi @renardeinside,

Thanks for the feedback. But even using the selfhosted PyPI repo I need that this stays private.
The credentials to access this private pypi repo are passed on the cluster init script?
How can I execute the cluster init script command via dbx?

**Comment by rdpnev** [comment]
We can have a wheel file specified within the yaml file that is installed as a library. I think this can be a workaround!

**Comment by renardeinside** [comment]
hi @rdpnev , 


> The credentials to access this private pypi repo are passed on the cluster init script?

Yes, you can pass them using the environment variables.

> We can have a wheel file specified within the yaml file that is installed as a library. I think this can be a workaround!

This is also an option, but kind of a static one (the approach with the repo is a bit closer to the software development best practices). However your proposal would also work.

**Comment by jfecunha** [comment]
Hi @renardeinside 
The init script that will be used to install the package via custom repository can be uploaded via dbx or that is not possible and is necessary to add that on the databricks UI?
