### ISSUE TITLE
 notebook_task is not supported

### ISSUE THREAD

**Issue by amitca71** [databrickslabs/dbx#631]
## Expected Behavior
support of notebook_task as in the example

## Current Behavior
when executing  notebook_task from the example  it ends with error
## Steps to Reproduce (for bugs)
1. follow: https://dbx.readthedocs.io/en/latest/guides/python/python_quickstart/
2. dbx execute charming-aurora-sample-multitask --task=notebook --cluster-name="amit_single_cluster"
## Your Environment

* dbx version used:
0.8.7
* Databricks Runtime version: 
11.2.x-scala2.12

**Comment by renardeinside** [comment]
hi @amitca71 , 
as stated in dbx limitations, execute works only for `spark_python_task` and `python_wheel_task`. 
If you're developing in a notebook, please use the Databricks Repos, or the [mixed-mode development](https://dbx.readthedocs.io/en/latest/guides/python/devloop/mixed/).
