### ISSUE TITLE
No valid authentication error when using Azure DevOps variable secret for DATABRICKS_TOKEN

### ISSUE THREAD

**Issue by ecuellar2** [databrickslabs/dbx#635]
## Expected Behavior
DATABRICKS_TOKEN value set from variable.
## Current Behavior
Exception: No valid authentication information was provided even though DATABRICKS_TOKEN set as pipeline variable.

## Steps to Reproduce (for bugs)
I'm using Azure DevOps pipeline. Pipeline has DATABRICKS_HOST and DATABRICKS_TOKEN variables defined using steps pipeline, edit, variables. The file azure-pipelines.yml calls dbx deploy and runs successfully when DATABRICKS_TOKEN is visible text variable.

However, I don't want to store the DATABRICKS_TOKEN as visible text in the variable setting.
I then go to pipeline, edit, variables, select the DATABRICKS_TOKEN variable. 
I select "Keep this value secret" and click ok, save. I then run pipeline again and get error:
Exception: No valid authentication information was provided
Is there a way to use DATABRICKS_TOKEN as variable that is treated as secret in pipeline?

## Your Environment
Azure DevOps pipeline 

* dbx version used:
0.8.7

**Comment by renardeinside** [comment]
hi @ecuellar2 

Please make sure that you provide and reference the variables in a proper way, accordingly to the Azure DevOps docs.
Unfortunately this issue is not relevant to `dbx`, therefore I'll close it.

**Comment by ecuellar2** [comment]
Adding one solution I figured out in case anyone has similar issue when using dbx and wanting to store Databricks token as secret. You can store the token in azure key vault then grab the value using AzureKeyVault@1.

Then set a variable named DATABRICKS_TOKEN using the value from the vault, something like this
 vso[task.setvariable variable=DATABRICKS_TOKEN;issecret=false]$(secret_name_from_vault)
