### ISSUE TITLE
HTTPError: 400 Client Error: on dbx launch multitask python_basic template

### ISSUE THREAD

**Issue by j-4** [databrickslabs/dbx#646]
## Expected Behavior

As described here https://dbx.readthedocs.io/en/latest/guides/python/python_quickstart/ and in the README of the generated `python_basic` template repository, I ran the following to set up a project and deploy it:

```bash
dbx init --template=python_basic
dbx deploy {{project_name}}-sample-multitask --assets-only
dbx launch {{project_name}}-sample-multitask --from-assets --trace
```
This should deploy and launch the template multitask job.

## Current Behavior

I get an error message 400:

```bash
HTTPError: 400 Client Error: Bad Request for url: 
https://adb-....azuredatabricks.net/api/2.0/jobs/runs/submit
 Response from server: 
 { 'error_code': 'INVALID_PARAMETER_VALUE',
  'message': 'Shared job cluster feature is not supported in runs/submit API.'}
```
I suspect that this is due to an API change, which requires adaptions in https://github.com/databrickslabs/dbx/blame/main/dbx/templates/projects/python_basic/components/conf/deployment.yml 

Reference for that: https://learn.microsoft.com/en-us/azure/databricks/workflows/jobs/jobs-api-updates#--runs-submit

## Steps to Reproduce (for bugs)
 see above.

## Your Environment

* Deployment on Azure
* dbx version used: [dbx][2022-12-22 10:34:49.730] 🧱 Databricks eXtensions aka dbx, version ~> 0.8.7
* Databricks Runtime version:  as specified in the template for Azure

**Comment by renardeinside** [comment]
hi @j-4 , 
this error and mitigation strategy is described here - https://dbx.readthedocs.io/en/latest/features/assets/#failsafe-behaviour-for-shared-job-clusters
