### ISSUE TITLE
Dbx execute no option to change pip.conf. No possibilty to install from private repo.

### ISSUE THREAD

**Issue by newbidoo** [databrickslabs/dbx#669]
## Expected Behavior

dbx execute allows to set pip.conf to be able to e.g. install repositories from other private pypi repos or e.g. azure devops artifacts
Maybe that's possible and I oversaw that with dbx execute but no luck so far.
So far my workaround is to use dbx deploy which is setting a init script which installs everything on cluster boot.
But it would be very handy for development to also being able to use dbx execut

## Current Behavior

installation step fails because it does not know where to search for the dependencies not in public pypi repos
and has no authentication credentials to access them

## Steps to Reproduce (for bugs)
no bug. missing feature

## Context
minimal abstract example:
dbx execute -> Project A with setup.py > install_requires["...projectB"]
projectB is wheel which was released to private Repo such as Azure Devops 

## Your Environment

* dbx version used: 0.8.7
* Databricks Runtime version: 0.17.3

**Comment by renardeinside** [comment]
hi @newbidoo , 

have you tried following this doc - https://dbx.readthedocs.io/en/latest/guides/general/dependency_management/?h=custom+rep#installing-python-packages-from-custom-pypi-repos?

**Comment by newbidoo** [comment]
> hi @newbidoo ,
> 
> have you tried following this doc - https://dbx.readthedocs.io/en/latest/guides/general/dependency_management/?h=custom+rep#installing-python-packages-from-custom-pypi-repos?

Thx for the response. Yes. I tried that and mentioned that this works with dbx deploy + init script + dbx launch.
But it does not work when using dbx execute. How can configure a pip.conf when using dbx execute? Where do i have to put it or is there any cmd line option to achieve that.

**Comment by renardeinside** [comment]
In short - do the same settings of /etc/pip.conf both in all-purpose and job clusters, the operate in the same sense.

**Comment by newbidoo** [comment]
Works as described in your link.
https://dbx.readthedocs.io/en/latest/guides/general/dependency_management/?h=custom+rep#installing-python-packages-from-custom-pypi-repos

Awesome. Thank you very much :)
