### ISSUE TITLE
__file__ not defined

### ISSUE THREAD

**Issue by senthilkumarimuth** [databrickslabs/dbx#680]
## Expected Behavior 

![image](https://user-images.githubusercontent.com/81953865/215983515-b928d928-8a41-4c8b-b899-6a632a108698.png)

This code to work without any error in databricks

## Current Behavior

__file__ not defined

## Steps to Reproduce (for bugs)

Run the code in databricks, you will see __file__ not defined error

import sys
from pathlib import Path, PurePath
sys.path.append(PurePath(Path(__file__).parents[1]).as_posix())

## Context

When I run the code in local environment it works, but in databricks it is not working. Getting __file__ not defined error i.e NameError

## Your Environment

* dbx version used: 0.8.7
* Databricks Runtime version: 11.3

**Comment by renardeinside** [comment]
hi @senthilkumarimuth , 
Why would you need to get the local file path

**Comment by renardeinside** [comment]
Moreover, `__file__` is neither supported in notebooks for the same reason. 

![Screenshot 2023-02-01 at 12 35 39](https://user-images.githubusercontent.com/4979594/216031977-abb9da07-e9ce-4fe6-9c18-324860a6e2ad.png)

**Comment by senthilkumarimuth** [comment]
Hi Databrickslabs/Dbx,


Thanks for your email. This piece of code is needed in local but same code
needs to be run in databricks.

Why do I need this code in local?

To find a python module in a directory which is located 1 step backwards to
current python file.

**Comment by renardeinside** [comment]
>To find a python module in a directory which is located 1 step backwards to
current python file. 

hi @senthilkumarimuth , 

You shall not use path-based approach for this. Use python modules and libraries, and upload arbitrary files as a part of a package. Here are some relevant docs:
- https://docs.python.org/3/tutorial/modules.html
- https://www.geeksforgeeks.org/python-modules/
- https://dbx.readthedocs.io/en/latest/guides/python/packaging_files/
