### ISSUE TITLE
Accessing secret from github actions in deployment.ymal

### ISSUE THREAD

**Issue by ptaban** [databrickslabs/dbx#688]
Hey, so i have some aws secrets keys as github actions, i deploy workflows via github actions, how can i reference that secret in deployment.file in cluster spark_envs..

So i would ofcourse take it as environment variable inside yaml file for workflow

AWS_KEY: {{secrets.AWS_KEY}}
dbx deploy ...

So how can i refrence now this AWS_KEY inside deployment.yaml.

**Comment by ptaban** [comment]
Could u send me url to some resources for using vault?

**Comment by copdips** [comment]
workflow is in databricks which doesn't have access to CICD secrets.

so, if you're using azure, it will be azure keyvault:
https://learn.microsoft.com/en-us/azure/databricks/security/secrets/secret-scopes#--create-an-azure-key-vault-backed-secret-scope

if you're using aws (I've never used aws), it seems that you only have the default databricks secret scope:
https://docs.databricks.com/security/secrets/secret-scopes.html#create-a-databricks-backed-secret-scope

during the workflow run, both can be read by `dbutils.secrets.get(scope="my-scope", key="my-key")`
https://docs.databricks.com/dev-tools/databricks-utils.html#secrets-utility-dbutilssecrets

**Comment by ptaban** [comment]
But if deployment is done on github runner which has specified secret as env variable and if i refer to variable in deployment.yaml, it could work right?
