### ISSUE TITLE
Support for environment variables in YAML deployment file

### ISSUE THREAD

**Issue by slionelr** [databrickslabs/dbx#693]
## Expected Behavior
Use dbx to deploy workflow tasks while defining a cluster with `instance_profile_arn` value taken from a custom environment variable. The value of this property contains AWS Account ID, which should be treated like a secret and avoid including it in versioned files.

## Current Behavior
There is no support for using environment variables as a value in the YAML file.

## Context
Deploying a workflow with a cluster that uses the specified AWS Role from the deployment file.

## Your Environment
AWS

* dbx version used: 0.8.7
* Databricks Runtime version: 11.3 LTS

## Suggestion
Easy customization with PyYAML package to include a resolver for env variables.
https://stackoverflow.com/a/65414774

**Comment by renardeinside** [comment]
hi @slionelr , 
Env variables are fully supported, please read on it here - https://dbx.readthedocs.io/en/latest/features/jinja_support/#environment-variables
