### ISSUE TITLE
DBX expects a build/package in spite of specifying no_build true

### ISSUE THREAD

**Issue by praj-ias** [databrickslabs/dbx#699]
## Expected Behavior
dbx commands should not initiate a build when the following config is specified on the deployment.yaml
`build:
    no_build: true`

## Current Behavior
Throws an exception and fails

## Steps to Reproduce (for bugs)
Create a simple project with dbx deployment yaml and project json conf
setup credentials
specify the build, noBuild as the intention is to deploy a notebook as is without making a jar / wheel or any package

## Your Environment

* dbx version used: [dbx][2023-02-22 09:08:21.168] 🧱 Databricks eXtensions aka dbx, version ~> 0.8.6
* Databricks Runtime version: 12
[dbx-error.txt](https://github.com/databrickslabs/dbx/files/10805248/dbx-error.txt)

**Comment by renardeinside** [comment]
hi @praj-ias , 
this issue has been already reported and will be fixed in 0.8.8 release (hopefully today).
