### ISSUE TITLE
Retry package being flagged as vulnerability by Mend

### ISSUE THREAD

**Issue by GBBBAS** [databrickslabs/dbx#709]
## Expected Behavior

Mend security scans pass when running their process on our repository.

## Current Behavior

Mend flags the security risk on retry package due to its inclusion of py 1.11 - this issue can be viewed here https://github.com/rtdip/core/issues/77

## Steps to Reproduce (for bugs)

Execute Mend Security scan on a repository using retry.

## Context

It is noted that retry was last maintained in 2016 - a fork of this repository is listed on the retry2 page here https://pypi.org/project/retry2/ - possibly a candidate that can be used to replace retry?

## Your Environment

* dbx version used: 0.8.8
* Databricks Runtime version: 12.1

**Comment by renardeinside** [comment]
Hi @GBBBAS , 
thanks a lot for flagging this one. Not sure what mend is, some research is required. 
There is also a ticket in retry - https://github.com/invl/retry/issues/58

**Comment by GBBBAS** [comment]
Hi @renardeinside - Apologies, I should have mentioned it - it does package scans on repos https://www.mend.io/

**Comment by renardeinside** [comment]
Fixed and released in 0.8.9. Thanks a lot for opening this one @GBBBAS !
