### ISSUE TITLE
Not execute build.commands before deploy when enable inplace_jinja_support 

### ISSUE THREAD

**Issue by nonpool** [databrickslabs/dbx#719]
## Expected Behavior
execute build.commands before deploy when inplace_jinja_support is true

## Current Behavior

not execute build.commands before deploy when inplace_jinja_support is true

## Steps to Reproduce (for bugs)
1. define any build commands in deployment.yml,such as:
```
build:
  commands:
    - "./gradlew clean jar"

```
2. set `inplace_jinja_support` to true in project.json
3. execute `dbx deploy`

## Your Environment

* dbx version used:  [dbx][2023-03-14 16:39:19.386] 🧱Databricks eXtensions aka dbx, version ~> 0.7.6
* Databricks Runtime version:  11.3TLS

**Comment by renardeinside** [comment]
hi @nonpool , 
could you please later versions, e.g. the 0.8.9? This issue was resolved some time ago.

**Comment by nonpool** [comment]
I don't know what to do to make it work 0.0
Maybe this is not a issue
