### ISSUE TITLE
How to install private GitHub repo as a python package in cluster while using DBX?

### ISSUE THREAD

**Issue by Edwardp17** [databrickslabs/dbx#728]
I currently add a private GitHub repository using poetry to my project and am able to use it while developing locally, however, as soon as I want to test my pipelines using DBX (either execute, deploy, or launch) and my working directory is built and installed as a wheel in my remote cluster (all purpose or job) the installation errors out because my Databricks cluster is not able to authenticate the cloning and therefore installation of the previously mentioned private GitHub repository.

Is it possible to configure so that a private repository could be installed as python package in a Databricks cluster with DBX compatibility, and also preferably DB workspace-wide.

* dbx version used: 0.8.10

**Comment by renardeinside** [comment]
hi @Edwardp17 , 

for this you'll need to authenticate in GH on the driver machine, which sounds pretty complex (you can find instructions on how to do this in the GitHub docs). 

Another approach would be to actually store your private package into a private PyPi repository (e.g. Azure Artifacts / Nexus / JFrog). Then you can provide the credentials via pip configurations. This approach is well-described [here](https://dbx.readthedocs.io/en/latest/guides/general/dependency_management/?h=custom+repo#installing-python-packages-from-custom-pypi-repos).

**Comment by Edwardp17** [comment]
Hi @renardeinside thanks for the quick response. A private PyPi repo is probably not feasible in my current situation, unfortunately. I'll look into authenticating GH on the driver machine, but it sounds like it may just be easier to forgo using this private package
