### ISSUE TITLE
Unable to pass dynamic parameter to workflow launch

### ISSUE THREAD

**Issue by sasi143** [databrickslabs/dbx#737]
## Expected Behavior
Using the below command to pass parameters dynamically through the workflow launch
dbx launch <workflow_name> --parameters='{"python_params":["john doe","35"]}' 

## Current Behavior
(test) C:\MyFiles\MLOps\DBX_sample\cicd-sample-project>dbx launch sample-multitask --parameters='{"python_params":["john doe","35"]}' 
[dbx][2023-04-03 13:42:30.133] 💥 Provided parameters payload cannot be parsed as JSON
┌─────────────────────────────── Traceback (most recent call last) ────────────────────────────────┐
│ C:\Users\A405408\Anaconda3\envs\test\lib\runpy.py:196 in _run_module_as_main                     │
│                                                                                                  │
│   193 │   main_globals = sys.modules["__main__"].__dict__                                        │
│   194 │   if alter_argv:                                                                         │
│   195 │   │   sys.argv[0] = mod_spec.origin                                                      │
│ > 196 │   return _run_code(code, main_globals, None,                                             │
│   197 │   │   │   │   │    "__main__", mod_spec)                                                 │
│   198                                                                                            │
│   199 def run_module(mod_name, init_globals=None,                                                │
│                                                                                                  │
│ C:\Users\A405408\Anaconda3\envs\test\lib\runpy.py:86 in _run_code                                │
│                                                                                                  │
│    83 │   │   │   │   │      __loader__ = loader,                                                │
│    84 │   │   │   │   │      __package__ = pkg_name,                                             │
│    85 │   │   │   │   │      __spec__ = mod_spec)                                                │
│ >  86 │   exec(code, run_globals)                                                                │
│    87 │   return run_globals                                                                     │
│    88                                                                                            │
│    89 def _run_module_code(code, init_globals=None,                                              │
│                                                                                                  │
│ C:\Users\A405408\Anaconda3\envs\test\Scripts\dbx.exe\__main__.py:7 in <module>                   │
│                                                                                                  │
│ [Errno 2] No such file or directory:                                                             │
│ 'C:\\Users\\A405408\\Anaconda3\\envs\\test\\Scripts\\dbx.exe\\__main__.py'                       │
│                                                                                                  │
│ C:\Users\A405408\Anaconda3\envs\test\lib\site-packages\dbx\cli.py:227 in entrypoint              │
│                                                                                                  │
│   224                                                                                            │
│   225                                                                                            │
│   226 def entrypoint():                                                                          │
│ > 227 │   app()                                                                                  │
│   228                                                                                            │
│                                                                                                  │
│ C:\Users\A405408\Anaconda3\envs\test\lib\site-packages\typer\main.py:328 in __call__             │
│                                                                                                  │
│ C:\Users\A405408\Anaconda3\envs\test\lib\site-packages\typer\main.py:311 in __call__             │
│                                                                                                  │
│ C:\Users\A405408\AppData\Roaming\Python\Python310\site-packages\click\core.py:1130 in __call__   │
│                                                                                                  │
│ C:\Users\A405408\Anaconda3\envs\test\lib\site-packages\typer\core.py:778 in main                 │
│                                                                                                  │
│ C:\Users\A405408\Anaconda3\envs\test\lib\site-packages\typer\core.py:216 in _main                │
│                                                                                                  │
│ C:\Users\A405408\AppData\Roaming\Python\Python310\site-packages\click\core.py:1655 in invoke     │
│                                                                                                  │
│ C:\Users\A405408\AppData\Roaming\Python\Python310\site-packages\click\core.py:920 in             │
│ make_context                                                                                     │
│                                                                                                  │
│ C:\Users\A405408\AppData\Roaming\Python\Python310\site-packages\click\core.py:1378 in parse_args │
│                                                                                                  │
│ C:\Users\A405408\AppData\Roaming\Python\Python310\site-packages\click\core.py:2360 in            │
│ handle_parse_result                                                                              │
│                                                                                                  │
│ C:\Users\A405408\AppData\Roaming\Python\Python310\site-packages\click\core.py:2322 in            │
│ process_value                                                                                    │
│                                                                                                  │
│ C:\Users\A405408\Anaconda3\envs\test\lib\site-packages\typer\main.py:988 in wrapper              │
│                                                                                                  │
│ C:\Users\A405408\Anaconda3\envs\test\lib\site-packages\dbx\callbacks.py:83 in                    │
│ launch_parameters_callback                                                                       │
│                                                                                                  │
│   80 │   │   │   json.loads(value)                                                               │
│   81 │   │   except json.JSONDecodeError as e:                                                   │
│   82 │   │   │   dbx_echo(":boom: Provided parameters payload cannot be parsed as JSON")         │
│ > 83 │   │   │   raise e                                                                         │
│   84 │   │                                                                                       │
│   85 │   │   return value                                                                        │
│   86                                                                                             │
│                                                                                                  │
│ C:\Users\A405408\Anaconda3\envs\test\lib\site-packages\dbx\callbacks.py:80 in                    │
│ launch_parameters_callback                                                                       │
│                                                                                                  │
│   77 def launch_parameters_callback(_, value: str) -> Optional[str]:                             │
│   78 │   if value:                                                                               │
│   79 │   │   try:                                                                                │
│ > 80 │   │   │   json.loads(value)                                                               │
│   81 │   │   except json.JSONDecodeError as e:                                                   │
│   82 │   │   │   dbx_echo(":boom: Provided parameters payload cannot be parsed as JSON")         │
│   83 │   │   │   raise e                                                                         │
│                                                                                                  │
│ C:\Users\A405408\Anaconda3\envs\test\lib\json\__init__.py:346 in loads                           │
│                                                                                                  │
│   343 │   if (cls is None and object_hook is None and                                            │
│   344 │   │   │   parse_int is None and parse_float is None and                                  │
│   345 │   │   │   parse_constant is None and object_pairs_hook is None and not kw):              │
│ > 346 │   │   return _default_decoder.decode(s)                                                  │
│   347 │   if cls is None:                                                                        │
│   348 │   │   cls = JSONDecoder                                                                  │
│   349 │   if object_hook is not None:                                                            │
│                                                                                                  │
│ C:\Users\A405408\Anaconda3\envs\test\lib\json\decoder.py:337 in decode                           │
│                                                                                                  │
│   334 │   │   containing a JSON document).                                                       │
│   335 │   │                                                                                      │
│   336 │   │   """                                                                                │
│ > 337 │   │   obj, end = self.raw_decode(s, idx=_w(s, 0).end())                                  │
│   338 │   │   end = _w(s, end).end()                                                             │
│   339 │   │   if end != len(s):                                                                  │
│   340 │   │   │   raise JSONDecodeError("Extra data", s, end)                                    │
│                                                                                                  │
│ C:\Users\A405408\Anaconda3\envs\test\lib\json\decoder.py:355 in raw_decode                       │
│                                                                                                  │
│   352 │   │   try:                                                                               │
│   353 │   │   │   obj, end = self.scan_once(s, idx)                                              │
│   354 │   │   except StopIteration as err:                                                       │
│ > 355 │   │   │   raise JSONDecodeError("Expecting value", s, err.value) from None               │
│   356 │   │   return obj, end                                                                    │
│   357                                                                                            │
└──────────────────────────────────────────────────────────────────────────────────────────────────┘
JSONDecodeError: Expecting value: line 1 column 1 (char 0)

## Steps to Reproduce (for bugs)
Step-1: "dbx init"
Step-2: Colud "azure"
step-3: Update deployment.yml
'''
custom:
  basic-cluster-props: &basic-cluster-props
    spark_version: "10.4.x-cpu-ml-scala2.12"

  basic-static-cluster: &basic-static-cluster
    new_cluster:
      <<: *basic-cluster-props
      num_workers: 1
      node_type_id: "Standard_DS3_v2"

environments:
  default:
    workflows:
      - name: "sample-multitask"
        job_clusters:
          - job_cluster_key: "default"
            <<: *basic-static-cluster
        tasks:
          - task_key: "etl"
            job_cluster_key: "default"
            spark_python_task:
              python_file: "file://cicd_sample_project/tasks/sample_etl_task.py"
              # parameters: [ "--conf-file", "file:fuse://conf/tasks/sample_etl_config.yml" ]
 """    
## Your Environment
Testing through Anaconda prompt in Windows10 machine
* python version: 3.10.8 
* dbx version used: 0.8.10
* Databricks Runtime version: "10.4.x-cpu-ml-scala2.12"

**Comment by sasi143** [comment]
Any Update here?

**Comment by renardeinside** [comment]
hi @sasi143 , 
what kind of shell do you use? It seems to me that it might add some escaping and because of that the JSON is not recognised.

**Comment by sasi143** [comment]
> hi @sasi143 , what kind of shell do you use? It seems to me that it might add some escaping and because of that the JSON is not recognised.

Yes, After debugging the issue with the Databricks team, found that we are passing as below makes working

**Not-working:** '{"notebook_params":{"name":"john doe","age":"35"}}'
**Working:** {\"notebook_params\":{\"name\":\"john_doe\",\"age\":\"35\"}}

In working mode again if we pass "john_doe" as "john doe" having a space between words makes a similar issue

Tested same from Windows 10 - Conda Prompt & Powershell

**Comment by sasi143** [comment]
**New observation:** In PowerShell Core it's working fine without any issue, the only problem in Windows cmd & Powershell. Can someone help here

**Comment by copdips** [comment]
I cannot test now, but take a try on backtick instead of backslask with powershell

**Comment by sasi143** [comment]
> I cannot test now, but take a try on backtick instead of backslask with powershell

Not working, same issue

**Comment by renardeinside** [comment]
hi @sasi143 , 

unfortunately this problem is unrelated to dbx - it's about how powershell handles the inputs. Probably there is a parameter that allows PS to properly pass the strings without adding any extra to them. I would recommend asking a specialist on Powershell to provide some PoV.
