### ISSUE TITLE
[BUG] Custom tags are being replaced during deployment

### ISSUE THREAD

**Issue by mshtelma** [databrickslabs/dbx#74]
## Expected Behavior
DBX created/updates a job def. with custom tags exactly as they were specified in the deployment.json

## Current Behavior
DBX changes some custom tags if their value is the same as project dir.

## Steps to Reproduce (for bugs)
Create custom tag with the value the same to the project dir

**Comment by renardeinside** [comment]
Implemented in #81 via strict path policy, will be released in 0.2.0
