### ISSUE TITLE
The term 'dbx' is not recognized as the name of a cmdlet, function, script file, or operable program

### ISSUE THREAD

**Issue by Rohit-1989** [databrickslabs/dbx#741]
## Expected Behavior
After successful installation of dbx package , on running the command dbx --version , it should give the version name.

## Current Behavior
Getting error - "The term 'dbx' is not recognized as the name of a cmdlet, function, script file, or operable program"

## Steps to Reproduce (for bugs)
Install dbx package
pip install dbx

Check version
dbx --version

## Context
![Error](https://user-images.githubusercontent.com/83412583/230067052-94449f6a-f00e-476d-9a16-7eb4450c2485.JPG)

## Your Environment
Visual Code
Python 3.11
* dbx version used: 0.8.10
* Databricks Runtime version:

**Comment by renardeinside** [comment]
hi @Rohit-1989 , 

my only assumption would be that your PS is misconfigured and it doesn't pickup the dbx executable from the PATH env variable.
