### ISSUE TITLE
Cannot overwrite an exisitng dbt job with a with a Service Principal

### ISSUE THREAD

**Issue by DRUKSTOP1** [databrickslabs/dbx#744]
## Expected Behavior
To be able to deploy and overwrite an existing dbt databricks job

## Current Behavior
Receiving an error that the service principal does not exist

## Steps to Reproduce (for bugs)
1. Deploy a dbt job with or without a service principal. 
2. When updating the existing job, ensure that a service principal is provided. 

## Context
{ 'error_code': 'RESOURCE_DOES_NOT_EXIST',
'message': 'Principal: '
                    'UserName(service-principal://NAME_OF_MY_SP) '
                    'does not exist'}

## Your Environment

* dbx version used: 0.7.5
* Databricks Runtime version: Standard runtime engine, 12.2.x cluster

**Comment by renardeinside** [comment]
hi @DRUKSTOP1 , 
Named properties resolution with references is supported with[ dbx >0.8.X](https://dbx.readthedocs.io/en/latest/features/named_properties/#reference-based-approach), you're using 0.7.5 - please update.
