### ISSUE TITLE
dbx fails due to pydantic 2.0a version

### ISSUE THREAD

**Issue by sercandogan** [databrickslabs/dbx#756]
## Steps to Reproduce (for bugs)
Any dbx command in cli.
## Context
Hello dbx 0.8.10 fails due to pydantic 2.0. I saw that requirement boundaries includes [pydantic 2.0](https://github.com/databrickslabs/dbx/blob/main/setup.py#L24). I think it shouldn't be equal or less than 2.0.

When I run `dbx`, it fails with
```pydantic.errors.PydanticUserError: If you use `@root_validator with pre=False (the default) you MUST specify `skip_on_failure=True`.```

The Address for exception: https://github.com/databrickslabs/dbx/blob/main/dbx/models/workflow/common/new_cluster.py#L12

I am happy to contribute with your suggestion to fix current error.

## Your Environment
MacOS m1
Python 3.8.12
pip 22.2.2
* dbx version used: 0.8.10

**Comment by renardeinside** [comment]
hi @sercandogan , 
I believe to avoid issues with pydantic we shall simply stick to a compatible version of `pydantic` to avoid much code rewrite. Would that be a sufficient fix in your opinion?
