### ISSUE TITLE
--no-rebuild legacy vs different environments

### ISSUE THREAD

**Issue by tonkolviktor** [databrickslabs/dbx#758]
## Context
In dev we use build and in prod not, but we'd like to use the same yaml configuration.
Without the --no-rebuild flag it's unclear how this could be achieved.

## Expected Behavior
Being able to specify different build behaviors in different environments.

Could you please not remove --no-rebuild until such a configuration is possible in the yaml.
(If it's already possible please let me know in https://dbx.readthedocs.io/en/latest/features/build_management/ i could find nothing regarding this.)

Thanks,

**Comment by renardeinside** [comment]
Hi @tonkolviktor 
Have you tried using if-else conditioning with Jinja? 

i.e. (not fully sure on the syntax, approx. written by Jinja docs):

```yaml
build:
   {% if env["IS_PROD"] %}
      no_build: True
    {%endif%}
```

You can enable this functionality as described [here](https://dbx.readthedocs.io/en/latest/features/jinja_support/?h=jinja).
Hope this helps. Please feel free to re-open the issue if additional support is required.

**Comment by tonkolviktor** [comment]
ah thanks!
