### ISSUE TITLE
Files in Workspace is not supported in runtimes below 11.2

### ISSUE THREAD

**Issue by ssabzevari-antuit** [databrickslabs/dbx#759]
## Expected Behavior
Deploying the pipeline to workspace when the runtime is less than 11.2

## Current Behavior
Errors out with the message

 { 'error_code': 'FEATURE_DISABLED',
  'message': 'Files in Workspace is not supported for Spark Version: '
             '10.4.x-cpu-ml-scala2.12. Please use 11.2 or above.'}

## Steps to Reproduce (for bugs)
Try to deploy jobs that use Git as source of the task

build:
  no_build: true
environments:
  default:
    workflows:
    - name: CompiledVersionPipelineTesting
      tasks:
      - task_key: ts_pipeline
        description: TS end-to-end pipeline      
        job_cluster_key: Job_cluster
        libraries: *libraries
        spark_python_task:
          python_file: "/tutorials/some_python_file.py"
          parameters:
          - "--input"
          - some_datea.parquet
          - "--output"
          - out_put.parquet
          source: GIT
      job_clusters:
      - job_cluster_key: Job_cluster 
        new_cluster: *BasicCPUCluster
      git_source:
        git_url: https://github.com/<your repo>
        git_provider: gitHub
        git_branch: develop  
      format: MULTI_TASK
      
## Context
When using UI and runtime 10.4 LTS ML you are able to use Git to setup tasks for python files and it works fine. However, when you try to do the same using dbx deploy it fails with error mentioned above.

## Your Environment
* dbx version used: 0.8,7
* Databricks Runtime version: 10.4 LTS ML

**Comment by renardeinside** [comment]
hi @ssabzevari-antuit ,
the error is not related to dbx, therefore I won't be able to provide a good support here. Please reach out to your account team for explanations on the topic of files-in-repos support.
