### ISSUE TITLE
Working on multiple workspaces(databricks accounts)

### ISSUE THREAD

**Issue by ptaban** [databrickslabs/dbx#762]
Hey, is the only way to run databricks workflow(inference pipeline for example) from dev -> staging -> prod,
to have same workflow in deployment just under three different environments?

**Comment by renardeinside** [comment]
Hey, 
yes, this is correct. Please note that you can use YAML anchors and substitutions, together with Jinja capabilities to avoid copying the definitions from one environment spec to another.
