### ISSUE TITLE
[FEATURE] Add support for environment variable substitution in deployment.yaml or deployment.json

### ISSUE THREAD

**Issue by dumontvi** [databrickslabs/dbx#77]
## Expected Behavior
Given a deployment file like:
![Screen Shot 2021-09-09 at 3 32 24 PM](https://user-images.githubusercontent.com/20103067/132751082-9c2ec9e6-3cb6-4c29-b8ca-0d4feb6dff46.png)

it would be beneficial to enable environment variable substitution during runtime like `${{ALERT_EMAIL}}` in the image above. The environment variable can be set by the CICD tool like `DATABRICKS_TOKEN` or `DATABRICKS_HOST` that dbx supports. 
 
## Current Behavior
No support for env variables and everything has to be pre-set in deployment files

## Your Environment

* dbx version used: 0.1.6
* Databricks Runtime version: 8.3

**Comment by renardeinside** [comment]
implemented in #80, will be released in 0.2.1. thanks a lot for your contribution @dumontvi !
