### ISSUE TITLE
dbx execute does not use new context for execution

### ISSUE THREAD

**Issue by ericfeunekes** [databrickslabs/dbx#772]
## Expected Behavior
1. Run `dbx execute ...`
2. Change source files
3. Run `dbx execute ...`

At step 3, the new code change should be run on the interactive cluster

## Current Behavior

Code changes are not picked up. Instead I need to restart the cluster, then the new code changes are picked up when run

## Steps to Reproduce (for bugs)
On an interactive cluster (DBR 13)
1. Run `dbx execute ...`
2. Change source files
3. Run `dbx execute ...`

## Context

The job type is `spark_python_task`. It runs a python file that is part of a larger package, which includes all job/pipeline source code.

## Your Environment

* dbx version used: 0.8.13
* Databricks Runtime version: 13.0

**Comment by flori567** [comment]
I can confirm the issue. Developing code on interactive clusters is nearly impossible like that.

Did this come up in one of the new releases, so we could get back to some earlier version?

**Comment by tarique-msci** [comment]
I am having the same issue. Also started seeing this on DBR 13

**Comment by renardeinside** [comment]
Hi everyone on this thread, 
I'm verifying the way to fix the issue, please stay tuned for updates. 
In the meantime the easiest fix is to use any version below 13.X

**Comment by Edwardp17** [comment]
Was this resolved? I came across this bug today which led me to this issue.

**Comment by renardeinside** [comment]
hi @Edwardp17 
this issue has been resolved in dbx 0.8.17 - could you please upgrade the version and take a look?

**Comment by Edwardp17** [comment]
Apologies for not checking - that did the trick, thanks!

**Comment by Edwardp17** [comment]
Apologies for not checking - that did the trick, thanks!
