### ISSUE TITLE
dbx fails to install a package with extension (ruamel-yaml + jinja2)

### ISSUE THREAD

**Issue by snovik75** [databrickslabs/dbx#781]
## Expected Behavior
All works smoothly and a package is installed

## Current Behavior
![image](https://github.com/databrickslabs/dbx/assets/26685119/e40f59e2-ccb9-4396-8cf8-aa4a7c9580db)

## Steps to Reproduce (for bugs)
I have the package set up in the pyproject.toml
![image](https://github.com/databrickslabs/dbx/assets/26685119/32ab343d-3908-4a54-b469-5d4be0e8abe0)

## Context
Package ruamel-yaml has a required extension as per screenshot above however the 

## Your Environment

* dbx version used: 0.8.14
* Databricks Runtime version: 12.2

**Comment by renardeinside** [comment]
Hi @snovik75 , 

the issue is unrelated to dbx. Your package string is wrong - package `ruamel-yaml` doesn't exist, it's called "[ruamel.yaml](https://pypi.org/project/ruamel.yaml/)", therefore the dependency string should look like:
```
"ruamel.yaml" = {extras = ["jinja2"], version = "^0.17.26"}
```
