### ISSUE TITLE
[Question] how to get github environment variable in deployment file during CD (dbx deploy ....)

### ISSUE THREAD

**Issue by shrinidhikulkarnitw** [databrickslabs/dbx#811]
## Expected Behavior
I am trying to access environment variables from github environments in deployment file during CD pipeline in github action.  I have stored env variable under github environment variable. But after successful dbx deployment, value of variable should show up in the cluster environment variables. 
## Current Behavior
Currently its not assigning any value to the env variable after successful deployment to cluster environment variable 
## Steps to Reproduce (for bugs)
I am trying to assign a variable under spark_env_vars in deployment file as shown below

<img width="624" alt="image" src="https://github.com/databrickslabs/dbx/assets/95338830/2ac56fe6-e275-40ed-99fe-52b0e5f8fb8e">

and using this cluster config in workflow config 

<img width="499" alt="image" src="https://github.com/databrickslabs/dbx/assets/95338830/4808aed1-903d-4641-9a44-443293f2c2af">

and this is how i stored env variable in github 

<img width="823" alt="image" src="https://github.com/databrickslabs/dbx/assets/95338830/03f5761d-a9a8-4c22-acf2-4d6f32c84863">

but after deployment, env variable value didn't showed up 

<img width="1177" alt="image" src="https://github.com/databrickslabs/dbx/assets/95338830/daab42ab-d77b-4c40-8cb9-aec1b4be91d7">
 
is i am missing anything here? can you folks please help me here.

## Your Environment
DEV
* dbx version used: latest version
* Databricks Runtime version:  11.3

**Comment by renardeinside** [comment]
hi @shrinidhikulkarnitw
Could you please verify that the variable is correctly set and **visible** outside of dbx inside the  CI/CD pipeline? 

e.g. by testing it via echo $SAMPLE_VARIABLE 

Asking because it seems like there is no value passed into dbx deploy command, therefore it fails to assign it.
