### ISSUE TITLE
Authentication on azure blob storage

### ISSUE THREAD

**Issue by panoptikum** [databrickslabs/dbx#812]
Hey Folks,

I'm having trouble to upload an artifact to a blob storage on azure. I think it is a simple authentication problem, but I can't figure it out and the documentation regarding this problem is sparse. I would very much appreciated a hint.

My project.json looks like the following:

`{
    "environments": {
        "default": {
            "profile": "DEFAULT",
            "storage_type": "mlflow",
            "properties": {
                "workspace_directory": "/Shared/dbx/appfigures-wasbs2",
                "artifact_location": "wasbs://artifact@xxxxx.blob.core.windows.net/appfigures"
            }
        }
    },
    "inplace_jinja_support": false,
    "failsafe_cluster_reuse_with_assets": false,
    "context_based_upload_for_execute": false
}`

and the error is as follows:

`DefaultAzureCredential failed to retrieve a token from the included credentials.
Attempted credentials:
        EnvironmentCredential: EnvironmentCredential authentication unavailable. Environment variables are not fully configured.
Visit https://aka.ms/azsdk/python/identity/environmentcredential/troubleshoot to troubleshoot this issue.
        ManagedIdentityCredential: ManagedIdentityCredential authentication unavailable, no response from the IMDS endpoint.
        SharedTokenCacheCredential: Azure Active Directory error '(invalid_grant) AADSTS700082: The refresh token has expired due to inactivity. The token was issued on 2023-01-03T10:17:27.4356604Z and was inactive 
for 90.00:00:00.
Trace ID: xxxx
Correlation ID: xxxx
Timestamp: 2023-07-12 13:36:20Z'
Content: {"error":"invalid_grant","error_description":"AADSTS700082: The refresh token has expired due to inactivity. The token was issued on 2023-01-03T10:17:27.4356604Z and was inactive for 90.00:00:00.\r\nTrace ID:xxxxx\r\nCorrelation ID: xxxxxf\r\nTimestamp: 2023-07-12 13:36:20Z","error_codes":[700082],"timestamp":"2023-07-12 13:36:20Z","trace_id":"2103a8ee-020d-40d4-8348-24dd037c0e00","correlation_id":"ca09f558-dc98-484d-b21c-a36501e08c1f","error_uri":"https://login.microsoftonline.com/error?code=700082"}
To mitigate this issue, please refer to the troubleshooting guidelines here at https://aka.ms/azsdk/python/identity/defaultazurecredential/troubleshoot.
DefaultAzureCredential failed to retrieve a token from the included credentials.
Attempted credentials:
        EnvironmentCredential: EnvironmentCredential authentication unavailable. Environment variables are not fully configured.
Visit https://aka.ms/azsdk/python/identity/environmentcredential/troubleshoot to troubleshoot this issue.
        ManagedIdentityCredential: ManagedIdentityCredential authentication unavailable, no response from the IMDS endpoint.
        SharedTokenCacheCredential: Azure Active Directory error '(invalid_grant) AADSTS700082: The refresh token has expired due to inactivity. The token was issued on 2023-01-03T10:17:27.4356604Z and was inactive 
for 90.00:00:00.`

Thanks again for this great tool!

**Comment by renardeinside** [comment]
hi @panoptikum , 

it seems like you're not authenticated to Azure, or the token is expired, or you don't have permissions to upload/download on the provided `wasbs` path. Could you please try first:
```
az login 
```
And then:
```
dbx <some command>
```
?

**Comment by renardeinside** [comment]
hi @panoptikum ,
the error you're seeing is unrelated to azure storage auth now - it says that there is no deployment file.
 
Please pre-read the [quickstart doc](https://dbx.readthedocs.io/en/latest/guides/python/python_quickstart/?h=quick), as well as the [artifact storage ](https://dbx.readthedocs.io/en/latest/concepts/artifact_storage/)explanation for clear picture on how azure storage is used with dbx.

I'll close the ticket as of now, since the root problem has nothing to do with auth on Azure blob.

**Comment by panoptikum** [comment]
Hi @renardeinside ,
Sorry I made a mistake. I called the command on the wrong folder where no dbx project resides. I will give an update tomorrow.

**Comment by renardeinside** [comment]
hi @panoptikum , 

now I see the issue, but it's still unrelated to dbx (at least as it seems to me). 

My guess would be that you have some old env variables that actually prevent the usage of the up-to-date token that you obtain from:
```
az login
```

Could you please verify that after running `az login` you can perform any operations on the ADLS container mentioned in the `.dbx/project.json`? e.g. run this command:
```
az storage blob directory list -c MyContainer -d DestinationDirectoryPath --account-name MyStorageAccount
```

**Comment by panoptikum** [comment]
Hi @renardeinside ,

Yes, I completely agree that this is issue is not related to dbx, but I could not figure it out by myself. You're hint was very good. Only after I have set the environment variable AZURE_STORAGE_AUTH_MODE to "login" the listing of the directory was successful. This however did not lead that dbx or the azure python sdk picked this way of authentication up. I was still getting this error:

```
DefaultAzureCredential failed to retrieve a token from the included credentials.
Attempted credentials:
Visit https://aka.ms/azsdk/python/identity/environmentcredential/troubleshoot to troubleshoot this issue.
        ManagedIdentityCredential: ManagedIdentityCredential authentication unavailable, no response from the IMDS endpoint.
        SharedTokenCacheCredential: Azure Active Directory error '(invalid_grant) AADSTS700082: The refresh token has expired due to inactivity. The token was issued on 2023-01-03T10:17:27.4356604Z and was inactive for 90.00:00:00.
Trace ID: eb55cb82-91e0-4394-85ea-0dd5be7e0600
Timestamp: 2023-07-19 08:15:42Z'
```

But I was consulting the mentioned address (https://aka.ms/azsdk/python/identity/environmentcredential/troubleshoot) again and when I set the environment variables AZURE_USERNAME and AZURE_PASSWORD then it seems to work as expected. I will play a bit more around during the day, but I'm optimistic.

**Comment by renardeinside** [comment]
Unfortunately I don't have much expertise on Azure auth CLI setup (I've always used standard `az login` and it worked for me in 100% of cases).

What I know for sure is that dbx uses standard Azure auth mechanism under the hood, exactly the same as in`az` CLI. 

Therefore any Azure auth related message is coming from this CLI/API and is just proxied via dbx. 

Make sure that you can perform the following actions with pure `az` cli:
- list the artifact directory
- upload a file to it
- download a file from it

If the issue on `az` level persists, please raise an issue in the relevant repo - https://github.com/Azure/azure-cli
If you can perform the actions above in `az` CLI and cannot do the same with `dbx` - please reopen this ticket.
