### ISSUE TITLE
databricks rest api weird missing parameter error

### ISSUE THREAD

**Issue by blankenshipc** [databrickslabs/dbx#830]
## Expected Behavior
create new cluster

## Current Behavior
When using parmaters:
autoscale:
              min_workers: 3
              max_workers: 10
              mode: "ENHANCED"

in deployment file, receive:

400 error for dlt pipeline creation 

HTTPError: 400 Client Error: Bad Request for url: 
***api/2.0/jobs/create
 Response from server: 
 { 'error_code': 'INVALID_PARAMETER_VALUE',
  'message': 'Cluster validation error: Missing required field: '
             'settings.cluster_spec.new_cluster.size'}

## Steps to Reproduce (for bugs)

create deployment file with dlt pipeline workflow and autoscale cluster.

## Your Environment

* dbx version used:
* Databricks Runtime version: 12.2

**Comment by renardeinside** [comment]
hi @blankenshipc , 

If you're deploying a DLT pipeline, you should pass the property `workflow_type: pipeline`, otherwise it tries to deploy it as a job and therefore fails.
