### ISSUE TITLE
databricks-cli installation needs to be updated to the new version

### ISSUE THREAD

**Issue by IamSandeepGunda** [databrickslabs/dbx#837]
## Expected Behavior
╰─ databricks -v
Databricks CLI v0.202.0

## Current Behavior
╰─ databricks -v                       
Version 0.17.7

## Steps to Reproduce (for bugs)
`databricks -v`

## Context
Databricks has launched a new standalone CLI which has a version v0.202.0. This is upgraded with a lot of new features from Databricks. 

However, dbx installs `databricks-cli` versioned at 0.17.7 which databricks has now declared as **Legacy**. 

The current situation creates a mismatched environment where there are 2 databricks-cli running side by side on a poetry setup. The poetry environment has the legacy CLI, whereas outside poetry there's the manually installed new CLI. 

DBX should adopt the new CLI and have a unified experience. 

## Your Environment

* dbx version used: 0.8.18
* Databricks Runtime version: NA

**Comment by renardeinside** [comment]
hi @IamSandeepGunda , 
unfortunately the databricks-cli is a hard-pinned dependency of dbx. I would recommend installing dbx inside a python virtualenv (e.g. in conda env or in `venv` or in poetry env) to avoid mixing the main CLI and the legacy CLI which we're dependent on.
