### ISSUE TITLE
[FEATURE] Add support for multi-task jobs inside dbx execute

### ISSUE THREAD

**Issue by niall-turbitt** [databrickslabs/dbx#84]
## Expected Behavior
Running a multi-task job is currently (dbx=0.2.0) only possible using dbx deploy followed by dbx launch. As such, to run a multi-task job requires specifying a new cluster to be created and launched for each task. Given that dbx execute allows execution of standard jobs against existing clusters, one would expect the ability to run a multi-task job against an existing cluster.

## Current Behavior
Multi-task jobs are only possible with dbx using dbx launch. Desired behaviour is that this would be possible with dbx execute also.

## Steps to Reproduce (for bugs)
Configure a job with multiple tasks and attempt to execute against an existing cluster using dbx execute

## Environment
* dbx version used: 0.2.0
* Databricks Runtime version: DBR 9.0 ML

**Comment by renardeinside** [comment]
Addressed in the linked PR, will be released as a part of 0.6.6
