### ISSUE TITLE
DBX execute/launch command issue - issue getting the result

### ISSUE THREAD

**Issue by Abhendu21** [databrickslabs/dbx#85]
## Expected Behavior

To run execute/launch command and to get the result

## Current Behavior

I am trying to implement databricks cicd.
when I am running the execute/launch command, I am getting the following error. could you please help me to solve the issue. Also where can I learn about the entrypoint and the python coding that is done inside it. I need to get output of the launch and execute shown in the output. currently it is showing the following error -

File "C:\Users\AChowdhury1\02_Python_Executables\lib\site-packages\mlflow\utils\rest_utils.py", line 184, in verify_rest_response
raise MlflowException("%s. Response body: '%s'" % (base_msg, response.text))
mlflow.exceptions.MlflowException: API request to endpoint was successful but the response body was not in a valid JSON format. Response body: '<!doctype html><html><head><meta charset="utf-8"/><meta http-equiv="Content-Language" content="en"/><title>Databricks - Sign In</title><meta name="viewport" content="width=960"/><link rel="icon" type="image/png" href="/favicon.ico"/><meta http-equiv="content-type" content="text/html; charset=UTF8"/><link rel="icon" href="favicon.ico"></head><body class="light-mode"><uses-legacy-bootstrap><div id="login-page"></div></uses-legacy-bootstrap><script src="login/login.6018450d.js"></script></body></html>'

## Your Environment
Windows
* dbx version used:
DataBricks eXtensions aka dbx, version ~> 0.2.0
* Databricks Runtime version: 
8.3 (includes Apache Spark 3.1.1, Scala 2.12)

**Comment by renardeinside** [comment]
Hi @Abhendu21 , 

how do you configure the databricks token & host - via environment variables, or via `~/.databrickscfg` (by using the profile name)?

**Comment by renardeinside** [comment]
In both cases, please verify that the host string looks like this:

`host=https://{domain}`

**without** any o={orgId} postfix.

We've seen this exception when in the profile the host=https://{domain}/?o={orgid} format is used for Azure. It is valid for the databricks cli, but not for the API. If that's the cause, once the "?o={orgid}" suffix is removed, the problem should be gone.

**Comment by Abhendu21** [comment]
Thanks Ivan, it  surely worked like a charm for me.
I have a different question, but I will post it in a different issue. For now I can happily close this issue.
Many thanks for the quick help :)
