### ISSUE TITLE
[DISCUSSION] Organizing different trigger conditions with Github Actions

### ISSUE THREAD

**Issue by Abhendu21** [databrickslabs/dbx#86]
I was going through the DBX CICD repository as below - 
databrickslabs/dbx: CLI tool for advanced Databricks jobs management. (github.com)
I have a python project where I have done CI integration and testing framework as per DBx project suggestion. Now I want to perform promotion of the project based of tag creation in each environment (for dev to sit a promotion of code will happen when a tag t-* is created; for sit to pre-prod a promotion of code will happen when a tag rc-* is created;)
Could you please help me as understand as how can I make it possible with the DBX CICD approach.
Any help is appreciated.

**Comment by renardeinside** [comment]
Hi @Abhendu21 , 

this is not directly related to dbx (dbx is just a deployment mechanism in this case. 

You can set up such rules in your Github Actions, for instance:
1. Define environment variables for each environment (workspace):
```
## for dev
DEV_DATABRICKS_HOST="some-host"
DEV_DATABRICKS_TOKEN="some-token"

## for ppd (pre-prod)
PPD_DATABRICKS_HOST="some-other-host"
PPD_DATABRICKS_TOKEN="some-other-token"


## for live
LIVE_DATABRICKS_HOST="some-other-host"
LIVE_DATABRICKS_TOKEN="some-other-token"


```

2. Define different GitHub pipelines per each environment:

```
# .github/workflows/dev.yaml

on:
  push:
    tags:
      - 't-*' # Push events to matching t-*
```

3. switch between different variables (for example, for dev):

```
env:
  DATABRICKS_HOST: ${{ secrets.DEV_DATABRICKS_HOST }}
  DATABRICKS_TOKEN: ${{ secrets.DEV_DATABRICKS_TOKEN }}
```

I would recommend reading this doc on [workflows](https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions) conditioning and this one on [env](https://docs.github.com/en/actions/learn-github-actions/environment-variables) variables usage.

**Comment by renardeinside** [comment]
Hi @Abhendu21 , 
since the question is not really related to dbx, I'll close the ticket. Please feel free to create another issue if the problem won't be resolved.
