### ISSUE TITLE
[BUG] Stuck at creating a new context when running dbx execute

### ISSUE THREAD

**Issue by kiranvasudev** [databrickslabs/dbx#91]
## Expected Behavior
`dbx execute` should run the job specified in the deployment configuration using the format mentioned in [this link](https://github.com/databrickslabs/cicd-templates#deployment-file-structure)

## Current Behavior
On running `dbx execute`, it gets stuck as shown below. The last time `dbx execute` was stuck for ~6 hours.

![image](https://user-images.githubusercontent.com/16002904/138303462-23d75195-d9b4-4937-b3e8-ffc4b1652bd7.png)

## Steps to Reproduce (for bugs)
1. Install dbx ( I tried v0.1.6 and v0.2)
2. run a job on an all purpose cluster using dbx
`dbx execute --cluster-name="<cluster name>"  --job="<job-name>"`

## Your Environment
* dbx version used: 0.2 and 0.1.16
* Databricks Runtime version: 7.3LTS and 8.4

**Comment by renardeinside** [comment]
Hi team, this is fixed in 0.2.1, please update your versions. Thank you for pointing out the bug.
