### ISSUE TITLE
[ISSUE] CLI commands are a bit slow

### ISSUE THREAD

**Issue by renardeinside** [databrickslabs/dbx#95]
## Current Behavior

Even getting a simple `dbx --help` takes quite a long time (comparison with the main CLI shows that dbx is **5.8 times slower** ):

```
time dbx --help # > dbx --help  2.09s user 1.06s system 72% cpu 4.310 total
time databricks --help > databricks --help  0.36s user 0.14s system 93% cpu 0.538 total
```

Would be great to debug why it works in this way and how to improve it.  

* dbx version used: 0.2.1
* Databricks Runtime version: N/A

**Comment by michal-szklarczyk** [comment]
Not sure if this is related but I noticed a significantly longer time of deploying job with YAML(~14m) configuration than JSON (~10s).

- dbx version used: 0.2.0 and 0.2.2

[dbx][2021-12-10 11:36:21.829] Starting new deployment for environment b2s_jobs_prod
[dbx][2021-12-10 11:36:21.836] No environment variables provided, using the ~/.databrickscfg
[dbx][2021-12-10 11:36:23.423] Re-building package
[dbx][2021-12-10 11:36:24.635] Package re-build finished
[dbx][2021-12-10 11:36:24.635] Locating package file
[dbx][2021-12-10 11:36:24.646] Package file located in: dist\databricks_jobs-1639132584-py3-none-any.whl
[dbx][2021-12-10 11:36:24.672] Requirements file is not provided
[dbx][2021-12-10 11:36:24.673] Deployment will be performed only for the following jobs: ['b2s_dim_business_hubspot']
[dbx][2021-12-10 11:36:25.540] Deploying file: .
[dbx][2021-12-10 11:50:50.117] File is already stored in the deployment, no action needed
[dbx][2021-12-10 11:50:50.347] Deploying file: dist\databricks_jobs-1639132584-py3-none-any.whl
[dbx][2021-12-10 11:50:52.150] Deploying file: jobs\batch\b2s\dim_business_hubspot.py
[dbx][2021-12-10 11:50:52.825] Updating job definitions
[dbx][2021-12-10 11:50:52.825] Processing deployment for job: b2s_dim_business_hubspot
[dbx][2021-12-10 11:50:53.052] Updating existing job with id: 5093 and name: b2s_dim_business_hubspot
[dbx][2021-12-10 11:50:54.667] Updating job definitions - done
[dbx][2021-12-10 11:50:55.936] Deployment for environment b2s_jobs_prod finished successfully

**Comment by renardeinside** [comment]
The main reason - imports of `mlflow` and `pandas` are taking quite a long time (approx. 2 seconds). Since these libraries are in the core, esp. `mlflow`, there is no potential way to make it faster.
