### ISSUE TITLE
[QUESTION] Is dbx capable to update jar-based library on existing cluster? 

### ISSUE THREAD

**Issue by norbertmwk** [databrickslabs/dbx#96]
## Context

In my use case I need to work at one cluster instead of creating new for each job due to security requirements (cluster must be located in specific vnet). 
According to this [docs page](https://docs.databricks.com/libraries/cluster-libraries.html#update-a-cluster-installed-library) the only way to update cluster installed library is to first uninstall it, restart cluster and then install it once again. 

So I just want to confirm, that currently dbx is not capable of doing "reinstallation" of the library? 

## Your Environment

* dbx version used:
* Databricks Runtime version:

**Comment by renardeinside** [comment]
hi @norbertmwk , 

It's possible with dbx, but it's a painful workaround. 

1. add library location as a separate file argument:
```json
{
    "default": {
        "jobs": [
            {
                "name": "<some-job-name>",
                "existing_cluster_id": "<some-cluster-id>",
                "libraries": [],
                "email_notifications": {
                    "on_start": [],
                    "on_success": [],
                    "on_failure": []
                },
                "max_retries": 0,
                "spark_python_task": {
                    "python_file": "<package-name>/jobs/sample/entrypoint.py",
                    "parameters": [
                        "--library",
                        "dist/<path-to-whl-file>",
                        "--conf-file",
                        "conf/test/sample.json"
                    ]
                }
            }
        ]
    }
}
```

2. Add the following to your entrypoint:
```python
from argparse import ArgumentParser
from pyspark.sql import SparkSession
from pyspark.dbutils import DBUtils


class LibraryInitializer():
    def __init__(self) -> None:
        print("Initializing job on interactive cluster with library argument")
        p = ArgumentParser()
        p.add_argument("--library", required=False, type=str)
        p.add_argument("--conf-file", required=False, type=str)
        self.namespace = p.parse_known_args()[0]
        self.spark = SparkSession.builder.getOrCreate()
        _utils = DBUtils(self.spark)
        _utils.library.install(self.namespace.library)
        _utils.library.restartPython()
        print("Library installed")


def provide_job(initializer):
    from lib_on_interactive.common import Job

    class SampleJob(Job):

        def launch(self):
            self.logger.info("Launching bootstrap job")
            self.logger.info(f"Job started with namespace {self.namespace}")
            self.logger.info(f"Job configuration: {self.conf}")
            self.logger.info("Bootstrap job finished!")

    _job = SampleJob(spark=initializer.spark, namespace=initializer.namespace)
    return _job


if __name__ == "__main__":
    initializer = LibraryInitializer()
    job = provide_job(initializer)
    job.launch()
```
3. always add this option to deploy command: `--no-package`

**Comment by norbertmwk** [comment]
oh I forgot to mention that I'm using scala and I actually need to update compiled locally jar file

**Comment by renardeinside** [comment]
I would assume this is impossible since you cannot change a compiled dependency in runtime, but I might be wrong. 
Asking for the help of the wisest @alexott ;)

**Comment by alexott** [comment]
To uninstall library cluster restart is required

**Comment by renardeinside** [comment]
hi @norbertmwk , 
I've checked and yes - there is no other way for jar-based libraries than the one you've outlined. You can use the databricks CLI to automate these steps (uninstallation/restart).
